### ISSUE TITLE
Bug with https detection on nginx reverse proxy

### ISSUE THREAD

**Issue by gilles-hemmerle** [octobercms/october#1001]
When you are using an niginx reverse proxy, the october cms is not able to generate urls properly. It generates urls with http:// schema and this break entirely the website because resources cannot be fetched over http when you are browsing the site on https for evident security reasons.

This is due to the fact that nginx is receiving the https://url/you/are/looking/for but it is sending the request internally over simple http protocol. You must use the $_SERVER['HTTP_X_FORWARDED_PROTO'] variable to determine if the https protocol is used by the client.

Here's an example of workaround to fix this issue : https://github.com/iabsis/october-cms-nginix-reverse-proxy. Maybe you want to include this feature directly in your core. An other better solution should be not to include the schema and domain name in your generated urls.

**Comment by daftspunk** [comment]
Have you looked at the `cms.linkPolicy` configuration item? It may be the solution for you.

**Comment by gilles-hemmerle** [comment]
It doesn't seem to solve the problem.

* If I use **detect**, the script is always generating urls with http:// because of the nginx reverse proxy
* If I use **secure** or **insecure**, it's impossible to switch between http:// or https:// because generated link will always use the forced schema
* If I use **force**, it's the same problem as with the two previous arguments. (I've tried to setup the app.url with only //domain-name/ to check if the application will generate urls like //domain-name.com/url/of/page. But again, the cms is generating links as domain-name/domain-name/url/of/page.

Maybe the solution would be to add a parameter like **noschema** to  generate url starting with //domain-name or fix the **detect** mode in order to properly detect https mode when using a reverse proxy.

**Comment by flip4bytes** [comment]
@gilles-hemmerle This is something that was kind of discussed in-depth in this issue --> https://github.com/octobercms/october/issues/856

It's something that I have been dealing with for about 3 months now (since switching my October site over to https://). What I have found out is that the ONLY way that you can get it properly working with detect (e.g. when it's on localhost it's non-https, when it's on my dev server, it's non-https, and when it's on the production server, it is https) is by purchasing and installing a proper SSL certificate to my site. The problem is that October is detecting from the **server** to the site, while the visitors are seeing the code client-side. So the visitor could visit an https connection, but the code was detected and served from the server as http because it doesn't have a server-side SSL Certificate telling it to be SSL encrypted.

I know it's a pain, I have since purchased an SSL certificate and installed it to the site and it has remedied everything, though it is a bit disappointing that I had to purchase a proper SSL Cert in order to fix the detection problems.

At the end of the day, if the URL's were served relative or //website.com (just without the http or https entirely)  then this wouldn't be a problem. Though, see here https://github.com/octobercms/october/commit/47eff923e5b8a7a90bb931fac40628938ff16678 @daftspunk tried to impliment a relative link policy but I guess it didn't play friendly with Laravel (read the comments in the bottom).

I'm sure this is a topic of discussion that isn't going to go away anytime soon and is going to be a real hassle for many people until somebody comes along with a great solution to fix it. It's just so funny how if you just use basic PHP or vanilla HTML/CSS to make a website, you always use relative assets and then you never run into any problems when switching between HTTP and HTTPS. Only when frameworks get involved does such a basic feature become complicated to implement so it seems.

**Comment by daftspunk** [comment]
[Reverse proxy plugin](https://github.com/JoelESvensson/october-trusted-proxy) might be of some help here.
