### ISSUE TITLE
Create a 'password' field type

### ISSUE THREAD

**Issue by abass** [octobercms/october#1061]
When you remove all permissions for a user, they still have access and can edit the MISC sub-category in settings on the backend which is terrible because some really important information that shouldn't be messed around with is there. To name a few plugins:

Google Analytics - Contains tons of keys & codes that will completely break it's dashboard functionality if changed.

Mailchimp - Contains the MailChimp API Key which would be very bad if changed by accident.

Disqus - Contains the Disqus API Site Key that would break comment section if changed.

**Comment by daftspunk** [comment]
These are concerns that should be raised with the plugins themselves, as they are not secured correctly.

Leaving this open as a reference to fix it.

**Comment by LarBearrr** [comment]
Not sure if this issue has been raised before or whether or not it belongs here, but this is the closest I could find to the issue I'm having.

I've noticed that changing a password field type to text allows the hashed password to come through, despite the field being in the model's hidden property.

For example, if you change the password field type in the Backend\Models\User class to text, and navigate to the update administrator page, you can see the hashed password:
![image](https://user-images.githubusercontent.com/28734844/51340422-7f7d3d80-1a54-11e9-8d0a-eaca849a623e.png)

This seems like it could be a security concern given someone could inject a new field and set the type to text to get the password. I believe this is because the FormController behavior is injecting an instance of the model object rather than returning the accessible fields. 

Are there any thoughts on this and whether or not this is expected behavior? Am I missing something?

Thanks!

**Comment by LukeTowers** [comment]
@LarBearrr this is an expected behaviour, the model's `hidden` property is only for uses of `toArray()`. 

This is not a security concern as client's injecting fields in their own browser has no effect on what October sends the client in terms of model data and if you're talking about plugins extending the fields serverside, well it's much easier for them to just to `steal_hashed_passwords(User::all())` then to muck about with changing a field type and going to a my account page, just to obtain their own hashed password.

**Comment by Samuell1** [comment]
Looking trough source code field type password already exists.

https://github.com/octobercms/october/blob/develop/modules/backend/widgets/form/partials/_field_password.htm
