### ISSUE TITLE
Media Manager bound to all backend controllers?

### ISSUE THREAD

**Issue by dooplenty** [octobercms/october#1089]
I'm not sure if this is really an issue or just wrong expectations on my part. It seems it was an implementation decision to bind the media manager widget to all backend pages by binding it in the backend/classes/Controller.php class constructor. The issue I ran into after my last update is that my implementation now renders that media manager widget under one of my backend tabs. Here is my use case...

In plugins/dooplenty/custom/controllers/CustomController.php `__construct` I instantiate five widgets that will be rendered in this backend section. 

```
new WidgetExtendingWidgetBase($this, $alias, $customParam);
new WidgetExtendingWidgetBase($this, $alias, $customParam);
new WidgetExtendingWidgetBase($this, $alias, $customParam);
new WidgetExtendingWidgetBase($this, $alias, $customParam);
new WidgetExtendingWidgetBase($this, $alias, $customParam);
```

I assign a var of all widgets in `index` of this controller, assuming the array of widgets is scoped to just my CustomController.

```
$this->vars['widgets'] = $this->widget;
```
I do this so that in my view file i can loop through the widgets added and display them dynamically on the screen. 
```
foreach($widgets as $tpl => $widget){
//display some widget stuff
```
so of course the media manager widget is now in this array and displays on my page as well.

**Comment by daftspunk** [comment]
I have confirmed this is by design, the Media Manager is a first class citizen and is bound to all backend controllers. I have also confirmed the widget construction adds no logic that would impact performance in any way.

The reasoning for this is the MM can potentially be spawned by anything, not just the Media page or Rich Editor toolbar. While both instances could potentially interact with the controller to register their interest to use the MM, it is just nicer if they didn't have to. That way a JavaScript plugin alone has the potential to spawn MM, for example.

I would suggest excluding it from your collection when displaying the widget stuff =)
