### ISSUE TITLE
Nesting limit reached error when adding second repeater item

### ISSUE THREAD

**Issue by Flynsarmy** [octobercms/october#1113]
I have a very barebones plugin that just has a simple repeater field in its form. Clicking 'Add new Item' twice results in an alert error
> "Maximum function nesting level of '300' reached, aborting!" on line 141 of /path/to/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php

Replicatable demo repo [here](https://github.com/Flynsarmy/oc-badrepeater-plugin).

**Comment by daftspunk** [comment]
This occurs because the Repeater widget uses a `Form` widget too, so you are extending the primary form and also the repeater with this code, It creates an infinite loop:

        Event::listen('backend.form.extendFields', function(\Backend\Widgets\Form $form) {
            if (!$form->getController() instanceof \Test\BadRepeater\Controllers\Testimonials)
                return;
            $form->addFields([
                'settings[options]' => [
                    'label' => 'Options',
                    'tab' => 'Appearance',
                    'type' => 'Backend\FormWidgets\Repeater',
                    'form' => [
                        'fields' => [
                            'key' => [
                                'label' => 'Key',
                                'type' => 'text',
                            ],
                            'value' => [
                                'label' => 'Value',
                                'type' => 'text',
                            ],
                        ],
                    ],
                ],
            ], 'primary');
        });

The following change should allow you to access the primary Form widget to extend that only:
https://github.com/octobercms/october/commit/1e8bf5d62b0a4f5ae2f35715b5658dbaf8267144
