### ISSUE TITLE
Component assets not being injected in layouts when attached in partials 

### ISSUE THREAD

**Issue by justin-lau** [octobercms/october#1118]
Not sure if this is a bug.

I have attached a custom component in a partial, which is included by a layout. The component injects assets in its `onRun()` method. The layout is responsible for including the `{% styles %}` tag and injecting assets.

If it was a page where I attach my component, the assets are being injected perfectly. However, in the case of partials, the page calls `makeAssets()` before the component's `onRun()`, so whatever I wanted to inject was left behind. They can only be injected if I put the `{% styles %}` in the partial itself.

**Comment by daftspunk** [comment]
Using components inside partials has [very limited functionality](http://octobercms.com/docs/cms/partials#life-cycle-limitations), since they are executed so late in the page cycle. The assets have already been rendered before the component has a chance to contribute to them. You may have more success by adding the component to the Layout instead.

**Comment by swt83** [comment]
I also had trouble with this issue.
