### ISSUE TITLE
Root url

### ISSUE THREAD

**Issue by polikin** [octobercms/october#1138]
It is possible to change the root url from `/` to `/en` or `/fr`?

**Comment by flip4bytes** [comment]
That's exactly what the [Translate Plugin](http://octobercms.com/plugin/rainlab-translate) is meant for. Give it a try, it's really robust. He recorded a video showing it off too, go check that out on the translate plugin page.

**Comment by polikin** [comment]
Yeah, I installed this plugin, but.. It doesn't work for unknown reason. I can translate text, but not the slug url. I will read the docs again.

**Comment by flip4bytes** [comment]
Yeah, just [watch the video](https://vimeo.com/102449697) he shows off changing around the urls. Seems kinda weird that you would want the root url to change though. Just have the default language be at the normal `/` and then any secondary languages be on `/fr` or whatever else it is. That's how most sites do it. Look at a giant company like [Razer](http://www.razerzone.com) or [Apple](http://www.apple.com/) for example. The main site is in English (because most of their users are English speakers) but they have a "change location" selector at the bottom and then it changes the url to `/br` or whatever language you choose. It then places that in your cache so any pages you visit continue to stay within the selected language. The main language of a site really should just be at the root `/` honestly.

**Comment by polikin** [comment]
Yes I agree. I'm playing around with translation.. so I tried few thing. My problem seem to be with the translation of Static Page component.

**Comment by polikin** [comment]
I don't know how can I translate a Static page.

**Comment by daftspunk** [comment]
Not sure how this relates to the October CMS core repository?
