### ISSUE TITLE
Can't login anymore

### ISSUE THREAD

**Issue by Sjoerdjanssenen** [octobercms/october#1158]
So, all of a sudden I'm getting this error `There is no an authenticated user to load or save preferences for.` on the backend login page. The only thing I did before logging out, was adding another user that I've since deleted in the database. I keep getting this error though.

**Comment by Pharetra** [comment]
Same problem here. Didn't add a user, but I did update my OctoberCMS installation a while ago. Maybe it's related to the update?

**Comment by Sjoerdjanssenen** [comment]
Yes, I did an artisan update and it showed a bugfix relating to it.



—

**Comment by Pharetra** [comment]
In case anyone is struggling to update their installation because they can't login to the backend, this worked for me:

1. Open modules/backend/models/UserPreferences.php
2. Navigate to line 35, which says
 `throw new SystemException(trans('backend::lang.user.preferences.not_authenticated'));`
This line says that October will throw an error. This line will only be executed if the condition in the if statement above is true, or in this case, if !$user evaluates to true.
3. Place two forward slashes in front of the code, like this:
`//throw new SystemException(trans('backend::lang.user.preferences.not_authenticated'));`
This means that this line will not be executed. You won't get an error and you can login to the backend.
4. Login to the backend. You probably already know how.
5. Update your installation. This bug was fixed a while ago.
6. If October has installed the update, you can open UserPreferences.php again. Remove the two forward slashes we just added and upload it to the server. You can now login to the backend again.
