### ISSUE TITLE
webpage background artifacts

### ISSUE THREAD

**Issue by skaviouz** [octobercms/october#1193]
![background artifacts](http://i.imgur.com/Oea5Drj.png)

I don't know what would be the cause, but

stuff:
June 7th, 2015
Firefox 38.0.5
windows 10_10041

switching tabs back and forth (control-tab, control-shift-tab) temporarily stop this bug, but it comes back after a minute or two. I havn't seen this before, and I've been using this firefox build for couple days now; so I'm assuming it's the website's html/css/js

**Comment by flip4bytes** [comment]
This totally looks like a graphics card/drivers issue. Definitely not HTML.. Does the same happen when you open the page in Chrome? And is it happening throughout the site, or only on that one select page?

**Comment by skaviouz** [comment]
I can't recreate this in IE so it must be a firefox bug. i'll look forward issue to them.

**Comment by flip4bytes** [comment]
Yeah, if you can't recreate in any other browsers then it's most likely an issue with the browser, (primarily too because that looks nothing like an html/css/js bug, looks more like a browser glitch, especially seeing as switching tabs back and forth temporarily fixes it). As you mentioned, you just recently updated a few days ago so there are probably many other sites being affected by it. Definitely reach out to Firefox, or just hold tight as I'm sure an update will come in the next few days to remedy that bug. They are normally good with that stuff.

**Comment by mrmlnc** [comment]
Windows 10 (build 10130)

Firefox 38.0.5 — ok
Firefox 40.0a2 — ok
Vivaldi 1.0.162.9  — ok
Maxthon Nitro 1.0.1.3000  — ok
Chrome 44.0.2403.30 beta-m  — ok
Spartan 15.10130.0.0  — ok

It is unlikely that the problem in browsers. I am sure that the problem is on your side. There may be a problem in Windows 10 build 10041.

**Comment by daviskoko** [comment]
@Denis, this has nothing to do with October, I use the same firefox build
(view below)
Please re-install the driver of your graphics card & if the issue persist,
reinstall you windows.
Consider changing the graphics card if the two options above did not solve
your problem.[image: Inline image 1]

**Comment by daftspunk** [comment]
Confirmed single user issue
