### ISSUE TITLE
Documentation request for setting up SSL

### ISSUE THREAD

**Issue by dhiva** [octobercms/october#1214]
I have looked into the documentation of OctoberCMS but I cant find any documentation on setting up SSL and on securing the websites. I have troubles setting up/forcing users to use SSL to access backend of the CMS. Any documentation on this topic will be really helpful for people like us.

**Comment by hybridvision** [comment]
I'm not sure of the preferred way of doing this on OctoberCMS (it's not something I've needed yet) but depending on your server setup, a URL rewrite might do the job.

Something like this could be used to force HTTPS for certain URLs: http://stackoverflow.com/questions/4398951/force-ssl-https-using-htaccess-and-mod-rewrite

**Comment by dhiva** [comment]
@hybridvision I tried htaccess rewrite rule but I cant seem to get it working. I want just the backend to be forced to use SSL. A good documentation always helps :)

**Comment by flip4bytes** [comment]
Here's two links for further reading:

https://github.com/octobercms/october/issues/856#issuecomment-71149845

https://github.com/octobercms/october/issues/1001

I'm assuming you're one of the many (like me) that uses CloudFlare. You have to make sure that you don have "Flexible SSL" selected anymore in CloudFlare. You need it to be using the option that forces it. What's probably happening is you're telling the site to force SSL, but CloudFlare is between the server and your site not forcing SSL so the site (like the backend) is not serving up files under HTTPS.

I struggled with this for a solid 4+ months. The easiest solution would be to just have all css/js/img assets be relative instead of having the entire URI. Though Samuel tried getting all of that working and it didn't go so smooth apparently. Search around here and you can get more information. I blew up this repo with discussions about forcing SSL problems. Hopefully you're using CloudFlare and just overlooking the accidental "flexible SSL" issue.

**Comment by FergusInLondon** [comment]
Was this ever resolved?

**Comment by dhiva** [comment]
This issue is not resolved yet. I am yet to find any documentation on it.
There is to be no way to force users to HTTPS when using the CMS backend.

**Comment by daftspunk** [comment]
`cms.linkPolicy` should control how links are generated. The webserver configuration can force a redirect to HTTPS if desired, for example, in the apache .htaccess file. October will never force a redirect like this because it is too magical, however it is possible to do in the layout code or using a plugin.
