### ISSUE TITLE
Bring the public folder back

### ISSUE THREAD

**Issue by tobz-nz** [octobercms/october#122]
Its a pretty big security issue having all your system code in the root folder - not a good idea.

I suggest bringing the default public/ folder back. this would probably also fix issue #107

**Comment by chrisvanderpoel** [comment]
I just wanted to chime in on this having just entered into the OctoberCMS world a few months ago.  Cool, I get it, it's a configuration issue that people can miss in the docs during their zeal to learn a new and exciting application and it can be overcome through some server tweaking -- but -- the one thing I wanted to bring up is that the discovery path for something as potentially nasty as this (and it could be nasty) is convoluted at best, nonexistent at worst.

In order for October to grow, one key thing you need to do is protect new users of your code and not simply assume they are protected through their own devops experience.  We've all seen nascent frameworks enter into the marketplace only to lose their initial momentum because of a security issues that, while not the fault of the actual application, end up putting negative attention on the framework non-the-less.  In the end, the end-users tend to blame the application and not themselves (just look at Wordpress' reputation).

So, I implore you to take a second (or tenth) look at this in order to protect your advancement into the CMS market.  You have a very good product here and I would hate for end user misconfiguration to bring your product into a negative light.

**Comment by daftspunk** [comment]
I can see there is some strong support here. In summary the concerns raised are:

- Nervous about safe deployment in production
- Laravel uses a "public" folder and has a publishing process
- Not using a "public" folder is sacrifice of security
- Not everyone is a system administrator and can configure a web server
- The /vendor folder may contain sensitive files with a safe file extension (.json, .txt, etc)
- October will succumb to the same security problems as Wordpress moving forward

I think that covers everything mentioned. While these are all fair points, the decision to not use a public folder was carefully considered. A publishing process creates duplication and is cumbersome, when a developer updates a JavaScript file, he/she should be able to see the change immediately. Apache is a fantastic web server and provides a `.htaccess` file for people who are not system administrators. Wordpress has an extremely large attack surface area for two reasons: it allows any .php script to be executed; and in general it does not use PHP classes. By only allowing `index.php` to be executed, October does not share this same vulnerability.

While OctoberCMS is opinionated software, these opinions shouldn't be forced on the developer. So as discussed, I have devised a solution that should (hopefully) satisfy the significant response here. In this commit (857c7c715aaf870a598e3f9a4b81909993dd1f58) I have added a new artisan command called **october:mirror**. Example usage:

```
php artisan october:mirror public
```

> **Note**: This command must be run as an administrator in Windows.

Sample output:

```
Destination: public/
 - Mirrored: index.php
 - Mirrored: storage/app/uploads
 - Mirrored: storage/app/media
 - Mirrored: modules/backend/assets
 - Mirrored: modules/cms/assets
 - Mirrored: modules/sandbox/assets
 - Mirrored: modules/system/assets
 - Mirrored: plugins/acme/crm/assets
 - Mirrored: plugins/october/demo/assets
 - Mirrored: plugins/october/test/assets
 - Mirrored: plugins/rainlab/blog/assets
 - Mirrored: plugins/rainlab/blogvideo/assets
 - Mirrored: plugins/rainlab/editable/assets
 - Mirrored: plugins/rainlab/forum/assets
 - Mirrored: plugins/rainlab/googleanalytics/assets
 - Mirrored: plugins/rainlab/mailchimp/assets
 - Mirrored: plugins/rainlab/pages/assets
 - Mirrored: plugins/rainlab/sitemap/assets
 - Mirrored: plugins/rainlab/translate/assets
 - Mirrored: plugins/rainlab/twitter/assets
 - Mirrored: plugins/rainlab/user/assets
 - Mirrored: plugins/responsiv/campaign/assets
 - Mirrored: plugins/responsiv/pay/assets
 - Mirrored: plugins/responsiv/showcase/assets
 - Mirrored: themes/demo/assets
 - Mirrored: themes/vanilla/assets
Mirror complete!
```

This command creates symbolic links to all the necessary folders and single `index.php` file needed for the website to operate. It is a streamlined process, intended to be used in production and should settle any concerns about total security.

I hope this is a satisfactory compromise. Comments please. Thanks @galaxy4public for the idea.

**Comment by w2pc** [comment]
Will this work as well under nginX

**Comment by chrisvanderpoel** [comment]
This sounds like a great compromise that provides us a viable level of compartmentalization.  Thanks @daftspunk!

**Comment by keiosweb** [comment]
Yay! @w2pc it will with right server block configuration :)

**Comment by chrisvanderpoel** [comment]
@daftspunk Looks like some backend assets aren't loading when using the `october:mirror public` command.  Since w're serving from `/public` now, we're going to need to have backend assets respect that as well.  Media manager, in particular, was what got my attention as it cannot load up some asset files in this configuration.

![These files in particular...](https://www.evernote.com/shard/s127/sh/3baa1cf4-a849-431f-9cd6-ac3b0959e73f/7d4314edc6b9e54fb5e120bff19d4cd6/deep/0/Media---October-CMS.png)

**Comment by chrisvanderpoel** [comment]
Also, for anyone out there who might stumble on this:

If you're using homestead, run this command from inside the VM or you're going to run into permission issues.

**Comment by emzero** [comment]
Could somebody post an example of an .htaccess to make it more secured? Meaning forbidding everything except assets and the index.php as described by daftspunk?
Sorry, I'm pretty new at LAMP development.

**Comment by daftspunk** [comment]
Moved this discussion to #1331
