### ISSUE TITLE
[Bug] Media Finder Fixed Ratio crop not cropping

### ISSUE THREAD

**Issue by DanielHitchen** [octobercms/october#1220]
Hi guys, just found a little bug in the Media Finder where when you "crop & insert" an image using the Fixed Ratio selection mode, the image doesn't actually crop, it just inserts as is (full size).

A cropped image gets created in the "cropped-images" folder in the media finder, but it's as the original.

**Comment by DanielHitchen** [comment]
Hi guys, have I just mis-understood the "Fixed Ratio" selection mode? I thought that you could use the fixed ratio selection to constrain the selection box (which is fine), but if you just selected "Fixed ratio" and clicked "Crop & Insert" then the image would just resize to those constraints - or have I just got it wrong?

I know you can click resize and enter the values there, so maybe I've just got confused. If so, just close this issue.

**Comment by alekseybobkov** [comment]
Hi Daniel, the Fixed Ratio selection mode constraints the selection tool so that it keeps the ratio. It doesn't resize the image. If you need to resize, use the Resize button. The Resize tool doesn't use the selected area, it resizes the entire image. So, in some cases you will need to use Resize + Select area (optionally - using the fixed ratio selection) + Crop & Insert.
