### ISSUE TITLE
Media Finder: add imageWidth and imageHeight parameters

### ISSUE THREAD

**Issue by gergo85** [octobercms/october#1233]
It would be great, if the Media finder widget could support the imageWidth and imageHeight parameters like File upload widget.

**Comment by matthewerskine** [comment]
+1

**Comment by Almusamim** [comment]
+1

**Comment by Almusamim** [comment]
1+

it would also be nice to have auto crop popup opening with image upload option.. something like cropModal: true

**Comment by khoatran** [comment]
+1 Exactly what I need

**Comment by LukeTowers** [comment]
The support demand for October is increasing, while the available time the founders have to give remains the same. These issues will be handled in time, however there are ways you can help:

- Submit a pull request that introduces this feature and wait for it to be reviewed
- [Post a bug bounty](https://www.bountysource.com/teams/october) for this specific issue so that more people can become involved with creating a fix
- [Make a financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone

**Comment by daftspunk** [comment]
Fixed by #2894 and the great @gergo85!

**Comment by daftspunk** [comment]
This should be available in Build 420+
