### ISSUE TITLE
Chrome backend height 100% pushes content

### ISSUE THREAD

**Issue by emcniece** [octobercms/october#1236]
For some strange reason, I've got 2 fresh installs doing the same thing in Chrome Version 45.0.2440.3 canary (64-bit) 

It looks like the `.layout > .layout-cell{ height:100% }` is bugging out and pushing the navbar to full screen height.

![Chrome table height bug](http://i.imgur.com/rlbNwKd.jpg)

I'm on 2 totally different servers, one on build 261 and the other on build 271. Firefox works fine. Anyone else experiencing this?

**Comment by daftspunk** [comment]
Doesn't look like anyone else has the issue, have you tried disabling all your Chrome extensions?

**Comment by flip4bytes** [comment]
This! I'm experiencing it too, but ONLY in Chrome Canary. It very well could possibly be an extension, but it happened after updating the build if I remember correctly. Started happening a week and and half ago. ONLY happening in Chrome Canary. Not in normal chrome, Firefox, IE, nothing. When I get home I'll test if it's an extension. I assumed it was just a Canary bug but it has existed for a few weeks now and chrome has updated numerous times since then. I figured it'd just work itself out. I'll check back soon!

**Comment by flip4bytes** [comment]
@daftspunk I disabled all extensions and it still seems to be happening for some reason. Again, only  happening in Chrome Canary.

[![IMG](https://s3.amazonaws.com/f.cl.ly/items/2X0u1R2A1X1s3m2t0g3d/Image%202015-06-27%20at%2011.28.14%20PM.png)](https://s3.amazonaws.com/f.cl.ly/items/2X0u1R2A1X1s3m2t0g3d/Image%202015-06-27%20at%2011.28.14%20PM.png)

**Comment by emcniece** [comment]
This seems more and more like a Canary bug - it's turning up in other places too along with other weird CSS issues... like my WordPress backends and some online IDEs and editors. Closing due to irrelevance.

**Comment by dtaub-mms** [comment]
Wanted to chime in and say I'm having this issue as well on Chrome 45.0.2454.15 beta-m.

**Comment by triagmas** [comment]
Same on 46.0.2478.0 dev-m (64-bit)

**Comment by mrmlnc** [comment]
@triagmas, @dtaub-mms

In Chrome beta (46.xxx) there is a problem with the control panel. Current release Chrome has no problems (44.xxx).

**Comment by arku31** [comment]
Bug still actual in Chrome 46.0.2490.80 m
https://www.dropbox.com/s/jw8f22wz0vk0su2/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-10-23%2014.12.30.png?dl=0
