### ISSUE TITLE
Link to media file as a snippet parameter of a static page

### ISSUE THREAD

**Issue by kapooostin** [octobercms/october#1298]
I'd like to create a snippet from a partial. And to let a user insert a link to an image from Media Manager. At the moment she can do it by finding an image in Media Manager and copying its direct URL.

It would be much more convenient to show Media Manager in a popup when a user clicks on a snippet inserted in my static page just like it is done in richeditor.

I do not have a lot of experience with October so maybe I miss some obvious way to solve this issue.

**Comment by daftspunk** [comment]
I suppose for this we would need a Media Manager component property type in the inspector. Clicking the snippet will only ever show the inspector properties.

**Comment by kapooostin** [comment]
Yes, I guessed it from the source. Do you plan to add such an inspector.

Пн, 27 июля 2015 г. в 10:51, Samuel Georges <notifications@github.com>:

**Comment by jajacobs** [comment]
I would be nice if the Media Manager would popup when using the file upload form widget too.

**Comment by hybridvision** [comment]
:+1: 

Yes, this would be a really useful feature and would make the editor even more client-friendly. Currently it's not easy to insert custom markup involving uploaded media - this is the missing link.

Another semi-related point (which should probably be in its own ticket) is regarding the snippet titles: if you have multiple snippets of the same type on a page, they all have the same title and are impossible to differentiate.

I see that the snippet title is set in CSS from a data attribute so there's no simple solution for giving them different titles based on the properties because the properties could be anything. Maybe the snippet could set which property is optionally used in the title for unique identification. I'm still thinking about this one and I'll probably submit a separate ticket but I thought I'd mention it here anyway!

**Comment by BenjaVR** [comment]
Are there any plans yet to add this in the near future?

**Comment by daftspunk** [comment]
It is a planned feature but low priority at the moment. Feel free to submit a bounty if you want to see it sooner.

**Comment by LukeTowers** [comment]
The support demand for October is increasing, while the available time the founders have to give remains the same. These issues will be handled in time, however there are ways you can help:

- Submit a pull request that introduces this feature and wait for it to be reviewed
- [Make a financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone
