### ISSUE TITLE
Building configuration files - Progress failed

### ISSUE THREAD

**Issue by fourroses666** [octobercms/october#1370]
I want to check out this CMS but can't install it.
Seems I'm not the only one with this problem.
I'm stuck at installing. Building configuration files -> Progress failed

All info I can give is I'm on shared hosting with PHP 5.5.25
Played with .htaccess and chmod but I don't think thats the issue, also no issues on the server check.

**Comment by hybridvision** [comment]
If you are looking to check it out, I'd suggest you start with a local environment since there are so many variables with shared hosting that can complicate the process.

Since OctoberCMS is built on top of Laravel, a very nice match is Homestead: http://laravel.com/docs/5.1/homestead - it's a virtual machine with all the latest tools and is very simple to install with Vagrant.

I'm using Homestead and have had no problems with installation at all. Give it a try :)

**Comment by fourroses666** [comment]
Thanks for your reply.

I just want to install it on the host. :(
Having to figure out how to install it local I don't want to do at this time.

With all respect, it should work out of the box. 
Could be many reasons like server settings but why it isn't giving any errors when checking the server. Shouldn't pass the check.

**Comment by fourroses666** [comment]
OKE, this is weird..

I shut down Filezilla FTP, my installation screen was still open.
So I clicked on the "try again" button one more time and it continued installing...!

**Comment by fourroses666** [comment]
More weird stuff.. can't reach the backend login.
I tried an other browser, all of a sudden the login was visible. 
Refreshed the page a couple of times and now its gone, page not found. 

Safari showed http://site.com/manager/backend/auth
then refresh and showed http://site.com/manager/backend/auth/signin

but both screens blank..

**Comment by fourroses666** [comment]
Just check here: http://www.october.esensdev2.nl/manager/backend/auth/signin
Cleared cache and sessions / removed browser cookies:
I see the login screen on Chrome but not in Firefox... I'm about to delete this and forget about it.

**Comment by hybridvision** [comment]
I understand how frustrating this is and the server check should pick up major issues but I think it's unrealistic to expect it to catch every possible problem with the server config. Some hosts have unusual settings that can cause unexpected problems so that's why I suggested the simpler route of installing it locally first.

OctoberCMS is still a young project so you have to expect some bumps along the road but it's worth persisting... Even with something as mature as WordPress, you'll find a myriad of problems on some hosts that can stop it installing. The only host I've tried OctoberCMS on has been WebFaction and it worked very nicely.

I could see the login screen for your site but first I got an ERR_EMPTY_RESPONSE in Chrome so there's something going on with your host that is making it return an empty response. This plus the blank screens suggest that there is an error occurring but error reporting must be turned off (as it should be in production). Try turning error reporting on and checking the logs on your host...

OctoberCMS chat is here: http://octobercms.com/chat and they also have a forum.

**Comment by fourroses666** [comment]
Thanks hybridvision, I have deleted it for now. 
Might try another install in the future. :(

**Comment by hybridvision** [comment]
You're welcome :) Best of luck!

**Comment by DanielHitchen** [comment]
@fourroses666 Hi, have a look at your ```phpInfo()``` and check what the ```max_execution_time``` is set to on your shared hosting

**Comment by fourroses666** [comment]
Hi, it's 30

**Comment by fourroses666** [comment]
I have set: ``max_execution_time = 300`` in php.ini

Still the same issue

**Comment by fourroses666** [comment]
Install.log header says:
`` [2015/08/14 10:21:37] Host: Linux shared.xxx.nl 2.6.32-29-pve #1 SMP Thu Apr 24 10:03:02 CEST 2014 x86_64
[2015/08/14 10:21:37] PHP version: 5.5.25
[2015/08/14 10:21:37] Server software: Apache/2
[2015/08/14 10:21:37] Operating system: Linux
[2015/08/14 10:21:37] Memory limit: 128M
[2015/08/14 10:21:37] Max execution time: 3600 ``

**Comment by daftspunk** [comment]
In our environment we had to tell FastCgi to use a longer timeout

```
FastCgiExternalServer /usr/lib/cgi-bin/php5-fcgi -socket /var/run/php5-fpm.socket -pass-header Authorization -idle-timeout 900
```

See `-idle-timeout 900`

**Comment by fourroses666** [comment]
Hmm I'm on shared hosting. can't see any setting like that in phpinfo()
I only see ``Timeouts 	Connection: 60``

**Comment by daftspunk** [comment]
The PHP or Apache error log will usually give you an exact reason for the failure, check these logs and we can target the web server's complaint specifically.

**Comment by daftspunk** [comment]
We are looking for you [in the chat](http://octobercms.com/chat), it might be easier if you join us there.

**Comment by fourroses666** [comment]
Unfortionately no error logs.

**Comment by daftspunk** [comment]
We discovered this may be caused by a segfault in Apache 2.4 when using DirectAdmin. The workaround for now is to use Apache 2.0 or 2.2.

[See this article](https://forum.directadmin.com/showthread.php?t=43572) for more details

**Comment by hybridvision** [comment]
Glad you figured it out - thanks for the update on the resolution :)
