### ISSUE TITLE
Updating plugin version

### ISSUE THREAD

**Issue by ab192130** [octobercms/october#1402]
Hi October Team,

I need some help with your awesome CMS. I wanna know, how to update **just a one plugin** via **october:up** console operation? Is it possible?

Thanks for your attention!

**Comment by shina** [comment]
No, you can't. However, you can lock plugins to update on Configurations > Updates > Manage Plugins

**Comment by ab192130** [comment]
Thanks, @shine. I would be so happy if It could be possible with just a single console command like **plugin:upgrade** or **plugin:up**. I think it is not so bad idea.

**Comment by gabsource** [comment]
At the end of https://octobercms.com/docs/plugin/registration you can read
> To apply plugin updates during development, log out of the back-end and sign in again. The plugin version history is applied when an administrator signs in to the back-end. Plugin updates are applied automatically for plugins installed from the Marketplace when you update the system.

In fact whenever a backend user has been successfully authorized the update manager is triggered and updates plugins.

**Comment by daftspunk** [comment]
I can't think of any reason why this is needed? Can someone help me out here.

**Comment by gabsource** [comment]
As I understood it, @ab192130 wants to run a migration on __a single plugin__ (maybe without disconnecting from the back-end) and because `plugin:refresh` does a full reset it may remove database entries (and maybe he don't want that).

**Comment by daftspunk** [comment]
I understand the "want" just not the "why"

Migrating a single plugin could be dangerous if it depends on other plugins. It leaves the question do we tell it to migrate these dependencies too? `october:up` is the best solution because dependencies can be evaluated and the correct migration order is used. Without knowing why anyone would want to migrate a single plugin the solution is unclear.

**Comment by gabsource** [comment]
A I see it, the only reason why it would be needed, is in special development cases. 
As when you are developing a multiple plugins at the same time, wrote their version file which contains not yet applied migrations and then only want to apply those from a specific plugin...

I think `october:up` is the simple and best way to run migration, even in dev. Maybe @ab192130 could explain his use case in details.

I'll close the PR.

**Comment by ab192130** [comment]
Thanks @gabsource, @daftspunk, i read your replies and came to decision that **october:up** is the best solution right now. Thanks for all!

**Comment by bekerov** [comment]
same problem. developed plugin, have many info in database and cant update (add some columns to plugin database)

**Comment by colthreepv** [comment]
What is the best way to test while developing a migration?

As Example I have a migration that creates a slug field, then creates all the slugs from the already-existing rows in the table.

It happened that I got the code wrong multiple times, and what I wanted to do was to:

  1. rollback plugin to previous version
  2. re-apply migration
  * check if result is adequate
  * if everything ok, commit, otherwise go back to 1

I did it manipulating the database directly, dropping the column and manipulating `system_plugin_version` and `system_plugin_history`

It was **really** painful, any suggestions?

**Comment by LukeTowers** [comment]
@colthreepv Nope, that's pretty much the way to do that right now. Create a separate issue if you have any ideas that you're willing to implement for an easier way of doing that.

**Comment by paishin** [comment]
Any updates on this? I think this is really needed. Each time we release a newer version of our plugin we have to run the migrations manually because we don't want data stored in the database to be lost by running plugin:refresh. It would be great if we could just run plugin:update and continue running commands from version.yaml that have not been called yet.

**Comment by LukeTowers** [comment]
@paishin that's what the `october:up` command is for. It runs any pending migrations that haven't been run yet.

**Comment by paishin** [comment]
@LukeTowers, thanks for this, I didn't know about it. Is there a way to rollback as well?

**Comment by LukeTowers** [comment]
@paishin there's currently a PR open to add the functionality to roll back to specific plugin versions:  https://github.com/octobercms/october/pull/4389. Feel free to test it out and add your feedback to the PR.
