### ISSUE TITLE
Bake responsive image support into core with media manager

### ISSUE THREAD

**Issue by nsrosenqvist** [octobercms/october#1419]
Now that OctoberCMS has a media manager it would be good if we could implement responsive images into it since it's a very essential feature these days. Wordpress has always had support for processing and saving uploads in predefined sizes.

**Comment by andreaslof** [comment]
+1!

Even though I understand the idea behind utilising the filesystem for the Mediamanager, it generates some issues when it comes to these things. We're currently developing a website where we've had to circumvent this by developing an external tool that generates our necessary versions of each image that is uploaded.

This **also** gives issues that once a backend user might move around a file in the media library, every post or place that reference that file (which is now a hardcoded path) breaks, and needs to be manually updated. This is very frustrating for the user.

If it would be database-backed, every resized image could be hidden from the user but still accessible by developers, and also have the benefit of the user accessing different sizes for downloads.

**Comment by nsrosenqvist** [comment]
It doesn't necessarily have to be database-backed. If the responsive images are either kept in a separate tree then the filesystem can be used as a simple key value store with folders that get renamed as the original file is moved with the media manager. But even simpler and maybe even better would be to generate them on demand in a cache, then no redundant files would be added to a project and as long as it's a moderately sized website it wouldn't impact performance too bad, since if they've been requested once they'd exist in the cache.

**Comment by hybridvision** [comment]
I think on-demand resizing + caching is a neat way to handle this. I don't find the WordPress method very elegant at all and it is quite wasteful on resources because you rarely need to use *every* image at *every* defined size.

The images could be generated at whatever size is required whenever they are used in the admin (eg. upon inserting into a page or post). This way the cache would already be primed as soon as a change is published. The concepts are quite simple but the UI and architecture of such a system is quite hard to get right.

Regarding the problem of users breaking links when they move media items around, I don't know of a perfect solution for this but maybe some kind of routing mechanism could handle this so that any "hardcoded" URLs will continue to work no matter where the file exists physically.

For example a link to `/media/fileID.jpg` might seamlessly reference `/storage/app/media/cats/fileID.jpg` or even a resized version of that file. If the file was moved somewhere else, the internal reference to the new location could be updated. This might require a database and that's not ideal if it is used for every image reference so some caching would be required too. Another issue would be that changes made by external sources (manual file system changes via SSH / FTP etc) would break the system, so you'd need to stick to always using the media manager for all operations.

To handle deleted media items, there's not much you could do except try to detect or track where that file is currently referenced and warn accordingly.

Some interesting challenges but it's nice to hear ideas on how others might approach them...

**Comment by daftspunk** [comment]
Sounds like a great idea for a plugin!
