### ISSUE TITLE
Can't access all backend menu items

### ISSUE THREAD

**Issue by gregorybleiker** [octobercms/october#1542]
I have installed a lot of plugins that have a backend menu entry, so my menu bar is wider than my screen and some menu items are thus hidden. I can see that there is a little ">", but I can't click on it and nothing happens on hover. The only way for me to get to those items is by resizing the browser window until the menu bar changes to the compact version and even there if the window is too small I can't scroll to the bottom items. Is this a browser issue? (Tested in FF and Chrome).

**Comment by gregorybleiker** [comment]
PS. I'm using a touchscreen laptop...

**Comment by daftspunk** [comment]
You should be able to click/touch and drag the menu across.

**Comment by gregorybleiker** [comment]
OK, works in FF (if you're not a moron like myself), must be a Chrome issue. Pls close

**Comment by axomat** [comment]
I have this problem exactly as described.

I can drag on the screen to the right and to the left.

In Linux FF I cannot horizontal scroll the backend header bar to the right using my touchpad although I can horizontal scroll to the left. It works in Chromium.

**Comment by firemankurt** [comment]
I am having this same issue on my laptop in October Backend.  https://stackoverflow.com/questions/25006721/bootstrap-slider-js-mouse-events-are-not-working-on-touchscreen-devices#
Very annoying because I have to use the touchscreen to slide menus.  They do not move with the mouse I have attached to laptop.

**Comment by Eoler** [comment]
Same problem on Chrome 51 / Windows 10 (convertible with touch screen).

**Comment by dudheit** [comment]
![october-bug](https://cloud.githubusercontent.com/assets/5411942/16334780/e66d9f72-39fa-11e6-8cd2-1f2a40c48b1c.jpg) 

For me it is not only the top menu, but also the scrolling in a list view (generated by Builder plugin) is not working with Firefox 47 and Chrome 51.

**Comment by geoffbeaumont** [comment]
This is still affecting the current version of OctoberCMS as of 14th March 2017.

In addition, the scrollable header isn't at all easy to use on a touch screen, where it tends to trigger the browsers back/forward side swipe at the same time, so that  you have to scroll it in a series of short swipes.

Even for users without a touchscreen, the UI doesn't seem to be remotely intuitive and it's a frequent bug report from clients that some list columns are hidden and they can't get at them. It doesn't help that the list setup button scrolls with the list so is out of sight - users can't even remove columns to fit the list within the available space.

I think this feature needs a completely different implementation.

**Comment by daftspunk** [comment]
I think there was an issue in Media manager that affected these touch-x-keyboard devices (only some) and a way we could replicate it on desktop.

Refs #2490

**Comment by daftspunk** [comment]
@geoffbeaumont Your additions should be included as a new GH issue, preferably with some ideas on a different or improved implementation.

**Comment by LukeTowers** [comment]
The support demand for October is increasing, while the available time the founders have to give remains the same. These issues will be handled in time, however there are ways you can help:

- Submit a pull request that introduces this feature and wait for it to be reviewed
- [Make a financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone

**Comment by ayumihamsaki** [comment]
@LukeTowers I agree with @w20k this issue can be closed, I have two open issues with regards to this issue open right now, see here:

Issue with Tabs: https://github.com/octobercms/october/issues/3856

Issue with Top Menu: https://github.com/octobercms/october/issues/2820

Both those issues should cover this issue, so no need to have this open.
