### ISSUE TITLE
Backend menus needs to be clicked twice

### ISSUE THREAD

**Issue by myst6re** [octobercms/october#1554]
Sometimes when I click on an entry in the top menu the click is ignored.

It seems that when this happen, the "drag" class appears on the body tag.

Is it possible to add a distance of few pixels (like 4 pixels) before start the drag event? Or disable drag functions where it is not necessary?

**Comment by tobias-kuendig** [comment]
+1

I'm experiencing the same problem and it's quite annoying.

It seems like there is already [a threshold of two pixels](https://github.com/octobercms/october/blob/3b4ee3340ea3afd932e6bf5e3e779c4ffaaa0df2/modules/system/assets/ui/js/drag.scroll.js#L144) that has to be passed for the dragging to start but [the `drag` class gets added to the body nonetheless](https://github.com/octobercms/october/blob/3b4ee3340ea3afd932e6bf5e3e779c4ffaaa0df2/modules/system/assets/ui/js/drag.scroll.js#L125). 

Maybe that's the problem here?

**Comment by daftspunk** [comment]
We can look at increasing it to 3 pixels.
