### ISSUE TITLE
compile.php  in the wrong place

### ISSUE THREAD

**Issue by mosid** [octobercms/october#1608]
When running `php artisan optimize`
Compile.php file is created in the `storage\framework` folder
but `bootstrap\autoload.php` checks for the file in the vendor folder.

**Comment by jzumbrun** [comment]
Yep in: https://github.com/octobercms/october/blob/51446f6a27b5680ba062c5afba71f95c6fda7c46/bootstrap/autoload.php#L50

`$compiledPath = __DIR__.'/../vendor/compiled.php';`
needs to be changed to
`$compiledPath = __DIR__.'/../storage/framework/compiled.php';`

**Comment by daftspunk** [comment]
Fixed by #1628

**Comment by ametad** [comment]
How is this being updated? I ask this because I have still the old code in my october project:

bootstrap/autoload.php
```php
...
$compiledPath = __DIR__.'/../vendor/compiled.php';
...
```

This is after (a few) updates of this October project, with
* artisan october:update
* composer update
* update through the backend application

I expected the $compiledPath to be changed to the storage location, but it has not. Am I doing something wrong?

**Comment by daftspunk** [comment]
Waiting on #1744
