### ISSUE TITLE
Cannot use field type "relation" for simpletree relationships

### ISSUE THREAD

**Issue by scottbedard** [octobercms/october#1656]
![simpletreerelation](https://cloud.githubusercontent.com/assets/7980426/11769439/29ad430e-a1a4-11e5-8f55-96d5ea83861e.png)

**Comment by daftspunk** [comment]
*Call to undefined method October\Rain\Database\TreeCollection::listsNested*

I am pretty sure this has been fixed in a newer build, since [this method now exists](https://github.com/octobercms/library/blob/9355153f40183f7871f9f6a2101a1a3425839c98/src/Database/TreeCollection.php#L66). Can you confirm?

**Comment by LukeTowers** [comment]
Closed due to lack of follow up from @scottbedard
