### ISSUE TITLE
Backend User Preferences Bug

### ISSUE THREAD

**Issue by shoguniphicus** [octobercms/october#1740]
When I tried to save backend user preferences, sometimes my preferences get overwritten by some other backend users and when I log into another browser, the backend user preferences didn't persist in my new browser session.

And sometimes it even overwrite other backend users preferences. Looked through the code but didnt find anything suspicious.

However, if I remove line 67 in file /modules/backend/behaviors/UserPreferencesModel.php. Things seems to be in order.

**Comment by daftspunk** [comment]
We need clear step by step instructions on how to replicate the issue.

**Comment by azzzy** [comment]
@shoguniphicus
Do you by any chance have duplicated entries in your backend_user_preferences table?
We have similar problem with multiple entries for the same user_id/namespace/group/item. Somehow instead of update, in some cases a new entry is created for us (we are using SQL Server for persistence).

**Comment by azzzy** [comment]
@daftspunk @shoguniphicus 
It seems the problem is with this method in UserPreferencesModel.php: 

```
public function getSettingsRecord()
    {
        $item = UserPreferences::forUser();
        $record = $item
            ->scopeApplyKeyAndUser($this->model, $this->recordCode, $item->userContext)
            ->remember(1440, $this->getCacheKey())
            ->first();

        return $record ?: null;
    }
```

The cache key doesn't contain the user_id. I would expect that this behaviour differs from the SettingsModel (which may be used for a global setting) and include the user_id as part of the cache key.

**Comment by daftspunk** [comment]
Got it! Thanks

**Comment by shoguniphicus** [comment]
Sweet, thanks!
