### ISSUE TITLE
Component not loading override partial

### ISSUE THREAD

**Issue by wilsonglasser** [octobercms/october#1854]
In my local server, partial override work just fine. (Mac,Apache,PHP 5.6)
In my production server (Ubuntu, Apache, PHP 7), OctoberCMS is not loading my override for a component partial because of case sensitive.

**These examples don't work:**

```
[blogPost]
==
{% component "blogPost" %}
```

blogPost/default.htm don't override 

```
[blogPost blogPostNew]
==
{% component "blogPostNew" %}
```

blogPostNew/default.htm don't override 

**This work:**

```
[blogPost blog_post]
==
{% component "blog_post" %}
```

blog_post/default.htm override just fine!

It's fine to always use [blogPost blog_post], but when using StaticPages I can't change the component to load from another directory.

**Comment by daftspunk** [comment]
Interesting, did you try
```
[blogPost blogPostNew]
==
{% component "blogPostNew" %}
```

With file
```
blogpostnew/default.htm
```

**Comment by wilsonglasser** [comment]
Yes I did, but the only case that worked was using custom name with all lower case:
[blogPost blogpostnew]
==
{% component "blogpostnew" %}

I will try using another PHP version instead of PHP 7.

**Comment by daftspunk** [comment]
Will perform some testing, thanks.

**Comment by petehalverson** [comment]
We've been stung by this on a few occasions...macOS ships with a case insensitive file system which explains the fickle behavior between local and production environments when **overriding** partials.

Without an override [lowercase is used](https://github.com/octobercms/october/blob/2659ae708f0c4cd45b48e4eaaac9e042d1a06649/modules/cms/classes/ComponentBase.php#L98). However, when using an override it has to match the component alias and is case sensitive.

**Comment by daftspunk** [comment]
Not sure what you mean by override?

**Comment by LukeTowers** [comment]
@daftspunk I'm assuming that he means without specifying an alias for the component (just using the default alias), the lowercase path is used. This is a valid bug though, on case-sensitive file systems the filesystem path to the overriding partial must match the case of the alias exactly.

**Comment by petehalverson** [comment]
Thanks @LukeTowers, that's it.

**Comment by daftspunk** [comment]
Damn, how should we resolve this inconsistency?

**Comment by LukeTowers** [comment]
We could either very boldly emphasize this fact in the documentation that case sensitive file systems are likely to confuse developers / users, or integrate a variation of https://stackoverflow.com/questions/14192515/php-skip-case-sensitivity-in-file-extension into a helper class that we can then use to guestimate which file is actually desired in a case-sensitive environment.

**Comment by daftspunk** [comment]
Ok, we have `File::existsInsensitive` for this already, however it comes at a performance cost (unknown) because it lists the entire directory contents to locate the file. 

We can tell Halycon to use this as a fallback when an file doesn't exist. Here are our options to move forward:

1. Magically rewrite paths that have a sensitivity mismatch (performance hit, perhaps oblivious to developer)
1. Throw an exception with details (Case sensitivity mismatch! X => Y)
1. Combine (1) and (2), except write to trace log instead of throw exception

**Comment by petehalverson** [comment]
An exception with details would be all we'd really need.

@daftspunk I was going to suggest a fix like what you just committed - 87f8f8f

**Comment by LukeTowers** [comment]
I think we should do some work on #2351 to reduce this happening to those developers and advanced users that utilize the backend interface to create these override partials, and make it more clear in the documentation that on case-sensitive file systems this problem is likely to occur.

I'm not really a huge fan of coding in automagically looking for incorrectly cased versions of the path since it's something that requires so little effort on the side of the developer to fix (it really only requires knowledge that it can happen).

I think probably the best way forward is to
1. Prevent users from shooting themselves in the foot by implementing the "Fork" button proposed in #2351
2. Educate developers that don't use the backend for development by emphasizing the pitfalls of case-sensitive file systems in this particular use case.

**Comment by daftspunk** [comment]
Looks like this commit https://github.com/octobercms/library/commit/8f0cf0cd58d8ba323c3f0f881839c4022772bfcf still doesn't fix the issue, although it's an improvement. It addresses file names only...

I think simply the hard rule is this. **All directories should be lower case**. If you stick to this rule then you'll be fine. We just need a way to deal with the fact that October previously required uppercase folders in some instances...

**Comment by LukeTowers** [comment]
Good solution @daftspunk 👍
