### ISSUE TITLE
BackendAuth::getUser() returns null on logged in user

### ISSUE THREAD

**Issue by mplodowski** [octobercms/october#1867]
`BackendAuth::getUser()` returns `null` in Plugin.php `boot()` method, although user is logged in.

Is there any other way to get logged in user in custom plugin `boot()` method?

**Comment by daftspunk** [comment]
I think the Session is generally considered to be unavailable inside Service Provider/Plugin register and boot methods. This is because it fires very early in the life cycle.

Maybe consider using `App::before(function() { /* ... */ });` to wrap the logic, the session should be available inside this event.

**Comment by mplodowski** [comment]
Yeah, that works.

Thank you.
