### ISSUE TITLE
Display custom message for status code in error page

### ISSUE THREAD

**Issue by ahlechandre** [octobercms/october#1935]
With `debug` in mode `false` the system renders `\error` page by default.

The problem is cause I can't show a custom message for the specific error. 

For example, this is the content of my error page:

```
url = '/error'
==
ops, error!
```

In my middleware, if using `App::abort(404)` or `App::abort(500)` the message will always be the same: `ops, error!`

I wish something like this was possible:

``` twig
url = '/error'
==

{% if statusCode == 500 %}
    server error!

{% else if statusCode == 404 %}
   page not found!
{% endif %}
```

Or, pages for each status code: `\error\404` and `\error\500`. 

How i can filter the status code and show a custom message in `\error` page?

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.

Also, I believe this has been implemented for a while with the support for the /404 page. https://octobercms.com/docs/cms/pages#404-page
