### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by trsh** [octobercms/october#1954]
My first steps with October CMS and I got and exception about not correctly inited Exception o_O

Symfony\Component\Debug\Exception\FatalErrorException Object ( [message:protected] => Uncaught TypeError: Argument 1 passed to October\Rain\Foundation\Exception\Handler::report() must be an instance of Exception, instance of Error given, called in /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php on line 73 and defined in /var/www/html/vendor/october/rain/src/Foundation/Exception/Handler.php:42 Stack trace: #0 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(73): October\Rain\Foundation\Exception\Handler->report(Object(Error)) #1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error)) #2 {main} thrown [string:Exception:private] => [code:protected] => 1 [file:protected] => /var/www/html/vendor/october/rain/src/Foundation/Exception/Handler.php [line:protected] => 42 [trace:Exception:private] => Array ( ) [previous:Exception:private] => [severity:protected] => 0 )

**Comment by daftspunk** [comment]
Please read the contribution guidelines before submitting to GitHub Issues. Thanks

**Comment by dshoreman** [comment]
@trsh That error is because you're running the older version of October with PHP 7. You need to enable `edgeUpdates` or clone from develop to get the latest version which is updated to support PHP 7.

Failing that, comment out the call to `report()` that the stack trace tells you about in `vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php`
