### ISSUE TITLE
Will this project live?

### ISSUE THREAD

**Issue by trsh** [octobercms/october#1974]
https://github.com/octobercms/october/graphs/contributors

**Comment by daftspunk** [comment]
Please explain.

**Comment by trsh** [comment]
Contributors counts is doping. Or I'm reading the chart wrong?

**Comment by trsh** [comment]
I also can find a roadmap.

**Comment by daftspunk** [comment]
No, the project is dead. Go away.

**Comment by trsh** [comment]
Very unprofessional answer :/

**Comment by daftspunk** [comment]
I assume your question is a joke. Perhaps this gives you the serious answer.

**Comment by trsh** [comment]
But seriously. I want to start a new project. And I like OctoberCMS a lot. But I want be sure this a long term relationship :D. So can you give me some insights. How is the project progressing? Why is the contributor count falling? And is there any road-map - future plans, perspectives, etc.?

**Comment by daftspunk** [comment]
In all seriousness, the project is the absolute opposite of dead; it has never been more alive! We work incredibly hard on this project and it continues to thrive. If operations appear quiet, this is the calm before the storm: October v1.0 is coming.

The GitHub data is not accurate because it doesn't include anything since February. It only includes the `master` branch. We are working towards October v1.0 (stable) which is currently in `develop` branch and will be launched any day now.

[Look at the changelog](http://octobercms.com/changelog) for a more accurate representation of health. There is a constant stream of rolling updates.

[Look at this usage chart](http://trends.builtwith.com/cms/October-CMS) for an idea of how many people use the platform. Although this also shows inaccurate data sometimes.

Good luck with your project, I know October is the right fit for experienced developers. We are in this game for the long term. We will not stop until we have saved the world from WordPress.

:v:

**Comment by trsh** [comment]
Ouh. Thanks for this detailed explanation. You the MAN! And sorry for taking your time.

While waiting for your answer, I was playing with October and it looks better and better for me.

Registered also couple of bugs.

WordPress will not die for people who only want to install and create content, and who always go for the most Famous thing. For developers, Sure. W.P. was dead for ME first time after trying it :D. I was for  along time on Django-CMS, but as my country lacks Python specialists, so we are going back for PHP and searching for a good system.

Small advice. Don't say: "YEAH DUDE, GET LOST with your stupid question". Because actually I'm not some noob why is struggling to make own homage. I'm analyzing CMS for serious project in my company, our team could also contribute in bugfixes. I'm 11 years in to DEV development. OctoberCMS just lacks a roadmap and upcoming features list.

Keep going!

**Comment by kalfheim** [comment]
DEVELOPMENT development?

**Comment by filipac** [comment]
> We will not stop until we have saved the world from WordPress.

Nice answer, dude!

**Comment by trsh** [comment]
kalfheim development development development! :P

**Comment by nacr-dev** [comment]
👍
