### ISSUE TITLE
Problem with listExtendQuery and NestedTree

### ISSUE THREAD

**Issue by odlex** [octobercms/october#1983]
I am Unable to use listExtendQuery when you set showTree: true for the behavior ListController

My model use: `use \October\Rain\Database\Traits\NestedTree;`
My config_list.yml contain: `showTree: true`
My controller have: 

``` php
   public function listExtendQuery($query, $definition)
    {
        if($this->current_menu_id) {
            $query->where('menu_id', 'like',$this->current_menu_id);
        }
    }
```

in the widget Lists l.494:

``` php
protected function getRecords()
    {
        if ($this->showTree) {
            $records = $this->model->getAllRoot();
        }
        else {
            $model = $this->prepareModel();
            $records = ($this->showPagination)
                ? $model->paginate($this->recordsPerPage, $this->currentPageNumber)
                : $model->get();
        }
        return $this->records = $records;
    }
```

> the list widget don't use **prepareModel** who fire the events

Thanks by advance
Alexandre

**Comment by kkoenen93** [comment]
Any update yet?
Thanks in advance!

**Comment by daftspunk** [comment]
Not yet @kkoenen93

**Comment by LukeTowers** [comment]
The support demand for October is increasing, while the available time the founders have to give remains the same. These issues will be handled in time, however there are ways you can help:

- Submit a pull request that introduces this feature and wait for it to be reviewed
- [Make a financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone

Closing as it has been over a month since any activity on this occurred.
