### ISSUE TITLE
MediaLibraryItem cannot differentiate between folder and document

### ISSUE THREAD

**Issue by lackneets** [octobercms/october#2016]
I think here: [MediaLibraryItem.php#L111](https://github.com/octobercms/october/blob/9dc1b4d836c8147f7fc0b3f752efe10d70a491f2/modules/cms/classes/MediaLibraryItem.php#L111) should be `TYPE_FOLDER`

**Comment by daftspunk** [comment]
As per the contribution guidelines, please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

**Comment by lackneets** [comment]
For example
```php
$files = MediaLibrary::instance()->listFolderContents('/carousel', 'title', MediaLibraryItem::FILE_TYPE_IMAGE);

foreach ($files as $file) {
    echo $file->publicUrl;
}
```

I got:

```
storage/app/media/carousel/01.jpg
storage/app/media/carousel/02.jpg
...
storage/app/media/carousel/min
```

where ``min`` is a folder

**Comment by daftspunk** [comment]
Need to confirm if this is intentional or not, as files can exist without extensions, it does not always assume they are folders.

**Comment by alekseybobkov** [comment]
Folders are accounted in the line [MediaLibraryItem.php#L99](https://github.com/octobercms/october/blob/9dc1b4d836c8147f7fc0b3f752efe10d70a491f2/modules/cms/classes/MediaLibraryItem.php#L99). `MediaLibrary::listFolderContents()` intentionally adds folders to the result, because in the Media Manager user interface we want to see folders even when a file type filter is applied. I added a new parameter allowing to suppress folders:

```php
public function listFolderContents($folder = '/', $sortBy = 'title', $filter = null, $ignoreFolders = false)
```
Your example, updated:
```php
$files = MediaLibrary::instance()->listFolderContents('/carousel', 'title', MediaLibraryItem::FILE_TYPE_IMAGE, true);

```
