### ISSUE TITLE
Checkbox fields should align bottom, not top

### ISSUE THREAD

**Issue by Flynsarmy** [octobercms/october#2045]
Checkbox fields look really strange when left/right span'd with a text (or any other type) of field. Shouldn't they be vertically aligned with the field, not the label?

![screen shot 2016-05-25 at 8 51 22 am](https://cloud.githubusercontent.com/assets/334808/15522474/02921c76-2256-11e6-88de-d55209ec4397.png)

**Comment by daftspunk** [comment]
This is normal.

We could introduce a CSS class that addresses this, there is `checkbox-align` iirc which does something similar for inputs (adds an indent so it lines up with the checkbox -- see Blog > Post > Published at)

Although you should probably handle this in your own plugin's CSS because it is not possible to have a one size fits all. In your example, if **Levels** used `commentAbove` the alignment would be different again.
