### ISSUE TITLE
BadMethodCallException: Method accessible does not exist.

### ISSUE THREAD

**Issue by mplodowski** [octobercms/october#2065]
I followed documentation and created test for my plugin, but after run it I get this error:

BadMethodCallException: Method accessible does not exist.

I tested with build 318 (master branch) and 340 (bleed updates enabled).

I downloaded Translate Plugin and run its tests and there was the same result.

In stack trace it points to:

/tests/PluginTestCase.php:100
/tests/PluginTestCase.php:65

The error is thrown when: `Artisan::call('october:up');` is called.

**Comment by gabsource** [comment]
Could you please use the template found at the link below to explain how to reproduce this issue ? I have installed the translate plugin via the backend interface, then ran the `phpunit.xml` found in it and it just launched fine. A test is failing due to a string mismatch but PHPUnit is doing his job. I'm using the `develop` branch version of OctoberCMS which matches build 341.

https://github.com/octobercms/october/blob/develop/ISSUE_TEMPLATE.md

**Comment by mplodowski** [comment]
**Expected behavior**

No errors after running phpunit tests.

**Actual behavior**

Most of the tests runs with error.

    BadMethodCallException: Method accessible does not exist.

**Reproduce steps**

1. Install latest October build with composer dev-develop.
2. Configure DB and run `php artisan october:up`
3. Update to the newest version from backend.
4. Run phpunit in project root.
5. Most of the tests runs with errors, like I receive in my plugin Tests.

Environment: Windows, Latest Homestead box, PHP7.

Probably something to do with my configuration, but I cannot resolve this.

**October build**

341

Stack Trace example for failed test:

    87) HalcyonModelTest::testFindAll
    BadMethodCallException: Method accessible does not exist.

    /home/vagrant/Code/oc-stable/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php:59
    /home/vagrant/.composer/vendor/illuminate/support/helpers.php:426
    /home/vagrant/Code/oc-stable/vendor/laravel/framework/src/Illuminate/Support/Arr.php:327
    /home/vagrant/.composer/vendor/illuminate/support/helpers.php:229
    /home/vagrant/Code/oc-stable/vendor/october/rain/src/Support/Collection.php:19
    /home/vagrant/Code/oc-stable/vendor/october/rain/tests/Halcyon/ModelTest.php:28

**Comment by gabsource** [comment]
Is your `/home/vagrant/.composer/vendor/illuminate/support/helpers.php` a correct version of Laravel for OctoberCMS (5.1 LTS). I don't get the same lines in `helper.php` (see the stacktrace below). The only difference I can see is that our Laravel `helpers.php` is loaded from `/.composer` instead of project path.

![image](https://cloud.githubusercontent.com/assets/1851314/15633058/20a6e66e-25a4-11e6-9b5f-698447031eee.png)

**Comment by mplodowski** [comment]
Thanks for helping solving this out.

I had `laravel/envoy` and `laravel/installer` in global composer for Laravel 5.2 and that was the issue.

After removing those packages, it works fine now.

Thanks again.

**Comment by shengbinxu** [comment]
@gabsource  thank you vevy much, you sloved my question。
In my php.ini,have:
`auto_prepend_file = /home/xushengbin/.composer/vendor/autoload.php`
It will first load file ` ~/.composer/vendor/illuminate/support/helpers.php`, and it`s laravel version is 5.4。 
so after remove this php.ini config, `php artisan october:up`  run ok。
