### ISSUE TITLE
Cannot remove plugin does not exits

### ISSUE THREAD

**Issue by mlukaszewski** [octobercms/october#208]
I trying to remove Rablab.Email plugin (aka Email Templates).
http://octobercms.com/plugin/rablab-email
This plugin has been rolled back from your official plugin list.

I removed them from my instance by plugin:remove - with success.
But every time I try to update the instance (project ID:233) this plugin back to system.

**Comment by daftspunk** [comment]
Projects now support the ability to remove Plugins. So they can be removed in both instances.

**Comment by mlukaszewski** [comment]
I have to reopen this bug. Still problems.

This is my plugin list on project page

![image](https://cloud.githubusercontent.com/assets/4126151/9191425/7c41fbe6-4001-11e5-92a5-2e01a4c135c9.png)

This is my plugin listed on website backend

![image](https://cloud.githubusercontent.com/assets/4126151/9191431/8e5e22c8-4001-11e5-9f7e-c9d376e66ef6.png)

And this is what happens if I check available updates

![image](https://cloud.githubusercontent.com/assets/4126151/9191443/ab3627c4-4001-11e5-8698-04d219a3dc23.png)

The plugin has been remove via console (plugin:remove etc) and it doesn't exists in folders structure.

The config setting (pluginsDisable) do nothing.

And here is, the hero of the day
http://octobercms.com/plugin/rablab-email

Please, help, I'm going to blow :/

**Comment by daftspunk** [comment]
We have removed it for you manually. The owner for some reason made the price $99999 and there is no ability to remove paid plugins (yet) because it would be like throwing away your money. We will add this along with some other features we have planned in the future.

**Comment by mlukaszewski** [comment]
@daftspunk 
I will be very grateful to you

**Comment by abass** [comment]
@daftspunk I have been encountering this exact same thing as well for my personal site (abass.co) and it has been such a headache. Even more-so because some other apps are dependent on the mail plugin, and it seems to keep grabbing Octo Mail even though it doesn't even exist breaking my site.

Could you possible manually remove this paid plugin (that no longer exists) from my account as well? Would save me so many headaches!

![IMG](https://d17oy1vhnax1f7.cloudfront.net/items/3i2w383f1q0e1Q3T3A2U/Image%202016-09-05%20at%206.48.21%20PM.png?v=d6ddea20)

**Comment by daftspunk** [comment]
@abass Send us an email to hello ata octobercms dota com with the project name and we can remove it for you.
