### ISSUE TITLE
timesince not working

### ISSUE THREAD

**Issue by sercanvirlan** [octobercms/october#213]
![ekran resmi 2014-05-26 18 29 28](https://cloud.githubusercontent.com/assets/533209/3083893/8f00ad0e-e4ea-11e3-9812-3e6429fa1ec0.png)

**Comment by SaifurRahmanMohsin** [comment]
This still needs a datetime in order to work. I’m using the datepicker in time mode and my model uses `$table->time(‘closes_at')->nullable();`. But I’m unable to display this in my list controller as a `type: date` field. It throws me this error and adding `protected $dates = [‘closes_at’];` gives me a `Unexpected data found. Unexpected data found. Data missing` error
