### ISSUE TITLE
Cannot access third party blog, forum, wiki or ticketing system

### ISSUE THREAD

**Issue by josephgodwinkimani** [octobercms/october#2135]
I wanted to install third party ticketing system, since no free option is offered by Octobercms, using Softaculous but the system is inaccessible through the url:`http://mydomain/helpdesk`. I get **403 error** so I tried other systems such as blogs, forums, wiki but got the same problem. 

I further tried uploading the system files for respective systems to `public_html/systemfolder` etc but same problem. Note this has never happened to us before. Why is this happening?

**Comment by Harrison-B** [comment]
This is most likely due to OctoberCMS's  `.htaaccess` file (if you are on Apache)

I'm no expert, but perhaps someone else could help specify how to add an exception. I put all my third party software on sub-domains, and disable (by renaming) the `.htaaccess` file during the install and re-enable it after everything is working.

**Comment by daftspunk** [comment]
As above, you will need to allow this folder through the .htaccess file

The GitHub issue list is for reporting bugs in the OctoberCMS code base specifically. Please try the following support avenues for getting support with using October:

- [Stack Overflow](http://stackoverflow.com/questions/tagged/octobercms)
- [OctoberCMS Forum](https://octobercms.com/forum)
