### ISSUE TITLE
Include composer.json in installation

### ISSUE THREAD

**Issue by pedzed** [octobercms/october#2255]
##### Expected behavior
When you run the initial installation, the `composer.json` file should be included in the root of the project.

1. Download the installer
1. Install OctoberCMS

The `composer.json` file _should_ be available.

1. Create a repo and push to GitHub for example
1. Clone the repo
1. Run `composer install`

##### Actual behavior
The `composer.json` file is missing.

**Comment by daftspunk** [comment]
If you plan on using composer, you should really follow the [composer installation process found in the documentation](http://octobercms.com/docs/console/commands#console-install-composer). The GUI installer is a different workflow than using composer, since the file isn't ever needed, it isn't included for simplicity. You can always add the composer file yourself manually.
