### ISSUE TITLE
Installation on 1and1 doesn't work out (1&1)

### ISSUE THREAD

**Issue by GabrielGil** [octobercms/october#227]
Since it's not possible to use Laravel with any of the 1and1 shared hosts due the memory per PHP process limitation and the fact that they don't have CLI installed, I know that it's not possible to install it this way.

However, the phar installer works good on 1and1 but you will miss the artisan commands (because of the missing CLI).

The thing is that I'm trying to use the October installer on 1and1 but when I hit install.php on my browser, it doesn't shows anything. Neither an error. And it's not because of the PHP version since I am using PHP5.5 there.

So what can be happening here? How can i fix it?

Cheers!

**Comment by rbianco3** [comment]
Not sure if anyone knows or has tried but I was able to successfully install October on 1and1 shared hosting. It's just a bare site with the theme right now at http://subox.one but I can't wait to start playing with it and see if I can get everything working that I need.

Impressive CMS. The biggest challenge was the database connection because 1and1 doesn't give root for the database they much slice up the instances as multi-tenant setups but I got it working! Only needed to edit one file in the installation process.

**Comment by rbianco3** [comment]
I'm willing to fix the installer so that it will work on **1and1** ( 1&1 for search ) **shared hosting with mySQL** if you'd like me to and can help you with updating your installation documentation. The workaround is pretty simple and a good solution would be to add another field to the mySQL connection form for the **unix_socket** and leave it blank by default. If the end-user doesn't put anything in there than ignore it otherwise concatenate the dsn using the socket setting which is what allows the mySQL connection to work. 

You mentioned **sqllite** not being installed on 1and1 but I see it when running phpinfo, haven't tried actually making a connection yet though.

If you have any questions don't hesitate to ask me.  You can hit me using the domain I listed in the prior post and use my first name 'rich' with it.

**Comment by daftspunk** [comment]
Please create a document, email it to us and we will publish it. (Email address is in the footer of the website, look for the email icon)

**Comment by hot-ham-water** [comment]
I know this is a bit out of date, but I was just able to install October on my 1and1 shared server. I had to call their support and have them change every file and folder in the install directory (I put it into a subdirectory on my server) to 755. For some reason, I wasn't able to do it with CyberDuck (it kept crashing each time I would try it). I then had to update my php to 7.0. And, I had to access install.php from my main URL/subdirectory/install.php rather than the 1and1 technical subdomain. But it all seems to be working fine now!
