### ISSUE TITLE
Protect from Partial Loop

### ISSUE THREAD

**Issue by tsioukas** [octobercms/october#2289]
This is not exactly bug, maybe it’s a feature request. This caused by bad web architecture from the web developer.

- Create a "Page" and two partials "Partial_1" & "Partial_2". 
- Add to "Page" the "Partial_1" twig
- Add to "Partial_1" the "Partial_2" twig
- If you add the "Partial_1" twig inside "Partial_2" it will create a loop

After PHP execution timeout, it will show a page doesn't response message.

Maybe it’s better to add a check to protect from this bad design by showing a message of the error.

Thanks.

**Comment by daftspunk** [comment]
I'm not sure we want to be introducing code for these cases. This is really programming 101, the same loop would occur using PHP includes or any other system. There is some responsibility for the developer to understand this, rather than implement code that affects the majority who do.

Tagged as conceptual feature request in case we should ever need to revisit.
