### ISSUE TITLE
GET requests with AJAX framework

### ISSUE THREAD

**Issue by Herlevsen** [octobercms/october#2321]
##### Expected behavior
When submitting a form with the ajax framework, if the form method is set to GET i expect a GET request to be sent.

##### Actual behavior
Regardless of the form method being GET or POST, the request is sent as POST.

##### Reproduce steps
From the documentation, but i added the method attribute:
`<form method="GET" data-request="onCalculate" data-request-update="calcresult: '#result'">
    ...
</form>`

##### October build
Any up to 359

##### Extra notes
Per the HTTP protocol GET requests are to be used for data retrieval (put simply). POST requests are used when the request has side-effects, for example a database or file is modified.

An important point is, that GET requests can be cached, but POST requests can not. Therefore, whenever we are using the ajax framework, currently the browser can not cache the response.

Discussed with @daftspunk on the Slack channel, and was told that October used an HTTP header, to route the ajax request properly. For GET requests, this could be done via a query parameter.

Hope we can discuss this here, and then i might be able to help implementing it.

**Comment by daftspunk** [comment]
Not sure why this is needed.

**Comment by Herlevsen** [comment]
It's needed because post requests can not be cached by a browser.

Less importantly we should also adhere to the HTTP protocol.

**Comment by tschallacka** [comment]
You are using the AJAX api to submit the form and retrieve what the servers hould do with it.

Remove the ajax api and set up a route to intercept your post request.

**Comment by Herlevsen** [comment]
@tschallacka You are missing the point. AJAX has nothing to do with the HTTP method in use. GET and POST have very specific use cases in the HTTP protocol, and GET should be used for data retrieval, AJAX or not.

**Comment by tschallacka** [comment]
It has ALL to do with what you are doing.

<form method="GET" data-request="onCalculate" data-request-update="calcresult: '#result'"> ... </form>

This, gets intercepted by the october base libraries. there is never a get request because the event is called and falsei s returned so there is never an actual post/get/put/delete request sent.

What happens is that when onsubmit is called on the form, the october api recognises the data-request tag, collects all form field values, wraps it up in a `$.request($form.data('request'))`  and then returns false so the submit event is cancelled, then performs whatever it has to perform after the AJAX request is completed.

Like I said, remove the ajax api handlers, and you can use your get request.

**Comment by Herlevsen** [comment]
@tschallacka You are still missing the point. I am aware how to make an ordinary GET request with a form. The example is from the documentation. AJAX requests can also be made post/get/put/delete methods, but Octobers AJAX framework, always makes a post request. What i want is for the AJAX framework to recognize the HTTP method from the form, and not make an assumption, that we always want to make a POST request.

**Comment by tschallacka** [comment]
You are using a specific framework to get data asynchronically by a scripting language run by a browser after certain interactions have taken place.

This makes it a moot point if the data was sent by post or get, the browser will not cache it like it would do with an html native form get submit.

You will always need to repeat the get request or post request the moment javascript loads to replay the same circumstances.

Post, or get is really a moot point, since its handled by a scripting language which will not be replayed by the browser on a history browsing event, unless you do a specific history.pushstate in supporting browsers.

Use 'vanilla' html get form submit, use jQuery.ajax with get method or use pushstates with october ajax api
Otherwise you're using a tool for purposes for which it's not meant.

Outlook voor Android<https://aka.ms/ghei36> downloaden



On Mon, Aug 22, 2016 at 6:10 PM +0200, "Jens Ahlsten Herlevsen" <notifications@github.com<mailto:notifications@github.com>> wrote:


@tschallacka<https://github.com/tschallacka> You are still missing the point. I am aware how to make an ordinary GET request with a form. The example is from the documentation. AJAX requests can also be made post/get/put/delete methods, but Octobers AJAX framework, always makes a post request. What i want is for the AJAX framework to recognize the HTTP method from the form, and not make an assumption, that we always want to make a POST request.

-

**Comment by daftspunk** [comment]
Guys, this discussion is madness. We use AJAX to POST and we use the URL for GET requests. Opening up AJAX handlers to GET requests would open a can of worms and create complete chaos. Regardless of the spec, this is October's implementation. To have a handler available via get is simple

```
if ($get = get('handler')) {
    return $this->$get();
}
```

http://localhost/?handler=onDoSomething

This is not advised for obvious reasons. I think what you might be looking for is an API, RESTful or otherwise. There are many ways to achieve that, and there are plugins that do it already. However it is completely out of scope for October's core at the moment.
