### ISSUE TITLE
Backend\Classes\FormField->resolveModelAttribute() does not support associative array attributes

### ISSUE THREAD

**Issue by LukeTowers** [octobercms/october#2354]
### Expected behavior
Fields that require getting dynamic options (checklist, radio, dropdown) should support being a part of an attribute's associative array just like more simple fields do (i.e. `type: text`).

### Actual behavior
`Backend\Classes\FormField->resolveModelAttribute()` (called by `Backend\Widgets\Form->getOptionsFromModel()` for fields that require dynamic options (`type: dropdown | radio | checklist`)) does not implement type checking with its iterative 'drill down' method of resolving the specified attribute. As a result of that, `Trying to get property of non-object` is thrown when the current implementation attempts to drill down through an attribute that is an associative array.

### Reproduce steps
Create a model that has a JSON attribute that is capable of storing an associative array of data. 

**MIGRATION:**
```
$table->json('options')->nullable();
```

**MODEL:**
```php
protected $jsonable = ['options'];

public function getLevel2Options($keyValue)
{
    return [
        'option1' => 'Option 1',
        'option2' => 'Option 2',
    ];
}
```

**FIELD CONFIG:**
```yaml
options[level1][level2]
    label: 'Test field'
    type: dropdown
```
Now attempt to load the page containing that form, October will throw an exception that you're `Trying to get property of non-object` in `\Backend\Classes\FormField->resolveModelAttribute()`. This occurs because in order to resolve the model attribute, the code is attempting to 'drill down' through multiple levels of model attributes when the field name is an array.

However, because this array represents an associative array stored within a JSONable attribute, and not a series of relations, this code fails on its assumption that each sub level of the attributes that it goes through will contain a Model class, and attempts to access the nonexistent property of the associative array instead of attempting to access the child element of that array.

##### October build
dev-develop (Latest commit as of this issue)

**Comment by daftspunk** [comment]
This is a complex case. Please submit a Pull Request to the [test plugin for investigation](https://github.com/daftspunk/oc-test-plugin) that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it *using the test plugin*.

**Comment by daftspunk** [comment]
Upon further investigation, it is determined that this is by design. In the example, level1 is not a model, it is an array therefore it cannot be resolved for sourcing the options. It would be dirty logic to source the options from the root model, so a explicit reference is needed.

Improved the exception handling, a more specific error message is now shown when trying to resolve a model from an array source:

`
The attribute 'options[level1][level2]' does not resolve to a valid model. Try specifying the options method for model class Acme\Plugin\Models\MyModel explicitly.
`

Note in the example below, the `options` definition refers explicitly to the method used for sourcing options.

**MODEL:**
```php
protected $jsonable = ['options'];

public function getLevel2Options($keyValue)
{
    return [
        'option1' => 'Option 1',
        'option2' => 'Option 2',
    ];
}
```

**FIELD CONFIG:**
```yaml
options[level1][level2]:
    label: 'Test field'
    type: dropdown
    options: getLevel2Options
```
