### ISSUE TITLE
Use query strings to bust asset combiner internal cache

### ISSUE THREAD

**Issue by frthjf** [octobercms/october#2393]
##### Expected behavior

The assets filter `theme` should combines assets with query strings (e.g. ignore query parameters):

```
<script src="{{ [
    'assets/js/script.js?v=5',
    'assets/js/another_script.js?another=query_string',
    ]|theme }}"></script>
```
##### Actual behavior

Scripts with query parameters in the URL are not included.
##### Reproduce steps

Add a query string to an asset combiner statement
##### October build

365

**Comment by LukeTowers** [comment]
Why do you have scripts with query strings in their path being run through the combiner anyways? Not saying this shouldn't be changed, just wondering your use case.

**Comment by dudheit** [comment]
@LukeTowers I don't. The thing is that I was porting an existing theme to October via copy & paste, which happend to have a query string in the javascript assets. I spent hours to debug why the script wasn't working, just to eventually recognize that the script was simply not included due to the query strings. I removed the query strings and it worked again, so I thought it might be a good thing for October to prevent developers falling in this trap by simply removing any query strings (which are usually used when the assets files are generated by PHP I think)

**Comment by LukeTowers** [comment]
@dudheit Yeah, query strings are usually included to prevent browsers from caching the assets, which wouldn't have anything to do with the asset combiner. I believe passing an array to the `theme` filter expects the values to be file system paths not URLs though, which is why it would fail on query strings. At the very least, some exception handling could be added to make this error apparent to anyone copy pasting in the future though.

**Comment by dudheit** [comment]
Yes, should be an easy fix. At least an error message would be good if developers accidentally include query strings.

**Comment by daftspunk** [comment]
Assets passed to combiner are combined to a single request and therefore do not support query strings on individual resources.

**Comment by dudheit** [comment]
I see, it would be still helpful though to get an error/warning message if one includes a query string.

**Comment by daftspunk** [comment]
While I agree it would be helpful to point it out, the mistake is akin to a paper cut; an implied expectation. 

> Warning: Paper from this printer can cut you 😄 

When two go in and one comes out, it is obvious that the query string is not a possibility. It is not a good idea to introduce code that impacts the majority who understand this.

**Comment by dudheit** [comment]
Ok, thanks for considering this anyway.

**Comment by daftspunk** [comment]
It does raise an interesting point though, the whole `?12345` is a common HTML hack to bust the cache. So it seems natural that you would try this. Perhaps in future we could emulate it to bust the internal cache of the combiner. This is a far more interesting use of the idea.
