### ISSUE TITLE
Rollback Modules / System to specific Build - AND - Bind Plugin Version to Build

### ISSUE THREAD

**Issue by sewagolubkow** [octobercms/october#2413]
### Expected behavior
I've updated October CMS, and checked if all the plugins are working correctly.
Some didn't, and I've tried to set the installation back to the previous state.

### Actual behavior
There is no way to roll back an October update to some old build.
> My plugin (https://octobercms.com/plugin/sewa-tileable) is using the October CMS modules.
v1.0.2 only works with an old build (I don't even know which one),
v1.0.3 only works with the lates build...  

> Rolling back some plugins can be done, pretty nice and easy.
But there is no way to define which October build the plugin was developed for.

### Another real world problem example
I have a website with a specific October build, and custom plugins for this build.
After a few years, I would like to install another plugin, but I don't know what version of this plugin I need. Furthermore, there is no way to roll the plugin back and forth.

This is really my most important issue for the marketplace, since I want to be a 100% sure my web project will be running in the future. When someone accidently presses "Update", it now can cost the company a lot of time and money!

### Fast and cheap solution
Tag the builds in GitHub. This way, at least we could do a GIT checkout to this specific build...
OR, someone could put up a list of "commit hash -> build number" connections for all previous builds.
I would then make a backend plugin, where the user can:
- Roll back and forth between plugin versions
- Checkout with GIT into different build states, with a user interface

```
Thanks for all your effort.
I fell in love with laravel, and I love October even more.
The marketplace is great! Can only say that a few times more...
```

**Comment by daftspunk** [comment]
The issues you are having are more than likely caused by using October before the stable release along with plugins that are no longer maintained. This proposed solution described above has been considered many times before so I will try my best to explain.

October's core uses an uncommon and simplistic approach to versioning. Right from the start, we had a clear vision and expectation of how the platform should be written and function. This allows us to [clearly state that the core is stable](http://octobercms.com/blog/post/october-stable-release) and from this point the platform is not allowed to cause significant breaking changes, ever. It is also the reason it took several years to build October, we had to get it right the first time.

This is a concept we refer to internally as "neo version" (one version). Basically there is only one October: the latest stable build.

The allows for some significant advantages, mostly it makes October an incredibly reliable platform for business. It means breaking changes are very rare and always minor (easy to fix). You can be confident that a site you build today will still be fresh and relevant for years to come.

In some ways it puts versioning in reverse gear. So if you are not using the latest core build intentionally, you are effectively running a "snapshot" fork of October, therefore it is up to you to manage the code base yourself.

The core is very light and minimal, this is entirely on purpose. A fresh install of October doesn't really do much. Almost all the functionality comes from plugins, which do support semantic versioning. You can "freeze" a plugin at a particular version and it should work with any future core build. However you cannot update a plugin without updating the core, effectively all the boats must rise with the water. It does mean that all authors must maintain there plugins to work with the latest core code.

If your site has come from the pre-stable build, then there may have been breaking changes in the core that require the plugins to be maintained. It is possible this is what has happened in your case, but it will be very uncommon moving forward.

So this isn't an issue with October, the problem is with the plugins, perhaps they are no longer maintained? If a plugin is failing to work in the latest build:

- Contact the author to find out why, and if they can fix it
- If there is no result, contact us and we will hide the plugin from the marketplace
- You are welcome to fork a plugin if it has been abandoned (#2352)

At this point in time, we do not plan to introduce the complexity that comes with maintaining old core builds with plugin versions. This is because the plugins are the basis for everything and they do support versioning. The core is the solid foundation that we use to build, that should never break (post July 2016). A bit like PHP itself.

**Comment by sewagolubkow** [comment]
Thank you alot for your detailed reply.  

You've guessed correctly, I've updated from a pre-release build.
Also, there were little changes I needed to make to get it running again.  

I want to encourage you to stick with this approach. I've read a little about it some time ago, when choosing my next framework. In fact, that is one of the main issues why I've chosen October over Sonata. The different plugin versions are just killing the developer, and most combinations never work (in Sonate). New, wanted features are breaking other plugins constantly (in Sonata).
So I was a bit shocked to see an update problem.

This approach may demand a bit more commitment from the developer, but the benefits are enourmous. I would recommend October to every Web Developer, and my commitment to this platform is strong.

### Still
Couln't you put up a list which links the October build number to a commit?
It's not much effort, and we would have the freedom of installing old builds...
On the other hand, knowing this approach it's not that important.

**Comment by daftspunk** [comment]
This has been considered also, tagging builds would [generate a lot of spam](http://octobercms.com/changelog) and give the impression that previous builds are supported, when they are not. It adds to the overall confusion when providing support, where the expectation is that you are using the latest build always.

It is possible to figure out which build marries up based on the timestamps in the changelog and the git history. The decision not to publish tags is to not make this a convenience for the above reason. Also as you say, it is much of a muchness; if a plugin is failing, it won't really matter which build it fails on.

**Comment by petehalverson** [comment]
I'm glad I stumbled upon this. Apologies for spamming other channels on the topic, I wasn't aware of this thread and didn't want to introduce a feature request via GitHub...

That said, I'm of the same mindset as @sewagolubkow. At the very least, there should be some build reference in the commit history. 

As it is now, the app only gets a build number when querying the API for an update (Issue #1632) which is inconvenient for automated deployments.

I understand your position @daftspunk, though I would argue that it serves plugin developers to reference a build number. It **does** matter what build a plugin fails on, as that helps the plugin developer troubleshoot an issue much more efficiently.

I think the benefits of introducing build numbers to the codebase / repository outweigh the risk of developers falsely assuming old builds are supported. The latter can easily be remedied with a bold line or two in the documentation.

**Comment by daftspunk** [comment]
We can look at including a BUILD_NUMBER somewhere in the source code that can be used as a point of reference.

Refs #1632
