### ISSUE TITLE
Call to undefined method October\Rain\Database\DataFeed::paginate()

### ISSUE THREAD

**Issue by biosonic** [octobercms/october#2415]
##### Expected behavior

Returned collection should be paginated as described in documentation:
https://octobercms.com/docs/database/collection#data-feed
##### Actual behavior

An unhandled error occurred:
Call to undefined method October\Rain\Database\DataFeed::paginate()
##### Reproduce steps

```
  $feed = new October\Rain\Database\DataFeed;  
  $feed->add('article', new Article);
  $feed->add('gallery', new Gallery);

  $this['records'] = $feed->orderBy('title', 'asc')->paginate(5)->get(); // not working
  //$this['records'] = $feed->limit(5)->get(); // working
```
##### October build

```
october/backend                       dev-master 1b731ae
october/cms                           dev-master 3c13b19
october/rain                          dev-master 762bb0a
october/system                        dev-master acdd5dc
```

**Comment by jcorapi** [comment]
Has anyone found a solution for this?  I'm also having the same issue.  The documents state that pagination should work and there is no method for it in the DataFeed class.

**Comment by LukeTowers** [comment]
The support demand for October is increasing, while the available time the founders have to give remains the same. These issues will be handled in time, however there are ways you can help:

- Submit a pull request that fixes this bug and wait for it to be reviewed
- [Post a bug bounty](https://www.bountysource.com/teams/october) for this specific issue so that more people can become involved with creating a fix
- [Make a financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone

**Comment by daftspunk** [comment]
It is accepted as a high priority bug.

**Comment by LukeTowers** [comment]
This is awaiting the merging of https://github.com/octobercms/library/pull/270. If we could get people to test that PR that would be much appreciated.

**Comment by Teranode** [comment]
I guess will test it since like theres too many PRs that arent getting merged

**Comment by daftspunk** [comment]
Apologies that this DataFeed idea was never really finished because in general, it is a bad idea to combine SQL queries like this, it doesn't scale very well.

**Comment by daftspunk** [comment]
As above, DataFeed is an inefficient way to merge datasets and it is advisable to use a dedicated table for this purpose. This class will be deprecated moving forward
