### ISSUE TITLE
Cannot extend controller using `addDynamicMethod`

### ISSUE THREAD

**Issue by Whyounes** [octobercms/october#2436]
##### Expected behavior

When I extend a controller, I should be able to override actions. (`index_onDelete`, etc)
##### Actual behavior

Nothing happens. The method is added nut never called.
##### Reproduce steps

Add the following code to the boot method of a plugin. The dynamic method never gets called!

``` php
\Rainlab\Blog\Controllers\Posts::extend(function ($controller) {
    $controller->addDynamicMethod('index_onDelete', function ($record) use ($controller) {
        return 'My method';
    });
});
```

**Comment by Patroklo** [comment]
Sorry, but I have been looking at the extension library today and it doesn't work like that. It doesn't override methods, you can add NEW methods into a class, but if you add an existing method, then the system will call that previously existing method instead of the dynamic one you have added (it would be soo cool to make that override, indeed, BUT also problematic, since you are changing a defined class logic from another place and it would be troublesom to follow all those changes).

There's a workaround using behaviors but it's not useful in most of the cases:
http://octobercms.com/docs/services/behaviors#usage-example

**Comment by daftspunk** [comment]
As above. Also, we need to be careful about getting too magical. Imagine if you are inspecting a method's logic, only to find it has been overridden by some other point in the code, this would be quite frustrating.

In most cases if you need to change a controller like this, create your own controller, extend the target controller as a base class and override like normal. Then you can redirect the user away from the base controller to your own.

However in *this* case, I think you just need to submit a Pull Request somewhere =)

**Comment by Eoler** [comment]
Monkey-patch everything!  :-P

> In most cases if you need to change a controller like this, create your own controller, extend the target controller as a base class and override like normal. Then you can redirect the user away from the base controller to your own.

Or override behavior and reuse it in your controllers (see TileListController):
[https://github.com/sewagolubkow/oc-tileable-plugin#list-widget](url)

**Comment by Whyounes** [comment]
@daftspunk @Patroklo Seems logical, I totally agree that things would become too magical and even confusing at some point.
Do I have to override the whole menu item to override the actions URL? Or there another solution?

**Comment by daftspunk** [comment]
Or you could hook the constructor, bind to a "before page load" event, and redirect away when the action matches the one you want.
