### ISSUE TITLE
Encoding problem with jsonable attributes

### ISSUE THREAD

**Issue by H6** [octobercms/october#2473]
##### Expected behavior
Encode jsonable attributes so that they can be decoded into objects.

##### Actual behavior
Attributes are quoted strings sometimes and then are encoded into quote-escaped thing like this `"{\"1\":{\"rule\":\"required\",\"message\":\"Test MSG\"}}"` which then can't be correctly decoded and cause an weird behaviour.

##### Reproduce steps
I my case it appeared using the form-builder plugin, which uses the normal `jsonable` method to serialize two attributes. Submitting there a form saves the above data e.g. in the database and then can't decode it later..

##### October build
`376`

**Comment by tschallacka** [comment]
is the object you are trying to save json_encoded json_encoded data?
If so, you need to json_decode twice too

**Comment by daftspunk** [comment]
This may have been fixed as part of https://github.com/octobercms/library/commit/fdf9be4a5f3fa5512aa15ce5e72d4b05f7060b0c (available in Build 381). Previously the toArray/toJson methods were not decoding the JSON property. Please confirm if this is still an issue after receiving this change.

Otherwise, this issue lacks enough detail or the replication instructions cannot be actioned easily. As per [the contribution guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#reporting-a-bug-with-octobercms), please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

Here is an example of a **bug summary**:

> The CMS page URL is not being set automatically from the title value.

Here is an example of some **reproduce steps**:

> 1. In the back-end, open the CMS > Pages section
> 1. Click the "Add" button
> 1. Enter [Hello] for the Title field
> 1. Click the Save button 

Here is an example of **expected behavior**:

> - The Title should be set to [Hello]
> - The URL should be set to [/hello]

Here is an example of **actual behavior**:

> - The Title is set to [Hello] correctly
> - The URL is left empty

**Comment by LukeTowers** [comment]
I'll test this commit as well, was having an issue related to the form controller calling `forceFill` on the october library User model class where the permissions weren't set (thus returning null for the attribute value, which the User model class used under the assumption that the attribute would be an array. That may be a separate issue however. I'll find out if the commit mentioned resolves my issue or not tomorrow.

**Comment by H6** [comment]
@daftspunk after updating to the current build version this Json encoding problem seems to be gone...
