### ISSUE TITLE
Back-end of form validation flash message

### ISSUE THREAD

**Issue by xNok** [octobercms/october#2489]
##### Expected behavior

When y define $rules in our model with the validation Trait. Then a flash message inform users of the first error in your form. 

for example the following message apears

__The due_date field is required.__

##### Actual behavior

__The Due Date field  is required.__

Actually the message displayed is the field name, which is not user friendly and not translated. Instead the label associated to the field should be displayed.

I see that $attributeNames could be usefull 

```
public $attributeNames = [
   'email' => 'Email Address',
   ...
];
```

However the information is already in the fields.yaml files, so I expect the framework to be clever enough to automatise that task.

##### Reproduce steps

```
    use \October\Rain\Database\Traits\Validation;

    /*
     * Validation
     */
    public $rules = [
      'title' => 'required',
      'due_date' => 'required|date'
    ];
```

##### October build
365

**Comment by LukeTowers** [comment]
Feel free to submit a PR to include this feature

**Comment by LukeTowers** [comment]
The support demand for October is increasing, while the available time the founders have to give remains the same. These issues will be handled in time, however there are ways you can help:

- Submit a pull request that introduces this feature and wait for it to be reviewed
- [Make a financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone

Closing as it has been over a month since any activity on this occurred.

**Comment by LukeTowers** [comment]
This can be easily done in your controller with the following code:
```php
public function formBeforeSave($model)
{
    $attributeNames = [];
    $form = $this->formGetWidget();
    foreach ($form->getFields() as $field) {
        $fieldName = implode('.', HtmlHelper::nameToArray($field->fieldName));
        $attributeNames[$fieldName] = $field->label;
    }
    if (!property_exists($model, 'attributeNames')) {
        $model->addDynamicProperty('attributeNames', $attributeNames);
    } else {
        $model->attributeNames = array_merge($attributeNames, (array) $model->attributeNames);
    }
}
```
The tricky part is where we can put it in the default form controller behaviour if we want it to run before saving the model every time? The FormController behaviour itself does not have access to running any code in the formBeforeSave() method.
