### ISSUE TITLE
OctoberCMS “unique” validation rule does not accept all conditional clauses while updating

### ISSUE THREAD

**Issue by VijayWilson** [octobercms/october#2545]
I have a backend form in my model, with "unique" validation rule, the validation works good when a new record is being created but when the same record is being updated the "unique" validation fails to include all the where conditional clauses.

    public function beforeValidate()
    {
        $this->rules['product_name'] = 'required|unique:products,product_name,NULL,id,product_type_id,'.$this->product_type_id.',product_for,'.$this->product_for;      
    }

Above **"unique"** validation rule performs perfectly for creating a new record, but while **updating** a new record it **fails** to include the conditional clause for **"product_for"** column

**Comment by daftspunk** [comment]
I think unique doesn't apply for existing records because it prevents the model from saving--it thinks itself as not unique and throws a validation error.

This is a complex case. Please submit a Pull Request to the [test plugin for investigation](https://github.com/daftspunk/oc-test-plugin) that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it *using the test plugin*.

**Comment by VijayWilson** [comment]
Actually in my case "unique" validation rule is applied for existing records, but what the problem is, it does not include **all** the **conditional clauses** which are defined in the unique rule expression. Say for example in the give validation rule "unique:products,product_name,NULL,id,product_type_id,'.$this->product_type_id.',product_for,'.$this->product_for;"
Here the conditional clause for id <> Null, product_type_id = _some_number_ is being considered but product_for = _text_ is not considered for unique validation rule

**Comment by daftspunk** [comment]
Please submit a PR to the test plugin so we can test your example scenario.

**Comment by LukeTowers** [comment]
Closing due to no further action on the part of the initial reporter.
