### ISSUE TITLE
Inconsistencies between installation methods

### ISSUE THREAD

**Issue by joseph-d** [octobercms/october#2608]
##### Expected behavior
Expected all installation methods on the website at https://octobercms.com/docs/setup/installation to install the latest stable build of OctoberCMS, which according to https://octobercms.com/changelog should be 382 at the moment.

##### Actual behavior
The different installation methods described install different builds:

[https://octobercms.com/docs/setup/installation#wizard-installation](https://octobercms.com/docs/setup/installation#wizard-installation)
This installs Build 382 as expected

[https://octobercms.com/docs/console/commands#console-install-quick](https://octobercms.com/docs/console/commands#console-install-quick)
I'm unclear about what this installs, but immediately after logging into the backend it prompts to upgrade to build 382 so the end result is the same I guess.

[https://octobercms.com/docs/console/commands#console-install-composer](https://octobercms.com/docs/console/commands#console-install-composer)
This seems to install the latest code as it appears in the master branch, and no build number displays in the backend

Finally, if I modify the composer command specified at the above URL to omit `dev-master` then I get build 3**9**2 rather than 3**8**2

Ideally, a way to run a composer command which grabs the latest stable build (ie: 382 at the moment) without one having to go to the changelog and see which version it is and specify it manually would be good.

I guess this means that the versions marked as 'pending' at https://octobercms.com/changelog should be suffixed with -dev at https://packagist.org/packages/october/october ?

**Comment by daftspunk** [comment]
It's a good question. At the moment using composer is the same as [enabling edge updates](https://octobercms.com/docs/setup/configuration#edge-updates). The pending builds represent "unreleased" updates for our less technical users, although they are still stable and suitable for consumption. Composer users and edge update users essentially help us with the testing. Not sure if there is an easy way to overcome this since October uses frequent rolling updates, as discussed in #2256.
