### ISSUE TITLE
The active theme is not found

### ISSUE THREAD

**Issue by yangzhipeng** [octobercms/october#2621]
exception 'Cms\Classes\CmsException' with message 'The active theme is not found.' in F:\xampp\htdocs\october\modules\cms\classes\Controller.php:125

exception 'ErrorException' with message 'Argument 1 passed to Cms\Classes\Router::__construct() must be an instance of Cms\Classes\Theme, null given, called in F:\xampp\htdocs\october\modules\system\classes\ErrorHandler.php on line 65 and defined' in F:\xampp\htdocs\october\modules\cms\classes\Router.php:68

**Comment by LukeTowers** [comment]
GitHub issues are not the place to dump error messages without any explanation. This wastes the time of project maintainers as they have to take time to look at your issue only to realize you're not actually reporting an issue or putting any effort into getting help with your problem. Open source doesn't equal free hand-holding support.

If you aren't even putting basic effort into asking for help (such as describing your problem instead of just dumping error messages), then why on earth should anyone else want to put any effort into helping you? Seek assistance through other channels (like the [forum](http://octobercms.com/forum), IRC channel, or Slack team) before creating an issue for your problem and put effort into asking for assistance.

**Comment by yangzhipeng** [comment]
哦！　谢谢，我自己找方法。不浪费你们宝贵的时间！！

**Comment by daftspunk** [comment]
Looks like a valid error, telling you that the active theme specified (either in cms.activeTheme or in the database) could not be found. Nothing to fix here.
