### ISSUE TITLE
Cache is cleared on october:up

### ISSUE THREAD

**Issue by toughdeveloper** [octobercms/october#2659]
##### Expected behaviour
Values set using the Cache service (http://octobercms.com/docs/services/cache) to remain after `october:up` has run.

##### Actual behaviour
Cached is cleared completely. 

##### Reproduce steps
Set something in the Cache. Run `october:up` (or log into admin), Cached value will now be lost. 

##### October build
396

---

To note, this has become an issue as clients logging into admin have been clearing the cache. As it seems the `october:up` command is ran upon login. The cache is being reset several times a day and is difficult to rely upon. 

I assume the `Cache::flush` method is being run within october:up to avoid issues with updates, would it make more sense to simply use the ::forget call on the October cached values?

**Comment by daftspunk** [comment]
Interesting, the cache needs to be cleared as part of the "update" process, perhaps not necessarily as part of the migration process (up). We'll take a look, thanks.

**Comment by toughdeveloper** [comment]
Just wondered if there was any update on this issue ? Thanks

**Comment by LukeTowers** [comment]
No update just yet, sorry.

The support demand for October is increasing, while the available time the founders have to give remains the same. These issues will be handled in time, however there are ways you can help:

- Submit a pull request that introduces this feature and wait for it to be reviewed
- [Post a bug bounty](https://www.bountysource.com/teams/october) for this specific issue so that more people can become involved with creating a fix
- [Make a financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone

**Comment by daftspunk** [comment]
We need to leave this in because there is a pretty decent flaw in Laravel's file based cache at the moment that is being counteracted by this issue's current functionality. In short the cache doesn't clean up after itself and it ends up being huge. We'll need to address the framework level issue first as it is blocker to this one.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.

**Comment by LukeTowers** [comment]
Also, has Laravel 5.5 resolved the issue with the file based cache @daftspunk? If so we could change this behaviour.
