### ISSUE TITLE
 Log system events doesn't write anything in the database

### ISSUE THREAD

**Issue by Klaasie** [octobercms/october#2696]
##### Bug summary
The new logging settings are confusing. The "Log system events" setting doesn't seem to do anything and "Log bad requests" setting seems to be the only condition to have anything written in the database.

##### Expected behavior
When Log system events is marked as "Checked" I expect the example codes below to be written in the database.
`\Log::info('Line xx of file foo.php has executed');`
`\Log::error('An error has occured!');`

##### Actual behavior
Currently as far as I can tell by the code the only condition for registering anything into the database is the "Log bad requests" switch. Meaning that the above code will only be written in the database if that one is checked.  While the "Log bad requests" should in my opinion only register uncaught exceptions into the database.

##### Reproduce steps
Execute the two examples above anywhere in an octobercms installation with "Log bad requests" set to false.

##### October build
401

**Comment by surahmans** [comment]
Ah, I should switch on "Log bad requests" to make the `trace_log()` and the code above work.

**Comment by daftspunk** [comment]
Log bad requests only records 404 requests at the moment. It has generic naming because it can be used to log 500 requests in the future. At the moment, when an error 500 occurs, it is [recorded in the Event log](https://github.com/octobercms/october/blob/master/modules/system/classes/ErrorHandler.php#L44-L46).

As far as I can tell this functionality is working properly, albeit requires some improvement. 

---
Want to help the project? Consider making [a monetary contribution](https://octobercms.com/fundraising).

**Comment by Klaasie** [comment]
If I look in the EventLog model it has a check if 'log_requests' is true. ([here](https://github.com/octobercms/october/blob/develop/modules/system/models/EventLog.php#L30-L39))
The field 'log_requests' is being set in the backend at the switch with label 'Log bad requests'.

This means that unless 'Log bad requests' is switched to on nothing is written to the database.

**Comment by daftspunk** [comment]
@Klaasie Damn, a typo, thanks for this! Will be fixed in Build 402+ (39dc4503b2286ba75691d329dcd9df8b3e562e9a)
