### ISSUE TITLE
Add support for mode option to MediaFinder

### ISSUE THREAD

**Issue by dunets** [octobercms/october#2726]
The bug is very simple... 
On media finder is we don't select anything and try to add, there are some message that inform us that we have nothing selected, but there are n controll when we acidentally try to add a folder:

![image](https://cloud.githubusercontent.com/assets/6217617/23458788/86eec2fc-fe75-11e6-84e3-d06eaf3ac443.png)

After adding:

![image](https://cloud.githubusercontent.com/assets/6217617/23458801/974e0270-fe75-11e6-8268-a50f18b942e6.png)

**Comment by daftspunk** [comment]
I was able to replicate this: folders can be selected via Media Finder.

**Comment by LukeTowers** [comment]
@daftspunk Can we have a mode of the Media Finder to allow only selection of folders? I've got a setting that I want to implement for a plugin that wants the user to select a folder, currently I do it in a text field with `$MEDIA` used to represent the media library path, but I'd much rather have a `mode: folder` on the MediaFinder widget so that I could get them to select **only** a folder.

**Comment by dunets** [comment]
@daftspunk it's possible to make auto-selection of last uploaded image? it's very pratical when we have big list of files

**Comment by LukeTowers** [comment]
@dunets I think that falls into the category of too magical / use case specific for us to add in to core. If you wanted you could dig into the code yourself and see if there's a way that you could do that through your own JS that would extend the mediafinder, but that would be up to you and probably wouldn't get merged into core.

**Comment by daftspunk** [comment]
@LukeTowers, sounds reasonable. Perhaps `selectionType: file` or `selectionType: folder` could be implemented. A Pull Request for this would be accepted.

**Comment by LukeTowers** [comment]
After thinking about this for a while, I've come up with the following idea for a solution, which involves a slight revamp which both fixes this issue and improves the overall UX of the MediaManager and MediaFinder widgets. 

1. Add support for filtering for folders and files to the MediaLibrary.
2. Add support for disabling or otherwise modifying the filter partial in the left sidebar from the MediaManager
3. Add support for specifying the filter from the MediaFinder formwidget

**Ideal Implementation:**
The mediafinder formwidget now accepts the following values for `mode`: `everything|file|folder|image|audio|video|document`. Each mode will be rendered by its own partial so that we could support having audio and video previews as well image previews.

Each of the modes are explained below:
- **`everything`**: The default mode, behaviour as it exists currently. Nothing is filtered, anything can be selected. Crop and insert button disabled. Rendered as current `file` mode.
- **`folder`**: Only folders are displayed and can be selected. The sidebar filter list is removed. Rendered same as current `file` mode.
- **`file`**: Nothing is filtered, only files can be selected. Ideally, "Folder" is removed from the sidebar filter list but everything else remains. Rendered as current `file` mode.
- **`document`**: Only documents (and folders for navigation) are displayed and can be selected. The sidebar filter list is removed. Rendered same as current `file` mode.
- **`image`**: Only images (and folders for navigation) are displayed and can be selected. The sidebar filter list is removed. Rendered as current `image` mode.
- **`audio`**: Only audio files (and folders for navigation) are displayed and can be selected. The sidebar filter list is removed. Rendered as a new partial that provides a HTML5 audio element.
- **`video`**: Only video (and folders for navigation) are displayed and can be selected. The sidebar filter list is removed. Rendered as a new partial that provides a HTML5 video element.

**Comment by LukeTowers** [comment]
changing label to shut up the bot, this will be dealt with whenever someone submits a PR or I get around to the larger media manager improvements.

**Comment by daftspunk** [comment]
This is gathering dust probably because it isn't a blocking issue. However, it has been added to the summary sheet for media manager. That means it will get addressed in the next iteration of this tool. Thanks @dunets 🙏
