### ISSUE TITLE
Backend Area inaccessible 

### ISSUE THREAD

**Issue by abhi1693** [octobercms/october#2757]
##### Expected behavior
Backend area should be accessible to the authenticated user.

##### Actual behavior
Cannot access backend area due to an undefined exception thrown while accessing the said page.

```
Type error: Argument 4 passed to Backend\Classes\NavigationManager::addSideMenuItem() must be of the type array, object given, called in /var/www/html/modules/backend/classes/NavigationManager.php on line 250
```

##### Reproduce steps
Updated to the latest build and the application crashed.

##### October build
405

I have also attached the stacks trace file.
[system.log.zip](https://github.com/octobercms/october/files/847030/system.log.zip)

**Comment by LukeTowers** [comment]
Look's like your problem is with NetSTI.Backend:
`#3 /var/www/html/plugins/netsti/backend/Plugin.php(29): Backend\Classes\NavigationManager->addMainMenuItems('October.Cms', Array)`

**Comment by abhi1693** [comment]
I removed the whole part from the plugin but the issue still persisted.

**Comment by LukeTowers** [comment]
What's the stack trace now?

**Comment by LukeTowers** [comment]
Looks like the issue comes from using an undocumented internal API to change aspects of system menu items. We could implement a change that would fix this (namely, cast `$definition` to an array before calling `$this->addSideMenuItem()`) but I'm not sure if we want to. I'll have to get @daftspunk's input.

**Comment by daftspunk** [comment]
Would need to see the code causing the error. Why is it passing an object I wonder?

**Comment by LukeTowers** [comment]
@daftspunk The offending code is this:

```php
Event::listen('backend.menu.extendItems', function($manager) {

    $manager->addMainMenuItems('October.Backend', [
        'dashboard' => [
            'icon'     => 'icon-rocket',
            'iconSvg'  => 'plugins/netsti/backend/assets/img/dashboard.svg'
        ],
    ]);
```

It's passing an object because it's referencing a menu that has already been loaded (`October.Backend`'s `dashboard` menu). Then when it adds the new attributes, it passes the existing side menu definition to the `addSideMenuItem()` method. However, because the existing definition is already instantiated as a stdClass object, it fails because the method call specifically requests an `array` through parameter type hinting.

So, to fix it we could just typecast the side menu definition to an array before calling `addSideMenuItem`

**Comment by LukeTowers** [comment]
@abhi1693 Please let me know if https://github.com/octobercms/october/commit/d1c9b1a6f1511824cbc74c7cd31926cace58fb9c solved your problem.

**Comment by abhi1693** [comment]
@LukeTowers  Yes, it solved my problem. Thank you.

**Comment by LukeTowers** [comment]
A [release note](http://octobercms.com/support/article/rn-6) has been created to document this.
