### ISSUE TITLE
[featureRequest] ruleset.xml phpcs

### ISSUE THREAD

**Issue by SebastiaanKloos** [octobercms/october#2763]
It would help every developer if there is a predefined ruleset.xml for the php code sniffer to use. This would include the PSR standards and exclusions. 

I'll try and add it myself.

I would like to know what you think about this addition!

**Comment by LukeTowers** [comment]
Interesting idea. I'm not opposed to it myself, @daftspunk what are your thoughts?

**Comment by daftspunk** [comment]
The project hasn't used an automated code sniffer thus far, we currently maintain the code quality by hand, this is because the code is seen as art rather than homogeneous. We want to keep the product and developer experience fun to use. Without a really good reason I don't think it is appropriate to be adding this at this late stage of development.

That said, we should keep this issue open for comments.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.

**Comment by SaifurRahmanMohsin** [comment]
@SebastiaanKloos You can find the rules [here](https://github.com/octobercms/october/blob/develop/phpcs.xml).
