### ISSUE TITLE
Ajax framework: redirect to url with anchor not working

### ISSUE THREAD

**Issue by wateryoma** [octobercms/october#2780]
##### Expected behavior
after returning 
```php
\Redirect::intended('/#someanchor')
```
in ajax handler, I expect redirect to page with path '/' and to anchor 'someanchor'

##### Actual behavior
server returns json
```json
{"X_OCTOBER_REDIRECT":"http:\/\/local.docker\/#someanchor"}
```
ajax progress bar hangs, no redirect

##### Reproduce steps
add ajax link to front-end, add ajax handler, return redirect with anchor in url from handler

##### October build
396

if I return redirect as
```php
\Redirect::intended('/?#someanchor')
```
it works as expected

**Comment by LukeTowers** [comment]
Problem is here: https://github.com/octobercms/october/blob/develop/modules/system/assets/js/framework.js#L330-L333
and here:
https://github.com/octobercms/october/blob/develop/modules/system/assets/js/framework.js#L330-L333

@daftspunk Is there a problem with removing those checks? Or adding a check to set isRedirect to false if the URL is the same (minus the hash fragment)?

**Comment by daftspunk** [comment]
Looks like you've linked to the same place twice. That logic is absolutely necessary. In my experience I have always been able to redirect to a hashed URL with no problems at all. 

Were you able to replicate this, @LukeTowers?

**Comment by LukeTowers** [comment]
Whoops, so I did.

Yes, I was able to replicate this. The redirect works absolutely fine, the problem is the loading indicator. 

With a normal redirect (i.e. to a different page), the call to `window.location.href = redirectUrl` will redirect the browser therefor cutting off the loading indicator and making the issue moot.

However, a call to `window.location.href = redirectUrl` where the `redirectUrl` is the same page, just a different hash will not actually redirect the browser, thus it will not cut off the loading indicator.

Because of those checks, the loading indicator is never hidden after the request completes. Again, normally this wouldn't be a problem because the browser would be navigating away from the current page where the loading indicator is displayed, but in this case the browser stays there and the user sees the loading indicator continue "loading" forever, because it was never told to stop after the request was finished specifically because of those checks.

@daftspunk Does that explain the issue a bit better?

**Comment by daftspunk** [comment]
Ah yes, I am familiar with this issue. There is no simple and reliable solution that comes to mind. I use the following JavaScript code as a workaround:

```
window.onhashchange = function() {
    window.location.reload()
}
```

**Comment by LukeTowers** [comment]
Why does the logic have to include the `isRedirect` flag when the location isn't actually changing? Can't we set the flag to false if it's just a hash change? Or could we put something like:
```
window.onhashchange = function() {
    loading.hide();
}
```
inside the redirect handler?

**Comment by daftspunk** [comment]
In my case I actually wanted the page to reload, but because the URL was the same (just a different hash), it did nothing. So as a workaround I used the aforementioned code.

So there are two scenarios when redirecting to the same page with a hash change:

- Dev wants the page to refresh
- Dev does not want the page to refresh (only hash change)

In both cases the browser shows a stuck loading indicator, so @LukeTowers your above idea could work, so long as it is a "bind once" event and only binds on a redirect (when isRedirect is true).

I assumed it's a redirect, so the page should always simply refresh. But I can see merit in both and I can see solutions for both too! 😄

**Comment by o0alexela0o** [comment]
i'm having same issue:
my js:

```
    onSwitchLocale: function(newLang){
        var self = this;
        this.set({loading : true});
        $.ajax({
                url: self.get('url'),
                data: { locale: newLang }, 
                type: 'POST',
                dataType: 'json',
                headers: {
                    "X-OCTOBER-REQUEST-HANDLER": "onSwitchLocale"
                },
                success: function(res){
                    window.location.reload();                
                },
                error: function (err) {
                    console.log(err);
                }
        })

    }
```

gives me  {"X_OCTOBER_REDIRECT":"http://localhost/israplanet.com"}

**Comment by LukeTowers** [comment]
@wateryoma Does https://github.com/octobercms/october/commit/f819aa607df4d8a84d6aa13cce3597ea464ac7e6 fix this for you?

@o0alexela0o I don't think your issue is the same thing at all, please provide more detail what your problem actually is.

**Comment by LukeTowers** [comment]
Assuming this is fixed since I've heard nothing from @wateryoma

**Comment by throbbing140** [comment]
i encountered that dilemma and discovered a solution https://adonetinfernal.github.io/assurance/
