### ISSUE TITLE
Menu permission issue

### ISSUE THREAD

**Issue by bartoszekj** [octobercms/october#2789]
##### Expected behavior
(Describe expected behavior here)
If user does not have a permission for the view in the section (in top menu) which is set as default url for this section but he has an access to the other views he should be automatically redirected to firs available view among the section.

##### Actual behavior
(Describe actual behavior here)
User is redirected to _access denied_ page.
Url can be manually set to other (available) view but if we have two users and each of them has an access to different view (there is no one common view) one of the users will never reach the view he has an access to.

##### Reproduce steps
(Describe the steps to reproduce the problem here)
- create a section in top menu with two views - A and B
- set A view as a default url 
- create 2 users with different permissions (first to A view, second - to B)
- try to test their permissions (especially to reach the view while logged in as second user)

##### October build
(October build number)
All builds

**Comment by LukeTowers** [comment]
Personally I'm of the opinion that this is something that you as the developer should be responsible for handling, (i.e., create a common view that can redirect your users as appropriate, or change the default URL based on who is logged in). 

If October tried to do this for you manually, that feels like it would be far too "magical" (so to speak), and error prone. I know it's annoying that it doesn't handle it automatically, but when you think about all the different configurations and setups in regards to controllers, navigation items, and permissions, there are just too many variables to account for in order to effectively provide that automatic redirect for all use cases.

Thoughts?

**Comment by daftspunk** [comment]
We could probably implement something like this. Say if the top navigation menu item omitted a URL in its definition. It could look at the side menu items for the first available and source the URL from that. Maybe a minor performance impact, but magic can be used with inexplicable configuration.

I may not have fully grasped this issue's description so let me know if I missed the mark.

**Comment by LukeTowers** [comment]
Not quite, that would be a separate issue (that's pretty solvable by developers anyways, they're going to have to use the top level menu item when building their functionality so they're going to release if it's missing a URL). 

What @bartoszekj is describing is the top level menu item is connected to a controller that has a required permission on it in order to access the page. Theoretical user doesn't have that permission and can't view that controller; but they can view a menu item that is defined in the sidemenu of the main menu.

In my opinion it's too magical because there are all sorts of assumptions about where to redirect the user to if they don't have permissions to view that page; and since this is talking about permissions required on the target controller (not the menu item itself); too much magic involved in determining ahead of time if the user doesn't actually have access to the target. Thus, that's why I think it should be the responsibility of the developer to build their system in such a way that their users have a smooth experience with it regardless of the user's permissions; it's too complex an issue to deal with how developers use their various permissions within this context and build it straight into core.

**Comment by daftspunk** [comment]
As above. This concern should be addressed by a controller, not the navigation manager.. If you need a special redirection, then create an action entry point to handle it.
