### ISSUE TITLE
Need number range filter for backend lists

### ISSUE THREAD

**Issue by aleshkanet** [octobercms/october#2796]
Like a date range filter, but just for numbers. I think it's important feature.

**Comment by LukeTowers** [comment]
Feature requests as issues are only acceptable if you are using it as a pre-PR communication. If you aren't planning on implementing it yourself, then it would be better suited being asked for on one of these channels:

Forum: http://octobercms.com/forum
IRC: #october on Freenode or http://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/

The support demand for October is increasing, while the available time the founders have to give remains the same. These feature requests are absolute lowest priority for us, they may be gotten to in time. However there are ways you can help:

- Submit a pull request that introduces this feature and wait for it to be reviewed
- [Post a bug bounty](https://www.bountysource.com/teams/october) for this specific issue so that more people can become involved with creating a fix
- [Make a financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone

**Comment by aleshkanet** [comment]
I tried to do it, but unfortunately it was difficult for me. I would like to see this useful function, but as I think it will not be soon =(

**Comment by daftspunk** [comment]
So someone else can see the importance of this, can you give a real world example of when this would be useful? This could help motivate others.

**Comment by purposebuiltscott** [comment]
checkout PR #2855

**Comment by LukeTowers** [comment]
Support in #2856
