### ISSUE TITLE
Url reset on backend CMS Pages editing

### ISSUE THREAD

**Issue by cgrondin21** [octobercms/october#2819]
##### Expected behavior
Normal backend pages editing ( drag and drop, writing, stuff ...)

##### Actual behavior
The page's URL resets to its default value ( from '/news/:slug' to 'newsdetails')

##### Reproduce steps
Modify pages in backend with the CMS plugin

##### October build
412

**Comment by daftspunk** [comment]
@LukeTowers were you able to comprehend / replicate this? Not sure what's going on here.

**Comment by LukeTowers** [comment]
@daftspunk nope, not a clue.

@cgrondin21 
As per [the contribution guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#reporting-a-bug-with-octobercms), please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

**Comment by daftspunk** [comment]
This issue lacks enough detail or the replication instructions cannot be actioned easily. As per [the contribution guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#reporting-a-bug-with-octobercms), please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

Here is an example of a **bug summary**:

> The CMS page URL is not being set automatically from the title value.

Here is an example of some **reproduce steps**:

> 1. In the back-end, open the CMS > Pages section
> 1. Click the "Add" button
> 1. Enter [Hello] for the Title field
> 1. Click the Save button 

Here is an example of **expected behavior**:

> - The Title should be set to [Hello]
> - The URL should be set to [/hello]

Here is an example of **actual behavior**:

> - The Title is set to [Hello] correctly
> - The URL is left empty
