### ISSUE TITLE
Does OctoberCms support full page cache or cache rendered content

### ISSUE THREAD

**Issue by phamtranphu** [octobercms/october#2846]
##### Expected behavior
(Describe expected behavior here)
When a page is rendered, content is cached for next render

##### Actual behavior
(Describe actual behavior here)

##### Reproduce steps
(Describe the steps to reproduce the problem here)

##### October build
(October build number)

**Comment by LukeTowers** [comment]
This is useless to us. If you have a question, ask it with full detail. Don't just dump half a question into the repository issues and leave the default issue format prompts in there. Put some effort into asking your question otherwise nobody is going to put any effort into answering them.

Github issues really isn't the place for questions like this. Please use one of the many other avenues available instead of submitting new issues for your questions.

Forum: http://octobercms.com/forum
StackOverflow: http://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or http://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/

**Comment by daftspunk** [comment]
A valiant attempt no less.
