### ISSUE TITLE
Accordion like (show/hide) functionality when reordering

### ISSUE THREAD

**Issue by felagund18** [octobercms/october#2851]
##### Expected behavior
I have a big list of items, and the model has ```NestedTree``` trait. When reordering these items, all descending items are visible. I want to show/hide childItems of some parent items.

Does ```octobercms``` have this functionality already or not?

How can I achieve this?

Thanks :)

**Comment by LukeTowers** [comment]
October does not currently have this functionality. If you would like to implement it yourself, feel free :)

Otherwise; the support demand for October is increasing, while the available time the founders have to give remains the same. These requests will be handled in time, however there are ways you can help:

- Submit a pull request that introduces this feature and wait for it to be reviewed
- [Post a bug bounty](https://www.bountysource.com/teams/october) for this specific issue so that more people can become involved with creating a fix
- [Make a financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
