### ISSUE TITLE
Show nested relation on front-end

### ISSUE THREAD

**Issue by Floriskoch** [octobercms/october#2883]
Maybe this is not the right place to ask but I can't find a solution anywhere. I'm building a plugin with 3 models:

**Ingredient**
    - relations: belongsTo product, belongsTo application

**Product**
    - relations: hasMany ingredients

**Application**
    - relations: none

Now on the product page on the front-end I want to show the ingredients that belong to the product but they should be grouped by application, like so:

- application
    - ingredient
    - ingredient
- application
    - ingredient

Any help would be greatly appreciated!

**Comment by LukeTowers** [comment]
Github issues really isn't the place for questions like this. Please use one of the many other avenues available instead of submitting new issues for your questions. Also, think about the XY problem before asking questions; don't ask about your proposed solution ask about your actual problem.

Forum: http://octobercms.com/forum
StackOverflow: http://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or http://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/
