### ISSUE TITLE
Installation requirements vs CMS requirements

### ISSUE THREAD

**Issue by GinoPane** [octobercms/october#2892]
Hey guys!

A question about requirements for installation:

![image](https://cloud.githubusercontent.com/assets/3897579/26443738/87692e76-4131-11e7-83d5-590503a4cb5f.png)

Do these requirements only touch installation process, or the CMS functionality also?

As you see, I do not have ZipArchive extension enabled, so installation fails. But if I run already installed CMS on the same server, I get it running fine. 

So the question is - does this ZipArchive extension required for CMS itself (not only for installation)?

**Comment by jareis** [comment]
About  2 years ago I had the same problem with a client prodution server. And the only problem that i had was the platform update didn't work.

It is still working until this day ...

**Comment by GinoPane** [comment]
@jareis Yes, I thought that maybe update process would require this. 
But still probably it would be nice to have a small dashboard in the admin panel, which would show current environment status: is everything installed, available and ready.

**Comment by LukeTowers** [comment]
It's required for the installer and for the CMS update process. Making such a dashboard widget to show the requirements still missing is within the realms of plugins though, so I don't see the core contributors on October spending time to make it, especially since that would imply that we support such not-really-fully-supported setups. However, I wouldn't be opposed to a PR that would add that functionality; but I'd have to discuss it with @daftspunk as well.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
