### ISSUE TITLE
FR: support translation out-of-the-box

### ISSUE THREAD

**Issue by achtan** [octobercms/october#2893]
ship OctoberCMS with Translate plugin integrated in core...
than also Builder can cont with Translate plugin and it can generate transatable Modules and Forms by default, no need for manual implementation like:
````php
    public $implement = ['@RainLab.Translate.Behaviors.TranslatableModel'];

    public $translatable = [
        'title',
        'subtitle',
        'text',
    ];
````

this could save as a lot of time :)

what is the reason that Translate is not in the core?

**Comment by LukeTowers** [comment]
Backend Translation is in the core, because the core uses it to support multiple languages, but the reason that the translate plugin isn't is because it's not something that necessarily gets used by everyone. It's definitely not something that we would consider enabling by default for every model. The closest it would ever get is through a model behavior that's present in the core, but then you're doing exactly the same work as if you were to just use the Translate Plugin

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
