### ISSUE TITLE
Backend incomplete

### ISSUE THREAD

**Issue by GeRoHi** [octobercms/october#2919]
##### Expected behavior
Backend is supposed to have all its sections working.

##### Actual behavior
Top left button ("tableau de bord" in french) gets me to an infinite loadind with no error code. 

##### October build
Used oc-bootstrapper (https://github.com/OFFLINE-GmbH/oc-bootstrapper), last version of Ocms installed, served by a local nginx. php and mysql installed.

Annex question/remark : I used admin/admin to log into backend by luck, seen it documented nowhere. I'm new to October, maybe I missed a getting started tutorial ? I've spend some time in the official Docs still.

**Comment by LukeTowers** [comment]
As per [the contribution guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#reporting-a-bug-with-octobercms), please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

As it stands right now, this issue does not have enough information to do anything about at all. 

Github issues really isn't the place for questions like this. Please use one of the many other avenues available instead of submitting new issues for your questions.

Forum: http://octobercms.com/forum
StackOverflow: http://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or http://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/
