### ISSUE TITLE
Creating a plugin

### ISSUE THREAD

**Issue by tyamz** [octobercms/october#2925]
#### Expected behavior
So, I'm creating a small plugin that allows back-end users to upload files that can be downloaded by SPECIFIC front-end users. All I want to do is allow back-end users to manage these files via a back-end controller. That part is fine, however the back-end users need to know what files they are managing, and they need to know information about those specific files. For example, they need to know the File name, disk name, the name of the user that the file is "attached" to, and maybe some other user information. I seem to have no problem pulling user information from the User Database, however pulling information about the file is not going so well as expected.

#### Actual behavior
[A screenshot of what the controller looks like...](http://i.imgur.com/bjvMZ9T.png)

As you can see, under the "File" Tab, nothing is being shown. I believe there is some issue here, but I'm not sure how to fix it.

##### This is my columns.yaml: [columns.yaml](https://gist.github.com/tyamz/f182d9a2c2e261ae6e3b3378fddc6134)

Just for testing purposes, I changed the key on the _file_'s _**attachOne**_ relation, to `id_`, just because I know it would produce an SQL error.

##### Here is that error:
`SQLSTATE[HY000]: General error: 1 no such column: jumplink_downloads_files.id_ (SQL: select "jumplink_downloads_files".*, (select name from "users" where "jumplink_downloads_files"."user_id" = "users"."id") as "full_name", (select email from "users" where "jumplink_downloads_files"."user_id" = "users"."id") as "email", (select disk_name from "system_files" where "system_files"."attachment_id" = "jumplink_downloads_files"."id_" and "system_files"."attachment_type" = ? and "field" = ?) as "disk_name" from "jumplink_downloads_files" order by "file_name" desc)`

I believe the issue is coming from `and "system_files"."attachment_type" = ? and "field" = ?`, but I'm not entirely sure how to fix that.

#### October build
(419)

I apologize if this is not the place to post this, but the forums and Slack honestly don't seem helpful AT ALL.

**Comment by LukeTowers** [comment]
Github issues really isn't the place for questions like this. Please use one of the many other avenues available instead of submitting new issues for your questions.

Forum: http://octobercms.com/forum
StackOverflow: http://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or http://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/

@tyamz I know you said you didn't find the forums or Slack helpful at all, but you have to be pretty patient with wherever you post your question. Please keep in mind the (XY Problem)[http://xyproblem.info/] when asking your question.
