### ISSUE TITLE
List all pictures upload on system file

### ISSUE THREAD

**Issue by hatame** [octobercms/october#2955]
##### Expected behavior
Is there any way to list all files and pictures that upload on system file in the backend like a plugin?

##### October build
419

**Comment by LukeTowers** [comment]
Github issues really isn't the place for questions like this. Please use one of the many other avenues available instead of submitting new issues for your questions.

Forum: http://octobercms.com/forum
StackOverflow: http://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or http://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/

As a side note, you should be able to do this just by using a list controller in your plugin and telling it to use the `System\Models\File` model. I don't know why you would want to do that though.
