### ISSUE TITLE
how to use factory seed database table

### ISSUE THREAD

**Issue by buuug7** [octobercms/october#2978]
```
factory(StatisticOne::class,50)->create();
```
but it give me error like below:
```
[InvalidArgumentException]
  Unable to locate factory with name [default] [Buuug7\Statistics\Models\Stat
  isticOne].
```
where is problem?

**Comment by LukeTowers** [comment]
Github issues really isn't the place for questions like this. Please use one of the many other avenues available instead of submitting new issues for your questions.

Forum: http://octobercms.com/forum
StackOverflow: http://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or http://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/
