### ISSUE TITLE
Required fields are not being required

### ISSUE THREAD

**Issue by michaeI** [octobercms/october#2981]
##### Expected behavior
When adding a field via Builder->Models->Forms and making it Required I would like see a warning message that the required field is empty, the empty field vill be focused and the form submit will be canceled.

##### Actual behavior
It is possible to submit the form without entering any data into Required fields - Although they are marked with red dot as required.

##### Reproduce steps
Create a plugin via Builder with an input filed and mark this field as Required. Go to the plugin page and add an item while leaving the Required field empty 

##### October build
419

I have tested it on Text field and Date Pickers

**Comment by LukeTowers** [comment]
This is because the FormController behaviour doesn't actually do any validation itself. The `required` property in `fields.yaml` is purely a cosmetic one at the moment. If you want actual validation to occur, then implement the [`\October\Rain\Database\Traits\Validation`](http://octobercms.com/docs/database/traits#validation) trait in your model and define the validation rules.
