### ISSUE TITLE
how to display jsonable value in list 

### ISSUE THREAD

**Issue by swapnildbalak** [octobercms/october#3088]

**Comment by LukeTowers** [comment]
Github issues really isn't the place for questions like this. Please use one of the many other avenues available instead of submitting new issues for your questions.

Forum: http://octobercms.com/forum
StackOverflow: http://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or http://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/

Also, the amount of effort people put into helping you is directly proportional to the amount of effort that you put into asking questions.
