### ISSUE TITLE
Callback while extending model does not work

### ISSUE THREAD

**Issue by SebastiaanKloos** [octobercms/october#3102]
##### Expected behavior
Do the callback while extending plugin.

##### Actual behavior
```
\Backend\Models\User::extend(function ($model) {
    dd($model);
});
```

Is working. But this does not.

```
\ICTBelang\Contacts\Models\Contact::extend(function ($model) {
    dd($model);
});
```

##### Reproduce steps
The model looks like this
```
<?php namespace ICTBelang\Contacts\Models;

use Model;

/**
 * Model
 */
class Contact extends Model
{
    use \October\Rain\Database\Traits\Validation;

    use \October\Rain\Database\Traits\SoftDelete;

    protected $dates = ['deleted_at'];

    /*
     * Validation
     */
    public $rules = [
    ];

    /**
     * @var string The database table used by the model.
     */
    public $table = 'ictbelang_contacts_contacts';
}
```

##### October build
422

**Comment by LukeTowers** [comment]
You have to actually be using the model before the extending code gets called. `dd()` in the Backend User Model will cause the script to `dd()` because that model actually gets used on every backend request.

However, if you aren't actually doing anything with your `\ICTBelang\Contacts\Models\Contact` model in that request then you won't trigger your extension to be added to the model class. Try the following:

```php
\ICTBelang\Contacts\Models\Contact::extend(function ($model) {
    dd($model);
});

$model = new \ICTBelang\Contacts\Models\Contact()
```

**Comment by SebastiaanKloos** [comment]
@LukeTowers You are a real hero! Thank you very much. You answer solved the issue!

**Comment by LukeTowers** [comment]
Not a problem, happy to help!
