### ISSUE TITLE
How can i pass a component variable to another component

### ISSUE THREAD

**Issue by tim0991** [octobercms/october#3197]
```
[postDetail]
slug = {{ :slug }}

[commentLists]
post_id = {{ postDetail.post.id }}
```

it does not works

**Comment by LukeTowers** [comment]
The amount of time spent asking for help is directly related to the amount of time spent putting in effort to answer it. If you want help and / or guidance, then invest as much time as possible in making questions that are detailed and easy to understand. Otherwise, nobody is going to invest their time helping with a question that wasn't even worth the askers time to ask correctly.
