### ISSUE TITLE
where is froala_drm

### ISSUE THREAD

**Issue by tim0991** [octobercms/october#3225]
I want to compile richeditor assets, but i find `Rich Editor is protected by DRM` comment in serviceProvider

```
/*
 * Rich Editor is protected by DRM
 */
if (file_exists(base_path('modules/backend/formwidgets/richeditor/assets/vendor/froala_drm'))) {
    $combiner->registerBundle('~/modules/backend/formwidgets/richeditor/assets/less/richeditor.less');
    $combiner->registerBundle('~/modules/backend/formwidgets/richeditor/assets/js/build.js');
}
```

where i can get the `froala_drm` directory?

**Comment by LukeTowers** [comment]
By paying for it. Froala is a paid WYSIWYG editor that @daftspunk purchased a business license for with money raised from the community. The license does not allow the inclusion of the source code for the editor within our project, so only @daftspunk can compile the assets. We generally don't want people contributing compiled assets anyways, we do that ourselves. If you need to make a change only for your project and the only way you can do it is in the files themselves instead of CSS or JS overrides later in the page, then just edit the compiled files directly. Although I highly recommend against doing that.
