### ISSUE TITLE
plugin Builder to pagination , there is nothing in page 2, 3, 4... it only show the page 1,  use the plugin Blog is ok, why

### ISSUE THREAD

**Issue by zhujiacheng1992** [octobercms/october#3228]
when i use octobercms plugin Builder to list the page with pagination , there is nothing in page 2, 3, 4... it only show the page 1,  why
![image](https://user-images.githubusercontent.com/25140952/32582504-22b6de74-c52a-11e7-844e-df13216bf046.png)

**Comment by LukeTowers** [comment]
The amount of time spent asking for help is directly related to the amount of time spent putting in effort to answer it. If you want help and / or guidance, then invest as much time as possible in making questions that are detailed and easy to understand. Otherwise, nobody is going to invest their time helping with a question that wasn't even worth the askers time to ask correctly. Also, this belongs in the RainLab.Builder repository, not the main octobercms repository.
