### ISSUE TITLE
Unknown database type json requested

### ISSUE THREAD

**Issue by 1298799999** [octobercms/october#3231]
##### Expected behavior
install themes or plugins

##### Actual behavior
Update failed

"Unknown database type json requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it." on line 423 of /var/www/zt11.localhost/vendor/doctrine/dbal/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php
Try again

##### Reproduce steps

![image](https://user-images.githubusercontent.com/31656350/32646343-19d13a90-c627-11e7-8815-8ef4a78e4691.png)

##### October build
how to get october build number?
i installed the latest master copy with composer create ... 

the old version of vendor/doctrine/dbal is the error reason perhaps.
how to resolve it ? thank you~

**Comment by LukeTowers** [comment]
I'm assuming you're trying to use the Builder plugin?

**Comment by 1298799999** [comment]
@LukeTowers 
This error occur when i just install theme
![image](https://user-images.githubusercontent.com/31656350/32648546-38ba9dac-c631-11e7-8386-2a648e6fb9a4.png)

**Comment by LukeTowers** [comment]
@1298799999 do you have the builder plugin installed at all? What theme are you trying to install?

**Comment by austinderrick** [comment]
@LukeTowers : we're seeing this and similar errors now on any of our migrations on MySQL databases with any json() field types. It seems as though the underlying "field type" in the SQL generation may have changed to "json" instead of something like "text"?

**Comment by LukeTowers** [comment]
@austinderrick the underlying field type mapping for `json()` in Laravel for MySQL has changed from a TEXT field to a JSON field as of Laravel 5.5 (Build +420).

**Comment by austinderrick** [comment]
Thanks @LukeTowers. That makes sense. For those playing along at home, if your databases don't support this yet, you can just switch to text().

See discussion here: https://laracasts.com/discuss/channels/eloquent/table-json-generates-an-error-when-running-migrations

**Comment by LukeTowers** [comment]
In summary:

If using the `->json()` column type in your migrations, MySQL 5.7 is required to properly support it. This has changed from Laravel 5.3 on where it was changed from being a alias for `->text()` to actually creating a JSON column type in the DB schema. 

A shim to determine the version of the database and then call the appropriate method (text if <5.7, json if >=5.7) was considered, however due to the advanced features of the JSON column type we won't be creating a shim as that could lead to a developer utilizing the advanced features on a system where they aren't supported properly. For maximum compatibility when developing plugins to be used by a wider audience, stick to the `text()` column type instead unless you specify MySQL >=5.7 as a requirement for your code.
