### ISSUE TITLE
jQuery code on screen 

### ISSUE THREAD

**Issue by polo195pl** [octobercms/october#3251]
##### Actual behavior
When i go to my page i dont see a website but only jQuery Script. When i refresh page its everything ok, but when i refresh again with ctrl+f5 i see jquery code again.  You can see at: `http://77.55.231.205/portfolio/`

##### Reproduce steps
I install a new October on Apache 2.4.18 PHP7.0 and i install a plugins:
October Demo, Pages, Translate, Sitemap,Blog, Blog RSS Feed, IntenseDebate, Google Analitycs, Facebook Compoments, SEO Exstesion, Cookie consent, Contact Us

##### October build
428

**Comment by LukeTowers** [comment]
Something is happening to respond to the browsers request with your theme's combined JS asset file instead of the actual web page itself. My best guess would it be either something in your environments configuration or the plugins that are installed. Are you able to replicate it happening on a different server environment?

**Comment by polo195pl** [comment]
I try, i will back ;)

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
