### ISSUE TITLE
this is a suggestion for october

### ISSUE THREAD

**Issue by buuug7** [octobercms/october#3348]
## suggestion 
While most apps are trying to lose weight, october can not be a exception. At present the most important task is to fix the bug and reduce unnecessary features, octoberCMS aim is not to solve all problems, just like C++, try to create a universal language, this led to the C++ is arcane and difficult to use.Many years passed, and no substitute for C.  

The original intention of octoberCMS is to build a simple, easy-to-use, modern CMS.But now, octoberCMS far from their original intention is more and more, it becomes complicated, hard to use in the near future can meet octoberCMS will be more and more difficult to maintain, is more and more difficult to keep up with the laravel's footsteps.The maintainer has to spend a huge amount of work on it, and eventually the project can't be maintained. 

So, i have few several Suggestions:
+ Any place that can lose weight should lose weight.
+ Convention over configuration, There is no need to add too much configuration to the problem manually.
+ remove Assets combined from `|theme` filter, such compile LESS, this is not necessary, very litter use.
+ remove MailBrandSetting from system module , this is very litter use.

**Comment by LukeTowers** [comment]
There are no specific changes suggested that are actionable. We aren't going to be removing the LESS/SCSS asset compilation feature since
a. That breaks people's expectations that October will remain stable.
b. I like using that feature and as a developer find it incredibly useful.

We're not going to remove MailBrandSetting either because of the people's expectations that October will continue to work as it has. Unless you can provide specific suggestions and reasons for implementing those suggestions this PR is unactionable.

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
