### ISSUE TITLE
Hidden Fields in Backend forms are not being saved

### ISSUE THREAD

**Issue by kojaktaha** [octobercms/october#3352]
##### Expected behavior
When a Backed Form is Submitted with hidden the values in the Hidden should be carried to the Database and saved.

##### Actual behavior
Data is not saved

##### Reproduce steps
if I create a form with a hidden field, and then use the filterFields() function in the Model responsible from the form to add value to that hidden field,, the value is not saved into the database.

in the same form,, if I change the field to a normal filed the data will be saved normally (note: i also added the value this time from the filterFields() function.

##### October build
431

**Comment by LukeTowers** [comment]
This is done on purpose, disabled and hidden fields are removed from the dataset because otherwise the user could craft a request to change those values: https://github.com/octobercms/october/blob/master/modules/backend/widgets/Form.php#L983.

If you need to set a model property through code only and not allow a user to do it then use a hidden field but hook into beforeSave() or similar on the model itself instead of trying to do it in filterFields().

**Comment by kojaktaha** [comment]
The problem is that if I have a field that was initially hidden and change it to visible if still will not save the data!!

**Comment by kojaktaha** [comment]
Just as an additional note for future lost developers like me .... if you want to hide a field ... don't hide it in the fields.yaml file .... make it visible there and hide it using filterFields() in the model responsible for that form, as Luke said .. hidden fields in fields.yaml are not to be submitted.

**Comment by LukeTowers** [comment]
Fields hidden with $field->hidden = true in filterFields() should have the same effect @kojaktaha, is this not the case?
