### ISSUE TITLE
Question about constraining results of model query attachments

### ISSUE THREAD

**Issue by maartenmachiels** [octobercms/october#3417]
As mentioned in #2877 querying a model with file attachments is very slow when there are a lot of records in table `system_files`. Modifying the column `attachment_id` to an unsigned integer makes everything run a lot faster. If I understand correctly, this fix is still being reviewed.

In my usecase, I've made a component with an overview of mannequins (roughly 1300 mannequins, with 10-30 images each). Each mannequin is represented by his/her name and the first connected image from their relation below:

    public $attachMany = [
        'images' => 'System\Models\File'
    ];

To get an overview of the mannequins in my component, I query as follows:

```
public function onRun()
    {
        $mannequins = Mannequin::where('status', 1)->orderBy('sex', 'ASC')->orderBy('web_name', 'asc')->get();
        $this->mannequins = $this->page['mannequins'] = $mannequins;
    }
```
But this loads the mannequins with **all their images** instead of just the first one. This might not be a problem, since in the twig of my component, I can easily only show the first item.
```
{% for mannequin in mannequins %}
                <figure >
                    <img src="{{ mannequin.images.first.path | app }}" />
                    <figcaption class="c-model__name">{{ mannequin.web_name }}</figcaption>
                </figure>
        {% endfor %}
```
Since I'm looking to get the **best possible performance**, my question is: is there a way to constrain the file attachments to only get the first connected image per mannequin in my `onRun` function?

Thank you for looking into this.

**Comment by LukeTowers** [comment]
The query to retrieve multiple images in a relationship has essentially the same performance affect as the query to retrieve one. Unless you're dealing with multiple thousands of related images attached to each mannequin (at which point it would be a memory constraint with loading that many Eloquent record) you don't have anything to worry about here. 

Performance improvements that would make a bigger impact for you would be to change the type of the slave_id column to an unsigned integer. As mentioned in #3014 however I'm leery about doing that for the project as a whole because of the potential for some people to be using non-integers as their slave keys since the conception of the project. It's definitely something that you can modify on your own personal project though.

**Comment by maartenmachiels** [comment]
Thank you, Luke. I understand and will follow your suggestions.
