### ISSUE TITLE
Installation through composer create-project exits with error

### ISSUE THREAD

**Issue by GinoPane** [octobercms/october#3419]
##### Expected behavior
Successful installation

##### Actual behavior
![image](https://user-images.githubusercontent.com/3897579/36790493-e59be588-1c8c-11e8-8aba-a74bc0b09743.png)

##### Reproduce steps
Run
`composer create-project october/october projectname`

**Comment by LukeTowers** [comment]
Duplicate of #3321

**Comment by meinmotion** [comment]
Same here

**Comment by LukeTowers** [comment]
Just FYI; the install completes but it doesn't setup an application key automatically because Laravel's key:generate command expects there to be a .env file present. There's been back and forth about the correct solution in #3321 and related; but for now you can just install as normal and then run `php artisan october:env` to generate a .env file and then run `php artisan key:generate`

**Comment by GinoPane** [comment]
@LukeTowers thanks! Yes, there're workarounds, but do I understand you correctly that the general fix is not ready yet? There's a mention of 433 build there.

**Comment by daftspunk** [comment]
Apologies here, the logic was passing on my system because there was an `.env` file present.

Fixed for good hopefully in Build 435+ (https://github.com/octobercms/library/commit/bbbaeae8f52fc92a0b59dc613924900b9756c7b1)

How do you guys wait 12 minutes for composer every time?
