### ISSUE TITLE
File Attachments name convention

### ISSUE THREAD

**Issue by rajakhoury** [octobercms/october#3454]
Hi, This is more of a question. The [October\Rain\Database\Attach\File](https://octobercms.com/docs/api/october/rain/database/attach/file) Model has these two methods
`getDiskName()` and `getPartitionDirectory()` that generate a custom file path and name for uploaded objects. 

I'd like to create a BaseFileModel and extend this class to overwrite these methods, something like 
`{model_name}/{attribute_name}/{model_id}/{file_name}`
`uploads/public/user/avatar/1/my_avatar.jpg`

My question is why October chose this naming convention for attachments, Is there any reason I should avoid what I am trying to do ? 

Thank you

##### October build
434

**Comment by GinoPane** [comment]
I suppose it is for uniform file distribution (to keep number of files per directory relatively small even for large amount of files).

A stored file name itself should be a hash of a real file name (due to uniformity of hashes). In this case when you have for example, 10000 of files, they will be distributed into multiple directories with only a few files per directory. You won't end up with thousands of files in one dir and no files in another.

**Comment by rajakhoury** [comment]
Makes sense. Thank you
