### ISSUE TITLE
Can not specify a custom pivotModel in Many To Many Polymorphic relations

### ISSUE THREAD

**Issue by iboved** [octobercms/october#3485]
##### Expected behavior
I want to add my custom "pivotModel" to Many To Many Polymorphic relation. [Here](https://gist.github.com/iboved/be21e72d329544a5553f9714d09bec7b) is my Model definitions and migration structure. When I get the collection of categories, the category has \Illuminate\Database\Eloquent\Relations\MorphPivot instead of the pivot model I provided. I found out that [here](https://github.com/octobercms/library/blob/d9a9adcc20b110c5516bc69910e7459dd025aa9d/src/Database/Relations/MorphToMany.php#L161) "$using" is always null.
I found out that in Laravel we can specify a custom pivot model with "using()" method like this:
```
    public function users()
    {
        return $this->belongsToMany('App\User')->using('App\UserRole');
    }
```
Here we call [using() Laravel method](https://github.com/laravel/framework/blob/5.6/src/Illuminate/Database/Eloquent/Relations/BelongsToMany.php#L293) and set "$using" property. But in OctoberCMS we can not set pivotModel via using() method. And that's why we always have "$using" equal to null [here](https://github.com/octobercms/library/blob/d9a9adcc20b110c5516bc69910e7459dd025aa9d/src/Database/Relations/MorphToMany.php#L161).

##### Actual behavior
When I get the collection of categories, the category has \Illuminate\Database\Eloquent\Relations\MorphPivot instead of the pivot model I provided. 

##### Reproduce steps
Create application structure like [here](https://gist.github.com/iboved/be21e72d329544a5553f9714d09bec7b). And try to set your own custom pivotModel.

##### October build
October build: 434

**Comment by LukeTowers** [comment]
This is because a pivot model for a MorphToMany relationship for Laravel is different from a pivot model used for the belongsToMany relationship. October has not implemented a mirror for this so it won't work in that case. 

This is something that would be welcomed though if you were willing to dive into the library code (octobercms/library) and provide a PR to implement it. Here is Laravel's relationship implementation: https://github.com/laravel/framework/blob/56a58e0fa3d845bb992d7c64ac9bb6d0c24b745a/src/Illuminate/Database/Eloquent/Relations/MorphToMany.php#L128-L147 and October would also need a MorphPivot model extending Laravel's MorphPivot model.

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
