### ISSUE TITLE
Downgrading October to support older php

### ISSUE THREAD

**Issue by danielchikaka** [octobercms/october#3515]
I have noticed the current version works with php 7. For some reasons the server i'm working on doesn't support php 7

How can i downgrade it? Or is there a link to old repo i can download Octobercms for php below version 7?

**Comment by davethepottingshed** [comment]
Hi Daniel

Please see the following instructions: https://octobercms.com/support/article/rn-9

The bottom of the pages tells you have to install version 1.0.419 which supports PHP 5.5.9

**Comment by LukeTowers** [comment]
@danielchikaka I highly recommend that you try to find a server with PHP7 though; 419 is no longer supported so if you run into problems you're on your own.

**Comment by marcomessa** [comment]
Hello, i confirm this is related to new upgrade (core 456 | page 1.3.0). The fix is working, but therse is another error.When I try to swtich language (using RainLab.Translate), after the update I got this error:

```
Type error: Argument 2 passed to October\Rain\Halcyon\Datasource\FileDatasource::selectOne() must be of the type string, null given, called in /Users/marcomessa/dev/arredocad/vendor/october/rain/src/Halcyon/Builder.php on line 309
```

I discovered this error in production ([here, menu patched is applyed, but I can't use english version](https://www.arredocad.com/it))while in my local env before the update it was correctly working
