### ISSUE TITLE
Uninstall paid plugin problem.

### ISSUE THREAD

**Issue by LucasZdv** [octobercms/october#3531]
##### Expected behavior
I need to delete a paid plugin & omit future updates.

##### Actual behavior
I don't can delete the plugin from octobercms projects.

http://nimb.ws/EMbagN

and, I uninstall it from the backend updates, but every time request me update the plugin, although I told him to always omit.

http://nimb.ws/JSx3zT

##### October build
(434)

**Comment by daftspunk** [comment]
Interesting. It should be possible to remove plugins, there must be some edge case preventing it. Regardless, troubleshooting this involves sharing private information. Please send an email to hello [at] octobercms.com and we can help further.

**Comment by LukeTowers** [comment]
@LucasZdv see above ^

**Comment by ayumihamsaki** [comment]
@LukeTowers @daftspunk  Hi Luke and daftpunk, I show you a screenshot as of 29 June 2018. It doesn't seem to be fixed on the website:

![www](https://user-images.githubusercontent.com/17784082/42105193-59fa0be6-7bc7-11e8-8d79-dd32a79842a1.png)

Is it ok, to send an email to hello@octobercms.com and cc octobercms@luketowers.ca. Because the website says "**Please note that this Project ID is private so don’t share it with others.**"
