### ISSUE TITLE
October CMS and thousands pages

### ISSUE THREAD

**Issue by KiraSokolov** [octobercms/october#3534]
Can this cms handle and work with thousands of pages? Or do I need to look for another cms to use a plugin to save in db? 
Will there be a lot of load on the server with so many pages?

**Comment by LukeTowers** [comment]
Github issues really isn't the place for questions like this. Please use one of the many other avenues available instead of submitting new issues for your questions.

Forum: http://octobercms.com/forum
StackOverflow: http://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or http://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/
