### ISSUE TITLE
Backend users with multiple roles

### ISSUE THREAD

**Issue by wellyfrs** [octobercms/october#3557]
The current database schema allows a backend user to have only one role. Does not it make sense for a backend user to have multiple roles? I just want certain backend users to have two sets of permissions.

**Comment by LukeTowers** [comment]
@wellyfrs could you provide more details, perhaps with specifics as to why you need to have that ability? The old system of attaching permissions to groups instead of roles had this functionality but after a lot of discussion between @daftspunk and myself we determined that introduced more complexity than it warranted. If you could provide specifics on your setup and why being able to have multiple roles / groups of permissions assigned to a user at a time would be helpful; that would be helpful in figuring out the best solution going forwards.

**Comment by LukeTowers** [comment]
> A, B, and C.
That's not super helpful, please give as much specific information as possible.

I would say that you should think about the different users that will be using the system and assign roles based on that, instead of trying to split it into different roles for each of the three major areas.

**Comment by LukeTowers** [comment]
So what you're looking for in essence is the ability for your users with the `manage_users` permission to only be able to manage users with less permissions than themselves and only be able to manage permissions that they themselves have. Is this correct? (Also, see the comment in https://github.com/octobercms/october/commit/fa840d79f6cbd054830d0f4e345bf024da9f18a7 for an idea of how we thought about implementing this in the future)

**Comment by wellyfrs** [comment]
Perfect! That's exactly what we're looking for. Second-in-command users can be of many types, each with their inherited roles.

Is there a forecast for this change?

**Comment by LukeTowers** [comment]
Not right now, there's a lot of other stuff on our plates. Your options are basically to implement it yourself and make a PR or offer to sponsor it for someone to be able to find the time to implement it for you.
