### ISSUE TITLE
How can I remove permissions in external plugin without editing this plugin directly?

### ISSUE THREAD

**Issue by iboved** [octobercms/october#3559]
How can I remove some permissions in external plugin without editing this plugin directly? For example, the external plugin has `registerPermissions` method with permissions in Plugin.php. I don't want to edit this plugin directly. I want to extend this plugin in my plugin in Plugin.php file and remove some permissions.
How can I remove permissions from external plugin in my Plugin.php?
Thank you in advance.

##### October build
October build: 434

**Comment by LukeTowers** [comment]
Github issues really isn't the place for questions like this. Please use one of the many other avenues available instead of submitting new issues for your questions.

Forum: http://octobercms.com/forum
StackOverflow: http://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or http://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/

As a side note, why do you want to remove permissions???
