### ISSUE TITLE
Back-end settings category shows up multiple times for same translated value

### ISSUE THREAD

**Issue by NathanBastiaans** [octobercms/october#3561]
##### Expected behavior
When using language files to translate the settings category the same translated value should be just one category. 

##### Actual behavior
When using language files to translate the settings category the same value shows up as a separate category 

##### Reproduce steps
Create two separate plug-ins:

In the first plugin:
```
    public function registerSettings()
    {
        return [
            'settings' => [
                'category'    => 'my.plugin::lang.settings.category',
                ... 
            ]
        ];
    }
```

In the second plugin
```
    public function registerSettings()
    {
        return [
            'settings' => [
                'category'    => 'my.otherplugin::lang.settings.category',
                ... 
            ]
        ];
    }
```

For both plugins define the `settings.category` value as the same value i.e. `Website`

The `my.plugin::lang.settings.category` and `my.otherplugin::lang.settings.category` both have the same value and are translated correctly but it shows up as different categories. 

<img width="323" alt="schermafbeelding 2018-05-25 om 13 42 01" src="https://user-images.githubusercontent.com/8858465/40543422-9644abe2-6024-11e8-9ebe-b437d2c63a5f.png">

##### October build
October build: 436 

The behaviour is the same on a new OctoberCMS.

**Comment by LukeTowers** [comment]
This is done on purpose, this is because categories are grouped based on the untranslated values. If you want them to exist in the same group then you need to assign the same untranslated value as their category, i.e. `my.plugin::lang.settings.category` for both. Either that or just do `category => Lang::get('my.plugin::lang.settings.category')` which would retain the translations but since it would be translating the text before the Settings Manager grouped the items it would also put them both in the same group if their translations were the same.
