### ISSUE TITLE
ReportWidget not supporting form filter submitting by ajax

### ISSUE THREAD

**Issue by sushmak2216** [octobercms/october#3587]
##### Expected behavior
i want to filter the  records of a type by date into dashboard graph analytics

##### Actual behavior
The dashboard graph analytics is showing static graph analytics

##### Reproduce steps
The form filter is not adding into ReportWidget and the ajax handler also not working. So that i can filter the records into ReportWidget graph analytics in dashboard

##### October build
(October build number)

**Comment by LukeTowers** [comment]
The amount of time spent asking for help is directly related to the amount of time spent putting in effort to answer it. If you want help and / or guidance, then invest as much time as possible in making questions that are detailed and easy to understand. Otherwise, nobody is going to invest their time helping with a question that wasn't even worth the askers time to ask correctly.

If you want to report this as a bug, then provide a minimal set of reproduction instructions for maintainers to be able to reproduce said bug. If you want to ask a question, then please use one of the many other avenues available instead of submitting new issues for your questions.

Forum: http://octobercms.com/forum
StackOverflow: http://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or http://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
