### ISSUE TITLE
Unable to rewrite key "connections.mysql.database" in config, rewrite faile d

### ISSUE THREAD

**Issue by mrhili** [octobercms/october#3598]
##### Expected behavior
installer work prfectly

##### Actual behavior
dontwork

##### Reproduce steps
i use homestead

In ConfigWriter.php line 60:

##### October build
latest

**Comment by LukeTowers** [comment]
The amount of time spent asking for help is directly related to the amount of time spent putting in effort to answer it. If you want help and / or guidance, then invest as much time as possible in making questions that are detailed and easy to understand. Otherwise, nobody is going to invest their time helping with a question that wasn't even worth the askers time to ask correctly.
