### ISSUE TITLE
api for mobile app

### ISSUE THREAD

**Issue by AnnuD77** [octobercms/october#3600]
i want to create api for mobile app using october cms api generator. so how can i create a api for mobile for login

**Comment by LukeTowers** [comment]
Github issues really isn't the place for questions like this. Please use one of the many other avenues available instead of submitting new issues for your questions.

Forum: http://octobercms.com/forum
StackOverflow: http://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or http://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/
