### ISSUE TITLE
Add pagination to the Media Manager for large collections

### ISSUE THREAD

**Issue by brunocascio** [octobercms/october#3612]
##### Expected behavior
Ability to get media manager paginated in order to avoid 504 error.

##### Actual behavior
I have a media manager with thousands of items, but it is not paginated, so it crashes. I am using Rainlab.Drivers plugin (S3 config).

##### Reproduce steps
Upload thousand of items and try to load the media manager...

##### October build
437

**Comment by brunocascio** [comment]
@LukeTowers  Have you any plans to implements this soon?

**Comment by LukeTowers** [comment]
@brunocascio not unless someone sponsors it or does it themselves and submits a PR. See the standard response below ;)

The support demand for October is increasing, while the available time the founders have to give remains the same. These issues will be handled in time, however there are ways you can help:

- Submit a pull request that introduces this feature and wait for it to be reviewed
- [Contribute to my Patreon](https://www.patreon.com/LukeTowers) so that I can spend more time on issues like these
- [Make a financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone

**Comment by Fenn-CS** [comment]
@LukeTowers please why did you close the issue? It's a genuine problem that the media manager cannot be used in (large) production scale. Should this not be left open so we examine how to fix it?

**Comment by LukeTowers** [comment]
@Fenn-CS I closed your issue because this issue already exists, is open, and is the same as yours.

**Comment by bennothommo** [comment]
Closing this in favour of https://github.com/octobercms/october/issues/4622, as they both reference the same issue, but there's been more discussion on potential fixes in that one.

**Comment by lewis-jump24** [comment]
> Closing this in favour of https://github.com/octobercms/october/issues/4622, as they both reference the same issue, but there's been more discussion on potential fixes in that one.

The above discussion is a 404 for me. I'm having similar problems, was the issue ever resolved? Thanks.

**Comment by daftspunk** [comment]
Hi @lewis-jump24,

We have added it to our internal tracker for the next iteration of the media manager. The solution for now is to group things into folders.
