### ISSUE TITLE
Security Requirements on Marketplace Plugins

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#3615]
I'm probably gonna get a lot of hate comment replies - but I would like to raise this issue.

There are so many plugins in the OctoberCMS Marketplace that bypass the Twig XSS Protection and use RAW tags etc.

I really don't understand why so many developers are doing this when there are: `htmlclean()` and `Html Purifier` plugins out there.

Surely the October CMS Marketplace should check for security issues on all plugins?!

In vBulletin CMS for example they label plugins that have security issues such as XSS.

Anyway, just felt like I should mention this as the number of plugins with security issues is very high in the marketplace!

Also another issue I see is the Open Redirect Security Issue in a lot of plugins.

I think the Marketplace should test all plugins for the: [OWASP Top Ten Security Issues](https://www.owasp.org/index.php/Category:OWASP_Top_Ten_2017_Project)

**Comment by LukeTowers** [comment]
@ayumihamsaki if there are any specific security vulnerabilities to report with a marketplace plugin, please email hello@octobercms.com and cc octobercms@luketowers.ca. Plugins submitted to the marketplace by @alekseybobkov but there isn't enough resources to perform pentests on all submitted plugins so we rely on users reporting anything non-obvious.

**Comment by ayumihamsaki** [comment]
@LukeTowers Hi Luke I hope all is well your end. 

In the past I have reached out to various developers and told them about there security issues with there plugins and 100% seem to either not care or can not be bothered. 

I will give you some brief examples of issues but I will be honest and say most likely over 90% of the plugins in the Marketplace have very bad security vulnerabilities! There are probably only 4 people who take security and their plugins seriously, You and Rainlab are in that list. I know you saying "there isn't enough resources to perform pentests on all submitted plugins" but Rainlab does basic security tests using Snyk. Here is a link showing an issue and getting it fixed properly: [Cross-site Scripting (XSS)
Affecting rainlab/user-plugin package, versions <=1.4.5](https://snyk.io/vuln/SNYK-PHP-RAINLABUSERPLUGIN-72142 ), so I can't see why everyone else cant do the same?

### A few examples:

The most popular paid plugin in the marketplace is called: "Form Builder" it is a contact form builder plugin. Using contact forms, its very important to have XSS Protection yet this plugin seems to turn off XSS Protection everywhere! Therefore 880 Projects have XSS Problems, see screenshots:

![1](https://user-images.githubusercontent.com/17784082/42031749-4996320a-7acf-11e8-9284-13786406f845.png)

![2](https://user-images.githubusercontent.com/17784082/42031754-4dbc94dc-7acf-11e8-9808-ab4978b9a181.png)

Another example of a Payment Processing Plugin has this line of code:

`<form action="{{ this.page.url | app }}" method="post">`

That's an Open Redirect Security problem where a hacker can steal the users bank details so that's another serious issue! See here about this security issue: [Open Redirects](https://www.owasp.org/index.php/Unvalidated_Redirects_and_Forwards_Cheat_Sheet)

The list goes on and on, plugin after plugin! I really wish some kind of action gets taken. It's so bad now I even see hacking videos of OctoberCMS on Youtube! And I contacted YouTube to take them down. Plugin Security Vulnerabilities is a big deal for all CMS! Please take some kind of action! I want OctoberCMS to grow and be bigger than WordPress in the years to come!

**Comment by ayumihamsaki** [comment]
I think one solution would be to fully intergrate HTMLPurifier into OctoberCMS Twig and then send out emails to every dev plugin owner and tell them to change the `|raw` tags into `|purify` tags! That would be a start.

**Comment by LukeTowers** [comment]
@ayumihamsaki I understand your concerns, however I'm not convinced that any of these issues are actionable security flaws, perhaps I'm misunderstanding something.

In regards to the form builder plugin's use of `| raw`, all of the values passed to that filter come directly from the application, so I don't see how that counts as XSS since anyone with access to change those values has access to change the site to just include any JS they wanted to in the frontend. 

In regards to the `| app` filter, URL's are generated relative to the application, an attacker wouldn't be able to change it to a completely different URL. Although, you'd still need a dangerous level of access to the application to even be able to change `this.page.url` in the first place as well.

Again with `html_strip()`, if someone has access to override that function definition (including their definition before the OctoberCMS application even boots up!) then the site is already compromised and changing it to use `| purify` wouldn't have any effect. 

Am I missing anything?

**Comment by ayumihamsaki** [comment]
@LukeTowers my explanations are probably bad, I try explain.

The `|raw` tag issue, a hacker just needs to insert code into the database (easy to do) and there is no sanitation and validation to stop the hacker being able to carry on the work needed. Nothing is getting blocked.

The `this.page.url|app` issue, the code is letting any URL pass, so if a hacker redirects the user after submitting the form it will go to the bad website, see flow chart:

![open-redirection-attack-process](https://user-images.githubusercontent.com/17784082/42050101-f786f806-7aff-11e8-8466-2a833fa4c491.png)

There is no validation to stop the hacker and only select a "fixed" url. It's totally open.

The `html_strip()` attack a hacker can inject it using a malformed execution.

Hard to explain as I am not a professional pen tester. I just know that any professional security expert will look at these things and say yah they are bad.

**Comment by ayumihamsaki** [comment]
(Better if some professional security experts could chip in).

**Comment by ayumihamsaki** [comment]
I know you are not a lawyer, but...

I am a bit curious to know, under GDPR laws would October Website be liable for storing and serving Security Vulnerability plugins without doing fulls checks to make sure they pass the most common security issues?

Plus is it ok to download the free and paid plugin, contact the developer about the issue, no response or action taken to fix the problem. Patch and fix the plugin myself, save it under a different namespace and use that version under one or more websites - due to the plugin not being fit for production websites?

(Sorry to ask such terrible questions!)

**Comment by LukeTowers** [comment]
@ayumihamsaki 
> I just know that any professional security expert will look at these things and say yah they are bad

That's not exactly the case; nothing in life is black and white and the same holds true here. I'll address each of your concerns in the following response:

1. `action="{{ this.page.url | app }}"` being a potential Open Redirection Attack:
Firstly, let me say that this isn't an Open Redirection Attack, that would be User -> Trusted Site -> Malicious Site. IF an attacker was able to change the value of `this.page.url` to a URL that they controlled, then the resulting HTML would be `action="http://example.com/maliciousstuff"` resulting in User -> Malicious Site -> Whatever the attacker wants. An ORA requires that the trusted application itself is redirecting the user, this is a case of the user just submitting data directly to a malicious target without even touching the application. It could still in theory be a problem, (and the better way of writing this code to begin with would be `{{ this.page.baseFile | page }}`) IF AND ONLY IF the attacker could control the value of `this.page.url`. However, in order to have control over that value, they would need to be able to run their own code on the application which would essentially mean that they could bypass all of this altogether and just replace the partial that renders the payment form with one that they crafted themselves, no mucking about with `this.page.url` at all. 

2. > also add some csrf protection
This is handled by the `{{ form_open() }}` twig command, which I agree that plugin should be using.

3. > `html_strip()` attack a hacker can inject it using a malformed execution.
I'm not sure what you mean by "malformed execution", but if they have the ability to define functions before October even boots up then they have the ability to modify any part of the application and using something like `| purify` is not going to save you.

4. > `|raw` [filter] issue, a hacker just **needs to inject some code** and there is no sanitation and/or validation to stop the hacker
That's the key part though, somehow they need to gain access to inject that code in the first place, and if they had that access then countermeasures like using `| purify` instead are not going to help.

I appreciate your enthusiasm for looking into this stuff, but unless you can demonstrate a successful attack on a marketplace plugin (preferably in an email to protect current users if one exists) then just saying "these things are bad for security" isn't actually very helpful. 

I appreciate you wanting to discuss this though and I welcome the discussion; however it would be more helpful if you could identify specific vulnerabilities (with reproducible successful attacks) and report those instead of just saying that the marketplace should "check for security vulnerabilities in all plugins" (which @alekseybobkov already does btw).

**Comment by ayumihamsaki** [comment]
@LukeTowers hi, understand what you are saying. I will close this issue, as I know you are a very busy guy and I don't want to take up too much of your time! With regards to demo'ing successful attacks on plugins, I didn't want to write here because that would be illegal and I would propbably get into a lot of trouble. Thanks for the info on the procedure of reporting plugins with regards to security flaws, will save that. 

Thanks for your replies as always! And have a great day, will close this issue anyway...

**Comment by LukeTowers** [comment]
@ayumihamsaki if you can create a demoable attack then send it to me @ octobercms@luketowers.ca and I can address it from there. Proving that attacks exist isn't illegal, it's only illegal if you try to use it on people's sites without permission.
