### ISSUE TITLE
Cookie::queue not work

### ISSUE THREAD

**Issue by sergei3456** [octobercms/october#3636]
In custom plugins not work function Cookie::queue(Cookie::make($name, $value, $minutes)) 

##### Expected behavior
Add custom cookie next response

##### Actual behavior
Cookies are not added

##### Reproduce steps
To call function in a plugin Cookie::queue

##### October build
Build 437

**Comment by LukeTowers** [comment]
The amount of time spent asking for help is directly related to the amount of time spent putting in effort to answer it. If you want help and / or guidance, then invest as much time as possible in making questions that are detailed and easy to understand. Otherwise, nobody is going to invest their time helping with a question that wasn't even worth the askers time to ask correctly.

**Comment by chrisbethelepb** [comment]
This is not a bug with October. You need to register the `Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse` middleware in your plugin.

If you are defining routes in a `routes.php` file in your plugin, you can register them per-route, or using a route group. If you want to globally enable cookie queuing for your October install, add this to your `Plugin.php` file:

```php
    public function boot()
    {
        $this->app['Illuminate\Contracts\Http\Kernel']->pushMiddleware('Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse');
    }
```

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
