### ISSUE TITLE
Focus not jump to next field after set value.

### ISSUE THREAD

**Issue by pavelmgn** [octobercms/october#3656]
After set change several fields, timestamp and other form widgets, focus is lost and not jumping on next field.

**Comment by LukeTowers** [comment]
Detailed information required to be able to help you.

The amount of time spent asking for help is directly related to the amount of time spent putting in effort to answer it. If you want help and / or guidance, then invest as much time as possible in making questions that are detailed and easy to understand. Otherwise, nobody is going to invest their time helping with a question that wasn't even worth the askers time to ask correctly.

**Comment by pavelmgn** [comment]
In datepicker enter date value from keyboard and press "tab" key - if next field in form simple input this work good. If i click on datepicked calendar, focus from the field disappears. If after simple input i press tab key again amd after the simple input (text), select widget, then the focus also disappears.

This greatly complicates keyboard input without a mouse.

in gif i pressed tab - shift tab - click on calendar (focus disappears) - click on input text - tab - focus dissapers.
![rfg](https://user-images.githubusercontent.com/8817759/43378043-b7da5774-93dd-11e8-849f-6227b86d1258.gif)

**Comment by LukeTowers** [comment]
@pavelmgn could you make a PR to re-add focus to the datepicker input field after a click closes the datepicker popup?

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
