### ISSUE TITLE
Plugin installation fails on migration step but leaves files causing migration to be retried endlessly

### ISSUE THREAD

**Issue by JohnB7590** [octobercms/october#3660]
##### Expected behavior
So I was expecting that I would be able to make updates for October CMS.

##### Actual behavior
"SQLSTATE[42804]: Datatype mismatch: 7 ERROR: column "statistics" cannot be cast automatically to type integer HINT: You might need to specify "USING statistics::integer". (SQL: ALTER TABLE news_posts ALTER statistics TYPE INT)"

##### Reproduce steps
Now, what I did in the process of eventually coming to this final error of mine - was that I installed the news and newsletter plugin. Then, at the moment, it gave me the first such error that I encountered, but I have since lost count of how to retrieve the message for that specific error (I believe it was the same as the one above).

Anyway, when opened I my browser in order to serve the backend for October CMS, I was able to see an icon for the plugin that I failed to install the previous night; however, it gave me the error in which I'm trying to resolve.

Also, I'm curious as to whether this is an issue with the state of my postgresql tables having an error, in which the case will be that I'll have to use my pgsql client application to fix that said error. Or, perhaps, is this an issue with another error that is more easily contained within a certain file under the October CMS project folder - that I have will all of the files stored for the web pages and the admin?

##### October build
(October Version N/A - it stated 1.5.6, but I believe that was for the News and Newsletter Plugin)

**Comment by LukeTowers** [comment]
@JohnB7590 this error is occurring because October is trying to run the pending migrations for the plugin in question, however that migration is failing on your environment, probably because the author did not test on a PostgresSQL environment. 

What October could do to improve the UX for these sorts of cases is to track failing migrations and simply not try to run them more than once and throw a warning message to the users (and in your specific case of it throwing on install - remove the plugin files and throw a more meaningful warning). However, until that gets implemented and released your best course of action would be to manually remove that plugin's files from your october install which should stop it from trying to run the migration that doesn't work on your environment.

**Comment by JohnB7590** [comment]
I wanted to ask another question. So, removed the plugin, and that seemed to work for the obvious reason that the check for updates button was working (since there were no new updates). However, I still get an SQLSTATE error whenever I had tried to reinstall the plugin. However, with the SQLSTATE error, it gives you some suggestions about a table that you can alter (I believe). Where would that be located? Is it in the October CMS directory of files and such, or over on the PGSQL client?

**Comment by LukeTowers** [comment]
@JohnB7590 that would be over the PGSQL, although you'd need to work with the plugin author to resolve it so that the migrations can run automatically via code; there could be side effects to trying to do it yourself manually.
