### ISSUE TITLE
GroupBy Datetime field with the date format into listing

### ISSUE THREAD

**Issue by sushmak2216** [octobercms/october#3665]
##### Expected behavior
groupBy the list record with date with pagination (field is of datetime type )

##### Actual behavior
pagination is not working with the groupby date(As it will group by them as datetime)

##### Reproduce steps
1.) A field with datetime type, shown as date in listing
2.) Group them on behalf of date (Not  #working) with pagination functionality

##### October build
(October build number)

**Comment by LukeTowers** [comment]
The amount of time spent asking for help is directly related to the amount of time spent putting in effort to answer it. If you want help and / or guidance, then invest as much time as possible in making questions that are detailed and easy to understand. Otherwise, nobody is going to invest their time helping with a question that wasn't even worth the askers time to ask correctly.

In this specific case it would be helpful to actually provide code to reproduce the issue. If you cannot reproduce the issue (or if this is a result of user error) then please use one of the many other avenues available instead of submitting new issues for your questions.

Forum: http://octobercms.com/forum
StackOverflow: http://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or http://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/

**Comment by sushmak2216** [comment]
Sure, What else i explain? I am very bad at explaining.

**Comment by LukeTowers** [comment]
@sushmak2216 I recommend that you just ask for help on Slack, it's better suited to the Q&A style that you'll need.
