### ISSUE TITLE
Integration with list behavior is not working

### ISSUE THREAD

**Issue by sushmak2216** [octobercms/october#3720]
##### Expected behavior
The export button will export the list data into excel

##### Actual behavior
Nothing happens

##### Reproduce steps
added the following lines into list configuration files:
export:
   useList: true
**Note**: it doesnot seems to be done
Will you suggestion what am i missing?

##### October build
(October build number)

**Comment by LukeTowers** [comment]
The amount of time spent asking for help is directly related to the amount of time spent putting in effort to answer it. If you want help and / or guidance, then invest as much time as possible in making questions that are detailed and easy to understand. Otherwise, nobody is going to invest their time helping with a question that wasn't even worth the askers time to ask correctly.

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
