### ISSUE TITLE
OctoberCMS local and test server storage path issue

### ISSUE THREAD

**Issue by mittultechnobrave** [octobercms/october#3722]
I have created one virtual host in my local server .. say it as `demo.mywebsite.com` and made my all the changes using static pages and uploaded few images on the fly from editor in static pages this is working fine.

Now as soon as I uploaded on my test server,somewhere at`http://testserver.com/mywebsite`, I m unable to see the images which I had uploaded on my local server. 

When I `firebug` it, I come to know that image paths showing something like this `/storage/app/media/myimage.png` and if I change from `firebug` from `/storage/app/media/myimage.png` to `storage/app/media/myimage.png` (removed first character, which is a forward slash) then its working fine. 

So there must be storage file location issue or related to `.htaccess`.

Hence I updated my `.htaccess` from `RewriteBase /` to this `RewriteBase /mywebsite/` but it did not work. I also tried to play with removing and appending forward slash and so on but nothing worked for me. 

I also went at `config\cms.php`

       
 

    'storage' => [        
                   'uploads' => [
                       'disk'   => 'local',
                       'folder' => 'uploads',
                       'path'   => '/storage/app/uploads',
                   ],        
                    'media' => [
                       'disk'   => 'local',
                       'folder' => 'media',
                       'path'   => '/storage/app/media',
                   ],    
        ],

And tried to update `path` value in both `media` and `uploads` array from `'/storage/app/media'` to something like `'regency_cms/storage/app/media',` or `'/regency_cms/storage/app/media',`.

But these did not work either. 

Can someone guide me how we can deal with this scenario without updating my static pages code manually for each and every page. 

Any help will be highly appreciated. 

Thanks

**Comment by LukeTowers** [comment]
@mittultechnobrave this would be a question for the static pages repo, not the main one. In any case, the images have been added to the richeditor content using the path resolution that was available when the images were added to the field, the image paths within the richeditor fields are not processed through the `|media` filter later. 

To replace these paths either setup a 301 redirect of all /storage urls on your test server or change your test server to use subdomains instead of subfolders or run an automated tool through your staticpage files (like a command line tool or project find/replace all in Atom) to change those image paths.
