### ISSUE TITLE
Using touches on NestedTree causes an exception

### ISSUE THREAD

**Issue by SeriousKen** [octobercms/october#3740]
If a model that uses NestedTree is a parent of another model that defines $touches on the relationship then it throws an execption:

```
Exception: A node cannot be moved to a descendant of itself. in D:\October\PluginDevSite\vendor\october\rain\src\Database\Traits\NestedTree.php:1030
```

I think I've tracked this down to `$moveToNewParentId` being `null` as default. Setting it to `false` in the NestedTree trait seems to fix this.

**Comment by SeriousKen** [comment]
Looking into this further I think the problem lies elsewhere. My PR works because the default for $moveToNewParentId is false rather than null but the issue caused because for some reason the beforeSave event isn't firing so storeNewParent is never called.

**Comment by SeriousKen** [comment]
Got it! In the Eloquent model, touchOwners only fires the saved event, not the saving event. This means that any touched October models only fire the afterSave event, so this PR is needed to work around this case.

**Comment by LukeTowers** [comment]
This is a complex case. 

In order to aid in our understanding of the problem, please submit [a Pull Request to the test plugin](https://github.com/octoberrain/oc-test-plugin) for investigation that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it _using the test plugin_.

**Comment by SeriousKen** [comment]
@LukeTowers PR to test plugin created https://github.com/octoberrain/test-plugin/pull/52
