### ISSUE TITLE
Why not use the viewbag in the layout when Layout Model Afterfetch

### ISSUE THREAD

**Issue by minhluccode** [octobercms/october#3743]
##### Expected behavior
(Describe expected behavior here)
<img width="578" alt="screen shot 2018-08-31 at 4 47 46 pm" src="https://user-images.githubusercontent.com/29726422/44905978-e320fb80-ad3d-11e8-8ce3-54e4fce06777.png">
<img width="586" alt="screen shot 2018-08-31 at 4 48 05 pm" src="https://user-images.githubusercontent.com/29726422/44905979-e3b99200-ad3d-11e8-96f3-5cbbe13324f2.png">

##### Actual behavior
(Describe actual behavior here)

##### Reproduce steps
(Describe the steps to reproduce the problem here)

##### October build
(October build number)

**Comment by LukeTowers** [comment]
(Describe the lack of response here)

The amount of time spent asking for help is directly related to the amount of time spent putting in effort to answer it. If you want help and / or guidance, then invest as much time as possible in making questions that are detailed and easy to understand. Otherwise, nobody is going to invest their time helping with a question that wasn't even worth the askers time to ask correctly.
