### ISSUE TITLE
What are the best practices for numbering version of a plugin which several developers work with?

### ISSUE THREAD

**Issue by amorphine** [octobercms/october#3800]
Hello, wouldn't you be so kind as to help with some cases I faced with?

Case A.
There's a plugin SomePlugin which has a version 1.0.0. Two developers DevA and DevB have got to implement some features. They start with git branches BranchA, and BranchB. Both of them need to create a migration and increment a plugin version. So each of them creates a migration file but DevA thinks his update in enough major to increment SomePlugin version up to 1.1 but DevB increment a version up to 1.0.1.
A senior developer called DevS merges BranchA, october:up passes fine. Now plugin has version 1.1.0
DevS accepts DevB's patches, resolves conflicts but october:up wont apply migration due to the plugin already has 1.1.0 version and 1.0.1 migration application is possible only with manual reverting to 1.0.0 version via history records in DB or total refreshing.

Case B.
DevA and DevB commit BranchA and BranchB with plugin version incremented up to 1.0.1. DevS resolves conflicts and makes BranchB plugin version 1.0.2. DevA will pull master branch and will be able to update fine but DevB will never be able to apply DevA migration due to his DB state thinks 1.0.1 has been already applied.

**Comment by LukeTowers** [comment]
This is a tricky problem that can probably only be resolved through better communication between DevA, DevB, and DevS. Versions should be planned out in advance so that your developers are prepared for what's coming and even if they have to do a manual refresh (for instance if they were working on 1.1 when they know that 1.0.1 is also being worked on) at least they would know about it and be prepared for it.

If you have any thoughts on how it could be improved through code I'm open to hearing them but right now my suggestion would be to look at improving the communications between your developers.

**Comment by CSNWEB** [comment]
Hey @LukeTowers just saw this. As October keeps track of all migrated versions it could easily (may be by a flag) check if there are any older versions that didn't ran. 

Regarding the coordination we usually just assign a 1.x version to each dev. So if the plugin is on 1.2.x and two devs want to start working on it, one gets 1.3.x and the other one 1.4.x.

**Comment by amorphine** [comment]
Due to some curcumstances we can not afford the linear path so we found a workaround:
```
if ( \App::runningInConsole() ) {
            $mainPath    = plugins_path( 'author/plugin/migrations' );
            $directories = glob( $mainPath . '/*', GLOB_ONLYDIR );
            $paths       = array_merge( [ $mainPath ], $directories );
            $this->loadMigrationsFrom($paths);
        }
```
This line of code placed in boot section of Plugin.php allows `artisan migrate` to catch migrations.
