### ISSUE TITLE
Random 

### ISSUE THREAD

**Issue by Nelortiz** [octobercms/october#3931]
Help me how plugin random or order example A9983F937 in id_card  

$id_card = str_random(10); is work but how to save in data base in plugin 
partial path, if save no work 
Text Name if button save work in data base
and
Partial if button save no work in data base 

Partial path = file is generator_field.htm

the file of generator_field.htm is: 

<?php
$id_card = str_random(10);

?>

<input type="text" name="id_card" id="id_card" value="<?=$id_card?>" placeholder="" class="form-control" autocomplete="off" maxlength="255" />
-------------------------------------------------------------------------------------------------------------------

 Where find document 

$query->orderByRaw("RAND()");
$id_card->orderByRaw("RAND()");

or

return 
DB::table("id_card")
	->select("id_card*")
        ->orderBy(DB::raw('RAND()'))
        ->take(8)
        ->get();

where file or folder ?

**Comment by Nelortiz** [comment]
the file of generator_field.htm is:

<   ?     php
$id_card = str_random(10);

?   >

<inpu t typ  e="text" name="id_card" id="id_card" value="<?=$id_card?>" placeholder="" class="form-control" autocomplete="off" maxlength="2 55" /  >

**Comment by LukeTowers** [comment]
help me how understand question

The amount of time spent asking for help is directly related to the amount of time spent putting in effort to answer it. If you want help and / or guidance, then invest as much time as possible in making questions that are detailed and easy to understand. Otherwise, nobody is going to invest their time helping with a question that wasn't even worth the askers time to ask correctly.
