### ISSUE TITLE
Upload path per file attachment

### ISSUE THREAD

**Issue by PubliAlex** [octobercms/october#3934]
##### Expected behavior
It would be great to be able to define upload path for each attachments. Something like that : 

public $attachMany = [
    'avatar' => ['System\Models\File', 'path' => '/storage/app/media/avatar']
];

##### Actual behavior
Actually, you can only define global upload path in config/cms.php. All your uploaded files, for all your models, will be uploaded there.

##### Reproduce steps
Nothing special to do to reproduce, just a missing feature.

##### October build
All

**Comment by SeriousKen** [comment]
I would extend System\Models\File to support what you require then use it in place of the system file model.

**Comment by PubliAlex** [comment]
Thank you for your answer. I know that october cms is (pratically) fully extendable as it's largely based on laravel and most conception choices are excellent.

However, if I post here, that's because it seems to be a quite basic and often needed that should be handled by configuration. But we can discuss about that.

**Comment by LukeTowers** [comment]
@PubliAlex @SeriousKen is correct in his recommendation. We're not going to implement a path configuration option for the built in file model in the way that you ask for because it would encourage a use case that isn't officially supported, uploading file attachments to the media manager directory. 

If you still want to proceed with that approach then do what @SeriousKen recommended and in your plugin include a model that extends the base System\Models\File model and overrides the relevant methods to generate that path.
