### ISSUE TITLE
Request: Make Marketplace reviews editable

### ISSUE THREAD

**Issue by ghost** [octobercms/october#3942]
On the October CMS website Users can leave reviews about plugins.

The issue is that you can not `edit` / `change` / `update` your review after it has been sent.

This can cause a plugin developer problems due to a person leaving a neg review about the plugin having an error for example and then the author fixing it. Then the user not being able to update their review with regards to the author fixing the problem and giving good support.

I open this issue to recommend allowing users to be able to edit their reviews for plugins in the marketplace.

**Comment by bennothommo** [comment]
@daftspunk @LukeTowers @w20k I don't think we should allow changing of reviews per se, because that leaves stuff open to manipulation, but I wonder if we record the version the review was left for, to give people a bit more context and perhaps show that some negative reviews have since been resolved.

**Comment by RomainMazB** [comment]
No news about that feature? I'm facing the situation where an user ran into posting a negative review instead of opening an issue on the repo. It's a free stuff so "I don't care for my self" but I'm convinced this tool can be useful for everyone ( + OctoberCMS itself because it helps users to create theme more easily and I hope share their creation) so a negative review is negative for the users and the platform.

https://octobercms.com/theme/romainmazb-bootstrap-boilerplate#reviews

https://github.com/RomainMazB/octobercms-bootstrap-boilerplate/issues/1#issuecomment-646001492

**Comment by LukeTowers** [comment]
@RomainMazB if you login to your author dashboard and review the reviews, there should be a "flag" icon next to all the reviews, just press that and include a reason why you're flagging it and then the admins can remove it or change the rating.

**Comment by RomainMazB** [comment]
Good to know! Thanks
