### ISSUE TITLE
Question: Will there be an official E-commerce plugin in the future?

### ISSUE THREAD

**Issue by jluisgarcia** [octobercms/october#4007]
Will there be an official E-commerce plugin in the future made by the OctoberCMS Core Team?

**Comment by jluisgarcia** [comment]
Just a matter of trust, better compatibility with the base software and Long Term Support.
I am not saying an external option would be bad but I tend to favor core products.

**Comment by LukeTowers** [comment]
I'm going to go ahead and say probably not. The core team is busy enough just maintaining the core and RainLab plugins, not to mention the core team consists of three people doing this in their spare time. Any ecommerce plugin we could create would have to compete with everything else going on in our busy lives, so I don't think that would make it a good option for users. I'd would suggest you go with Shopaholic since they have a dedicated company working on that solution: https://octobercms.com/blog/post/lovata-chooses-october-cms-after-7-years-modx
