### ISSUE TITLE
afterBoot event not firing

### ISSUE THREAD

**Issue by SeriousKen** [octobercms/october#4025]
##### Expected behavior
An event handler bound to model.afterBoot should get triggered when the model is booted

##### Actual behavior
The event is never triggered

##### Reproduce steps
Bind an event handler to any model eg:

```php
Example\Plugins\Model\MyModel::extend(function ($model) {
    $model->bindEvent('model.afterBoot', function () {
        \Log::info('Model booted');
    });
});
```

##### October build
443

The cause seems to be in the constructor of `October\Rain\Database\Model`

```php
/**
 * Constructor
 */
public function __construct(array $attributes = [])
{
    parent::__construct();

    $this->bootNicerEvents();

    $this->extendableConstruct();

    $this->fill($attributes);
}
```

The parent constructor has alreadt fired the `booted` Eloquent event so when `bootNicerEvents` registers the handler for `booted` it is too late. Calling `bootNicerEvents` before calling the parent constructor seems to fix this but I don't know if this has other implications or not.

**Comment by jexme** [comment]
@LukeTowers @SeriousKen I confirm the problem, at the moment this functionality does not work, but you cannot call `bootNicerEvents` before the constructor.

Yes, in this case, the `$model-> afterBoot()` method will work, but the event itself will still not be listened to, because trait Emitter, in which the creation of new events takes place (`bindEvent` method), will not be called yet
