### ISSUE TITLE
can't display children of parent on a page connected by slug

### ISSUE THREAD

**Issue by Corymillz** [octobercms/october#4174]
I have subcategory page connected to my category page by slug so when clicked, the children belonging to the clicked category shows up.

it doesn't just work regardless of what i have tried

This is my php block

`use Corymillz\Adverts\Models\Cat;

function onStart(){

$this['subs'] = Cat::whereHas('children', function ($query) {
                  $query->where('slug','=',$this->param('slug'));
               })->get();`

while my foreach

`<ul class="record-list">

    {% for subs in subs %}
        <li>
               
                {{ subs.cat_title }}
               
        </li>
    {% else %}
        <li class="no-data">{{ noRecordsMessage }}</li>
    {% endfor %}
    </ul>`

**Comment by LukeTowers** [comment]
Github issues really isn't the place for questions like this. Please use one of the many other avenues available instead of submitting new issues for your questions.

Forum: https://octobercms.com/forum
StackOverflow: https://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or https://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/
