### ISSUE TITLE
Update the CSS to Modern Standards

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#4203]
I don't have the time to do this. But instead I feel it is worth while leaving an open issue for someone in the near future to work on.

## Issue

October CMS uses very old CSS styling, you may not see many errors on a desktop computer screen, but when you down scale on to a mobile and tablet device you will start to see many errors.

## Common CSS Issues

Things that I have noticed in the code are the following:

- The CSS is full of `px` and not switched over to using `em` or `rem`
- The CSS is using things like `floats` instead of modern CSS such as `Flexbox` and `CSS Grids`
- The CSS is missing loads of vendor prefixes so cross browser issues
- The CSS has basic errors
- The CSS has some order issues, between prefixes and standard
- Should update the CSS to w3c accessibility standards
- Many other small errors and bugs etc

## Conclusion

I leave this open and someone can work on the updates to it in the near future.  I am referring to the main CMS backend CSS files such as:

https://github.com/octobercms/october/blob/master/modules/backend/assets/css/october.css

and other such files.

**Comment by LukeTowers** [comment]
Please only use GitHub Issues for feature requests if you are using it as a pre-Pull Request collaboration tool. If you aren't planning on implementing it yourself, then it would be better suited being asked for on one of these channels:

Forum: http://octobercms.com/forum
IRC: #october on Freenode or http://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/

The support demand for October is increasing, while the available time the founders have to give remains the same. Feature requests are by default the lowest priority for us, as we don't have time to implement everyone's suggestions by ourselves. However there are ways you can help:

- Submit a pull request that introduces this feature and we'll review it. Please note that the amount of effort making the PR (code quality, rationale for inclusion in the project, explanation of changes) is directly proportional to the likelihood that we will review and merge it.
- [Make a financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone


@ayumihamsaki above is my standard take on posting issues for "other people to take care of" 😉 

Long and short of it, for the most part don't unless you plan on actively working on it. If someone cared enough to spend the time to do it, then at that point we can have an issue for it. Otherwise it's just adding to the noise of all the other open issues.
