### ISSUE TITLE
Froala license expired

### ISSUE THREAD

**Issue by Eoler** [octobercms/october#4220]
- OctoberCMS Build: 449

### Description:
After updating to a new edge build (with upgraded Froala resources: #3203) all richtext fields show this warning:
**Expired copy of the Froala Editor. Please renew the license.**
Link: https://wysiwyg-editor.froala.help/hc/en-us/articles/360000717489-Why-is-my-editor-license-expired

**Comment by w20k** [comment]
@Eoler could you try to pull `the latest - latest` changes :D

**Comment by daftspunk** [comment]
This should be fixed in Build 450. Thanks for the report!

**Comment by tobias-kuendig** [comment]
Any ETA on when build 450 will be officialy released? Froala adds a `Powered by` message to all richeditors. I'd rather have this fixed before the weekend otherwise there will be lot's of edits to undo next week.

![image](https://user-images.githubusercontent.com/8600029/55246535-b5edea80-5245-11e9-8932-7f856fedf777.png)

**Comment by Eoler** [comment]
450 is already available on my edge installations, and it fixes Froala nag screen.

**Comment by tobias-kuendig** [comment]
On edge, yes. But I don't want to switch installations to edge updates just for this problem since this might introduce other bugs from unreleased plugin updates.

**Comment by LukeTowers** [comment]
@tobias-kuendig you shouldn't have the Froala update in the first place unless you were on edgeUpdates, Build 449 was still in pending status, i.e. an edge update. https://octobercms.com/changelog

**Comment by tobias-kuendig** [comment]
The installation was updated via composer so it actually received build 449 with edgeUpdates disabled. It seems like it was updated just before build 450 was tagged. So updating it through composer again fixed the issue :+1: 	

This is the third time this month we had problems because of `pending` releases being available via composer (https://github.com/octobercms/october/issues/4178, https://github.com/octobercms/october/issues/4209 and https://github.com/octobercms/october/issues/4220). We manage lots of October installations and want to keep them up to date automatically. It's a PITA if we always have to check if it's safe to run composer update first.
I really wish we could change this release process.

**Comment by LukeTowers** [comment]
@tobias-kuendig use `dev-master` instead of `dev-develop` or `1.0` in composer (note for library you'll have to do `dev-master as 1.0`) in order to always only use the equivalent of stable builds via composer.
