### ISSUE TITLE
Access session in Twig

### ISSUE THREAD

**Issue by NedStrk** [octobercms/october#4275]
### Description:
Couldn't find an answer in the docs, but I am pretty sure the solution should be simple )

Assume we use ```Redirect::refresh()->with('message', 'Some message here');```

Now we want to access variable ```$message``` from Twig (front-end)

tried ```session_get('message')``` and ```session('message')```

**Comment by LukeTowers** [comment]
Github issues really isn't the place for questions like this. Please use one of the many other avenues available instead of submitting new issues for your questions.

Forum: https://octobercms.com/forum
StackOverflow: https://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or https://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/
