### ISSUE TITLE
Why did my plugin disappear from backend after boot method?

### ISSUE THREAD

**Issue by Corymillz** [octobercms/october#4291]
I am using the latest version of octobercms

Ok this is kind of driving me crazy. i tried boot method in a new plugin but it shows 'plugin has been removed from file system' even though it is still there in my files, and it is also removed from the builder list of plugins. I thought it was a problem with the new plugin and tried the boot method on my main dev plugin and I am now seeing the same thing in the backend plugin list and it is also removed from the builder plugin list. Every things seems working still except registered components in the plugins Plugin.php file and everyother display of the plugin in the backend. How do I get things back?

**Comment by Corymillz** [comment]
Sorry False Alert. Just a silly curly bracket close. Seems I cant delete

**Comment by LukeTowers** [comment]
Github issues really isn't the place for questions like this. Please use one of the many other avenues available instead of submitting new issues for your questions.

Forum: https://octobercms.com/forum
StackOverflow: https://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or https://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/
