### ISSUE TITLE
Slack vs. Discord

### ISSUE THREAD

**Issue by LukeTowers** [octobercms/october#4297]
Current OctoberCMS uses Slack for our community discussions and support. There has been interest expressed in switching to Discord, considering the main limitation of Slack requiring paid plans to retain history (which just isn't feasible for our community).

OctoberCMS has a Discord right now, but it's not really utilized by anyone much yet: https://discord.gg/MM3ezTZ.

Vote for your preferred platform with 👎 for slack and 👍 for Discord

**Comment by bennothommo** [comment]
We could also try Mattermost - https://mattermost.com.
Pretty much a carbon copy of Slack, but is available as open source with no history limitations that I can see.

**Comment by eightygrit** [comment]
Might be a useful link: https://stackshare.io/stackups/discord-vs-gitter-vs-slack

Also, here's [the relevant slack thread](https://octobercms.slack.com/archives/C09864473/p1556296311170400) on this topic.

**Comment by eightygrit** [comment]
Might as well throw Gitter into the conversation too.  https://gitter.im/

**Comment by eightygrit** [comment]
## Discord

The more I look at it, the more I don't like it. It's gamer-centeric, which is fine, but not what this community is about. As was noted in the slack thread, the UI is a bit of an eyesore. 

On the plus, it is popular, and that could lead to increased engagement.

## Mattermost

I love it. Great UI. FOSS. But someone does have to host it. It's a minimal expense, but also one more thing for someone to manage. If there's a volunteer, great. Otherwise, hosting is a roadblock. 

## Gitter

Good UI. Developer centric. Supposedly some points of integration with your Github repo. Looks like there's a [really active Laravel community already](https://gitter.im/laravel/laravel) there, including Tyler Otwell. Seems like a good option.

**Comment by amdad** [comment]
We need 2 things. Unlimited free history/search. And code oriented syntax would be also very welcome. 

Mattermost can be self hosted. Independent, but that means also generate a COST. Time and money.

So I think Gitter would be the weapon of choice. BUT GRAV was on gitter then moved to Slack then moved to Discord. So? Maybe Discord will be best. It looks best when it comes to UX at least.

I would choose Discord as it looks superior. 
Also there is already Discord done. So let it run for a while and test it.

**Comment by amdad** [comment]
Check this out https://getgrav.org/blog/chat-moving-to-discord

**Comment by Samuell1** [comment]
I recommend reading this: https://reactjs.org/blog/2015/10/19/reactiflux-is-moving-to-discord.html?utm_source=tuicool

**Comment by ayumihamsaki** [comment]
Hi I would like to offer two different solutions:

## Telegram

Telegram is probably the most popular messaging tool for websites that want to create channels for their users to talk and discuss things! I would suggest create and using a Telegram channel for October CMS. I believe you can have up to 50,000 users per channel.

## Arrowchat

A few years ago I bought their software and have a full license, I don't use it and would be happy to give it to the October CMS team to use on their website, you can see their software on their website here: https://www.arrowchat.com/

Disclaimer: I do not work for arrowchat and I am not trying to promote their software, I honestly have their software with a bought license, which I don't use right now and don't plan on using it - due to my full time work on some large projects.

**Comment by lautsevich** [comment]
I'd prefer Slack at the moment just because of overwhelming by chat apps. By the way, as for Telegram, there are two chats with October CMS developers:
- https://t.me/octobercms_rus - Russian speaking community (350+ users), but I think when more English speaking folks will join the chat, the locals will speak English more often! =)
- https://t.me/octobercms - English and Portuguese speaking community (30+ users). I think it's rather dead than aliveю

**Comment by ayumihamsaki** [comment]
@lautsevich Thanks for info just added it to the wiki page in this repo, but needs to be added to the octobercms website found here: https://octobercms.com/support

**Comment by lautsevich** [comment]
@ayumihamsaki, thx!

**Comment by prhost** [comment]
Telegram is widely used by development communities and technology of all kinds. I participate in several groups, it is good because everything is close by (:

I can give you group admin, or create another, but it would be nice to have everyone supporting it.

![Screen Shot 2019-06-26 at 21 05 46](https://user-images.githubusercontent.com/3984760/60223157-6922ab80-9856-11e9-902c-aae8fefcdd63.png)

**Comment by DanHarrin** [comment]
How about [https://zulipchat.com/](Zulip)? Looks alot like Slack, has a few other features, and has unlimited message history for open source projects!

**Comment by drmzio** [comment]
How about an open-source slack clone? https://rocket.chat/

**Comment by lautsevich** [comment]
IMO the IRC chat should be closed already. It's obsolete. As for changing Slack to something else... I've checked Discord and Rocket chat and have found them cool. Unlimited chat history is a very necessary functionality.

**Comment by bennothommo** [comment]
All, the new Discord chat is here, in case you miss @LukeTowers edit above:
https://discord.gg/MM3ezTZ
