### ISSUE TITLE
Persist user's list settings even after logout from backend

### ISSUE THREAD

**Issue by munxar** [octobercms/october#4357]
- OctoberCMS Build: 455
- PHP Version: 7.2.17
- Plugins Installed: none

### Expected Behavior
When I customize the list settings of any backend list (like show/hide columns, customize the order they appear or sort a column), I expect this list settings to persist.

![Bildschirmfoto von 2019-05-30 08-06-59](https://user-images.githubusercontent.com/12279988/58612194-04ede580-82b2-11e9-9296-9949262d3117.png)

### Actal Behavior
If I log out from the backend and log back in, my list settings are reset to the defaults.

### Steps To Reproduce:
- fresh october cms install (installer or composer doesn't matter)
- go to a backend page with a list (e.g. Settings/Administrators)
- change any list setting (e.g. show/hide column)
- log out from the backend
- log back in
- visite the same backend page with list and see it in its default glory

### Did this ever work?
Yes. I was not sure if this was always like that and I just never logged out of the backend, but I checked with build 446 and there the list settings are persisted even when I log out.
So I assume that somewhere between 446 and 455 this bug was introduced.

**Comment by w20k** [comment]
@munxar confirmed!

**Comment by LukeTowers** [comment]
@munxar this might have worked previously; but with its current implementation the actual bug was that it was working in the first place. These settings get stored in the session, the only reason this used to work is that there used to be a bug where the session was not properly cleaned on logout. By fixing that bug, we have made it so that this no longer works. 

The proper fix to this would be to make it an option to store cached list preferences in the UserPreference models as well as the session.

**Comment by bennothommo** [comment]
@munxar Could you give https://github.com/octobercms/october/pull/4360 a test when you have a chance, and see if this gives back the config behaviour you're looking for?

**Comment by LukeTowers** [comment]
Fixed by https://github.com/octobercms/october/commit/6d283829c04098ddb7e0f4700c0078864831806e
