### ISSUE TITLE
How refresh backend form after Save?

### ISSUE THREAD

**Issue by Cryden** [octobercms/october#4388]
How refresh backend form fields after Save model?

**Comment by w20k** [comment]
Github issues really isn't the place for questions like this. Please use one of the many other avenues available instead of submitting new issues for your questions.

Forum: https://octobercms.com/forum
StackOverflow: https://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or https://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/
