### ISSUE TITLE
Help me :(

### ISSUE THREAD

**Issue by gusdn5387** [octobercms/october#4396]
I created a plugin on the backend. However, the speed of outputting more than 2,000,000 data to the list is very slow. Also, the speed at which all data is imported and moved from Page 1 to Page 2 is very slow. Downloading over 10,000 data to csv is also very slow. Can you solve this speed problem? Please let me know how to solve the problem. :(

**Comment by bennothommo** [comment]
@gusdn5387 There's a few things you can try:

- Optimise the indexes in your database table. Make sure you have indexes for all fields that are sorted or related.
- Set the `showPageNumbers` setting for the list widget to `false`.
- Limit the number of filters applied to the row set so that there's less computation involved
- Try and separate groups of rows to other pages if possible, to shrink the number of rows needed. 2 million rows is probably going to slow down any application regardless of language or framework.
