### ISSUE TITLE
Vendor assets in the default demo theme are out of date

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#4407]
I just noticed that the vendor assets for the default demo theme are out of date.

- jQuery is using v1.11.1 (has a lot of security issues and xss problems)
- Bootstrap is using v3.3.7 (5 years old now)
- Font Awesome v3.2.1 (5 years old now)

Can update all these to latest versions, I think it is worth doing as this demo theme is pre-installed on everyone's CMS.

I will do this PR next, after I have finished the tab pr.

Link: https://github.com/octobercms/october/tree/master/themes/demo/assets/vendor

**Comment by LukeTowers** [comment]
The demo theme is just that, a demo. What you could do is replace the jQuery entirely with the embedded version of jQuery by using `@jquery` instead of including it's own assets but I don't see a good enough reason to update either Font Awesome or Bootstrap. If people want updated versions of those libraries there are plenty of other starter themes they can use (including one of my own: https://github.com/luketowers/oc-blank-theme)
