### ISSUE TITLE
Help Me :( 

### ISSUE THREAD

**Issue by gusdn5387** [octobercms/october#4409]
I tried to use the radio button on __list_toolbar.htm in the backend list to divide the data by month and week. But I can not solve it. Is there a good way?

> <div data-control="toolbar">
    <div class="btn-group">
        <a
            href="<?= Backend::url('partner/ad/ad/export') ?>"
            class="btn btn-default oc-icon-download">
            download
        </a>
        <div class="radio custom-radio" style="display:inline-block; margin-left:10px;">
            <input name="radio" value="1" type="radio" id="radio_1"/>
            <label for="radio_1">month</label>
        </div>
        <div class="radio custom-radio" style="display:inline-block">
            <input name="radio" value="2" type="radio" id="radio_2"/>
            <label for="radio_2">week</label>
        </div>
        <div class="radio custom-radio" style="display:inline-block">
            <input checked="checked" name="radio" value="3" type="radio" id="radio_3"/>
            <label for="radio_3">day</label>
        </div>
    </div>
</div>

And on the backend controller, is it possible to pass the $query variable of listExtendQuery to another function? I want to take the value and send it to the page by creating a variable $this->vars ['q'] = $query->get().

**Comment by LukeTowers** [comment]
Github issues really isn't the place for questions like this. Please use one of the many other avenues available instead of submitting new issues for your questions.

Forum: https://octobercms.com/forum
StackOverflow: https://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or https://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/
