### ISSUE TITLE
AJAX Select2 Issues

### ISSUE THREAD

**Issue by DanHarrin** [octobercms/october#4413]
As per #4411 and #4412 with @LarBearrr.

**Comment by DanHarrin** [comment]
@LarBearrr feel free to add.

Part of the issue here is that the docs currently state `onGetOptions()` to return a keyed array with all of the options as keys and values. This is fine when working with PHP, but this is then parsed into a JSON object as JS doesn’t support keyed arrays. Select2 is then expecting an array, not an object. That’s where some of this issue is. The JSON object needs to be adapted into an array.

**Comment by DanHarrin** [comment]
Here's what's needed to support the current docs' JSON object format:
```
// results passed from request
var options = [];

for (var i in results) {
    if (results.hasOwnProperty(i)) {
        options.push({
            id: i,
            text: results[i],
        });
    };
};

options = JSON.stringify(options);
```

**Comment by w20k** [comment]
Related: https://github.com/octoberrain/test-plugin/pull/75

**Comment by DanHarrin** [comment]
PR: #4414

**Comment by DanHarrin** [comment]
Related: #2722

**Comment by LarBearrr** [comment]
Here is an updated method that is working with the test example:

```
processResults: function (data,params) {
                        var results = data.result;
                        var options = [];

                        for (var i in results) {
                            if (results.hasOwnProperty(i)) {
                                options.push({
                                    id: i,
                                    text: results[i],
                                });
                            };
                        };                       
                        return {
                            results: options
                        };
```

**Comment by DanHarrin** [comment]
Fixed with #4414.

**Comment by jimcottrell** [comment]
According to this commit:

```Support for the original `results` array format is however retained to ensure backwards compatibility.```

This appears not to be the case, as `processResults` doesn't check for `data.results` at all. This has broken some widgets for me. Supporting array results is a fine idea, but I'd like to also have the option to specify the Select2 data format directly.

**Comment by jimcottrell** [comment]
Looking at the docs again, maybe I should be clearer. Prior to `processResults` being added, AJAX handlers had to return results in the Select2 format:

```
return [
    'results' => [
        [
            'id' => 'ID',
            'text' => 'Label,
            'selected' => false
        ]
        ...
    ],
    'pagination' => [ // If used
        'more' => true
    ]
];
```

This is what I'm assuming was meant as "the original `results` array format" though perhaps that's not what the commit refers to. Either way, this is the use case that this commit breaks.

**Comment by bennothommo** [comment]
@jimcottrell Would you mind filling out another issue specifying the format above? I will be happy to add a PR to this in a few days, as I sometimes use Select2 formatted data as well.

**Comment by LukeTowers** [comment]
@jimcottrell the "original" results array was `$results = ['id' => 'value]` (https://github.com/octobercms/october/pull/4412/files#diff-eeb59170f4b88ede5425e3575bc899d0L80).

Looks like the issue is that it's not expecting additional objects to be passed in the results response, it's just expecting the contents of the results item. That should be relatively easy to fix.

**Comment by jimcottrell** [comment]
I would say this was more a case of incorrect documentation, because giving Select2 its expected format always worked, and I guess I question whether this was a necessary code change. The new `processResults` does support the originally-documented associative array, but was anyone writing it that way, since it didn't work before? And the added suggested format is just a subset of the Select2 format, so we almost duplicate what's already there natively, but without supporting all functionality.

Anyway, I guess at this point maybe it's too late and we're locked into supporting the associative array?

**Comment by LukeTowers** [comment]
@jimcottrell yup, it was made public in 457 which is stable so we have to support it now. We could easily adjust the JS to support all three methods though.
