### ISSUE TITLE
Google Browser Editing Page Problem

### ISSUE THREAD

**Issue by opjklu** [octobercms/october#4422]
- OctoberCMS Build: ### Build 456
- PHP Version: 7.3
- Database Engine: mysql
- Plugins Installed: 

### Description:
Google browser CMS module edit page, can not edit normally, Firefox browser can, for example, can not delete normally, add code

**Comment by bennothommo** [comment]
As per [the contribution guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#reporting-a-bug-with-octobercms), please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

**Comment by w20k** [comment]
Or a video clip/gif.

**Comment by opjklu** [comment]
[Kazam_screencast_0000.zip](https://github.com/octobercms/october/files/3341350/Kazam_screencast_0000.zip)

**Comment by bennothommo** [comment]
@opjklu I'm still unclear as to what the issue is. Are you talking about the caret position in the editor appearing out of position from where the input characters are appearing?

**Comment by opjklu** [comment]
yes

**Comment by bennothommo** [comment]
@opjklu I'm not getting the same issue, even with the same conditions from your video. I would suggest trying to run `artisan cache:clear` and `artisan october:util compile assets` from the command line just to eliminate some common issues. If you can provide some additional info so that we can properly replicate the issue, please feel free to re-open this issue.
