### ISSUE TITLE
Install plugins via upload panel

### ISSUE THREAD

**Issue by alvaro-canepa** [octobercms/october#453]
Actually the only way to install plugins is via the "Marketplace". Will be great if we can upload the compressed file (zip|tar.gz) and continue with the installation. Always from the backend panel.

**Comment by Alex360hd** [comment]
Not sure this is a duplicate, the author talk about the possibility to install private plugins using the backend.

The post you linked as a duplicate is about the possibility to install market plugins by searching their name instead of knowing their unique code...

+1 for the author request, I work in an agency that plan to use october CMS by default for most small projects. Actually, we have a project ID with some default modules from the marketplace but we developped our owns (thanks to the builder) and we want to keep them private (at least at the moment).

It's a pain actually to install a non-marketplace plugin (ftp upload + commande line to initialize database etc....), here is some ideas to make the process easier :

* Add a button in the plugin backend page to upload a custom plugin archive. October would copy it's file to the right place, and install the database.
* Allow to create private plugins and private projects on october CMS website to be able to use the backend to manage/install/update your plugins without be obliged to make them public
* Allow to link one or several github repository as a source of plugins, that would allow to install and update module exactly like the ones in the marketplace, but from different source.

It would make our life far easier and will accelerate the october CMS adoption in our agency (and probably many others).

**Comment by SebastiaanKloos** [comment]
I guess you could make a plugin that solves all of the problems you have. 

Just dig a bit deeper in the installation logic of the plugins. Maybe I will create a plugin that could do all of these things when I have some free time.

**Comment by LukeTowers** [comment]
@daftspunk This could potentially be tied into what we were discussing with the adding of plugins from git sources.

**Comment by Zmove** [comment]
@LukeTowers Oh it would be a very nice addition to be able to add a git repository in the backend that would provide a new source of search for plugins install and update.

+1 to this, I think a lot of agency will applaude this feature.

**Comment by Arakiss** [comment]
+1 i think it's a necesary feature, every "famous" CMS have that kind of option to do that

**Comment by maartenmachiels** [comment]
+1, encountering difficulties running commands via the terminal on my server, even with correct version of PHP installed... Any clues how to circumvent on the short term?

**Comment by LukeTowers** [comment]
@maartenmachiels That sounds like another issue entirely, please don't hijack issues for unrelated problems - create your own.

**Comment by daftspunk** [comment]
This issue old and actionable at present, closing. @LukeTowers new issue for this, I reckon.
