### ISSUE TITLE
List setup unclickable when columns override window

### ISSUE THREAD

**Issue by mkinternet** [octobercms/october#4560]
- OctoberCMS Build: 455
- PHP Version: 7.2
- Database Engine: 5.2

### Description:
When i add many columns to columns.yaml model and rendered table override window i can't click list setup popup. It is covered by last column.

**Comment by LukeTowers** [comment]
The amount of time spent asking for help is directly related to the amount of time spent putting in effort to answer it. If you want help and / or guidance, then invest as much time as possible in making questions that are detailed and easy to understand. Otherwise, nobody is going to invest their time helping with a question that wasn't even worth the askers time to ask correctly.

**Comment by mkinternet** [comment]
https://imgur.com/vHjKkwX

Step to reproduce. 
Create list and resize window to make it smaller. List setup disappears and Right arrow shows >
I assume that it should move columns. This arrow is under the last column name and i cant click it to show next columns and list column setup button.

**Comment by LukeTowers** [comment]
Link doesn't work.

In order to aid in our understanding of the problem, please submit [a Pull Request to the test plugin](https://github.com/octoberrain/oc-test-plugin) for investigation that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it _using the test plugin_.

**Comment by mkinternet** [comment]
Same result https://imgur.com/LtmpN2K

Step to reproduce
Install test plugin
Open People list in sidebar.
Resize window to saller
Try to show columns exceeds window or open hidden list setup.

**Comment by Samuell1** [comment]
Columns have ability to be scrollable horizontally if you hold on column names.

**Comment by mkinternet** [comment]
Thanks a lot. Nice feature but it isn't obvius :). Maybe if arrows should be able to scroll table horizontally?
