### ISSUE TITLE
Can't access any site pages – ErrorException array_merge(): Argument #1 is not an array

### ISSUE THREAD

**Issue by brandsistency** [octobercms/october#4609]
All of a sudden, I can't access my dev site including the backend. When I call any URL, I get an error page, which says...

**ErrorException**
array_merge(): Argument #1 is not an array
in RegisterFacades.php (line 26)

...followed by a number of 'at' statements. The full details can be seen at [https://brandsistency.dev/october/](https://brandsistency.dev/october/).

I was simply editing some page content and have no idea what's happened but I suspect that something has corrupted? I'm a front-end designer/dev, so this back-end stuff is beyond me. 

Please help!

**Comment by LukeTowers** [comment]
@brandsistency take a look at your config/app.php file. The `aliases` section should look like this: https://github.com/octobercms/october/blob/master/config/app.php#L152-L156

If it does, then the problem is probably in `include(base_path('modules/system/aliases.php'))`, which might mean that file doesn't exist, or it's corrupted, or the system doesn't have access to read it for some reason. 

As a note, GitHub issues aren't meant for support, you'd get much better help on our Slack instead.
