### ISSUE TITLE
Custom backend path during installations.

### ISSUE THREAD

**Issue by mkinternet** [octobercms/october#4641]
Artisan installer or web installer could contain custom backend path setting option or it could create backend random path like prestashop does. I could start with backend plus random numbers and letters. This feature will increase backend security.

**Comment by bennothommo** [comment]
@mkinternet There is already a setting in `config/cms.php` called `backendUri` which can change the backend path to one which you would prefer. I don't think we're going to implement random backend URLs because it would confuse less tech-savvy people. It's also [security through obscurity](https://en.wikipedia.org/wiki/Security_through_obscurity), which is the poorest form of security one can use for securing a website.
