### ISSUE TITLE
Mustache.js outdated

### ISSUE THREAD

**Issue by ayumihamasaki2019** [octobercms/october#4643]
October currently uses Mustache 2.0.0 which is outdated.

For more details of the issues with 2.0.0, see here: https://snyk.io/vuln/npm:mustache:20151207#snyk-patches

**Comment by LukeTowers** [comment]
Mustache uses in October:

- https://github.com/octobercms/october/blob/master/modules/backend/formwidgets/fileupload/partials/_fileupload.htm#L31
- https://github.com/octobercms/october/blob/master/modules/backend/widgets/mediamanager/partials/_item-sidebar-preview.htm#L5
- https://github.com/octobercms/october/blob/master/modules/system/controllers/updates/_install_plugins.htm#L95
- https://github.com/octobercms/october/blob/master/modules/system/controllers/updates/_install_themes.htm#L97

None of these are vulnerable to the linked issue, so it is not true that 

> the October backend has several medium level Vulnerabilities with mustache 2.0.0

While the dependency could be updated, please do more research before tossing the terms "security vulnerabilities" around, especially when you're doing so on public issues instead of through our published security reporting process: https://github.com/octobercms/october/blob/master/SECURITY.md

**Comment by LukeTowers** [comment]
Merged in #4644
