### ISSUE TITLE
Icons pages not showing icon list  

### ISSUE THREAD

**Issue by Nvironmental** [octobercms/october#4665]
Hi Guys, 

I noticed something weird, on this page [October Icons](https://octobercms.com/docs/ui/icon) the icon list is missing. It was available till like 2 days ago :/ 

Am I missing something ?

**Comment by w20k** [comment]
Check your adblocker:
<img width="882" alt="Screenshot 2019-10-04 at 20 30 54" src="https://user-images.githubusercontent.com/1053320/66227485-e8d9d500-e6e5-11e9-9a0a-f0492a5a797b.png">

**Comment by mlieshout** [comment]
The icon's won't show in latest Firefox (69.0.2):

<img width="889" alt="Firefox 69 0 2 Screenshot 2019-10-05 at 13 26 16" src="https://user-images.githubusercontent.com/994055/66254253-ffc70880-e773-11e9-9199-84935ab6de32.png">

<img width="1247" alt="Screenshot 2019-10-05 at 13 30 31" src="https://user-images.githubusercontent.com/994055/66254270-57fe0a80-e774-11e9-902e-269d95aa8fb3.png">

**Comment by bennothommo** [comment]
@mlieshout It might've been a temporary error. They are appearing just fine for me, albeit on 69.0.1:

![image](https://user-images.githubusercontent.com/15900351/66255275-679d4380-e7b4-11e9-98c4-19f564ae498a.png)

**Comment by w20k** [comment]
Works for me as well.
<img width="955" alt="Screenshot 2019-10-05 at 17 01 11" src="https://user-images.githubusercontent.com/1053320/66255934-d917ca80-e791-11e9-8fd5-89f5467da4a4.png">
<img width="973" alt="Screenshot 2019-10-05 at 17 01 43" src="https://user-images.githubusercontent.com/1053320/66255935-d9b06100-e791-11e9-8beb-ae08b2663d16.png">

**Comment by mlieshout** [comment]
It's a min-height problem of the iframe. When I change it from 500px to 800px, a part is shown. When I look into the frame source, the whole page is loaded.
Same thing happens in Chrome v77.0.3865.90 
I'm on MacOS 10.14.6 btw.

<img width="1364" alt="Screenshot 2019-10-05 at 17 12 01" src="https://user-images.githubusercontent.com/994055/66256950-935c0180-e793-11e9-8453-7a851370e723.png">

**Comment by w20k** [comment]
@mlieshout you definitely having some weird issues there, probably your iframe not loading properly, because you're missing the one crucial component, which I and @bennothommo have in iframe styles - `height`:
_I'm on the Mac, latest, as well_
<img width="935" alt="Screenshot 2019-10-05 at 18 56 41" src="https://user-images.githubusercontent.com/1053320/66257454-2ac85100-e7a2-11e9-96fe-801723c912df.png">

**Comment by danielbidala** [comment]
There are issues all over in User interface guide with heights.

- Windows 10
- Chrome Version 77.0.3865.90

![screencapture-octobercms-docs-ui-dropdown-2019-10-07-18_10_13](https://user-images.githubusercontent.com/16636699/66329001-f84b5f00-e92d-11e9-9096-ce42f97a2d75.png)

**Comment by CptMeatball** [comment]
Most likely this is caused by the iframe loading a lot slower than the other parts of the page. Pausible causes slow response from the iframe, or just plain old slow internet. When throttling the browser to slow 3G you can exactly replicate the screenshots. 

Can confirm this works on MacOS 10.15.1 for:
- Chrome 78.0.3904.87
- Firefox Quantum 70.0.1 (64-bits)
- Firefox Developer 71.0b7 (64-bit)
- Opera 64.0.3417.92
- Safari 13.0.3 (15608.3.10.1.4)
