### ISSUE TITLE
Cannot reload polymorphic many-to-many relation after sync

### ISSUE THREAD

**Issue by Rike-cz** [octobercms/october#4715]
- OctoberCMS Build: 458
- PHP Version: 7.2

### Description:
I have Articles and Tags models. Relation between them is polymorphic many-to-many, so I can use `sync` method for change that. In this case everything works as expected:
```
$article = Article::find(5);
dump($article->tags->pluck('id')->toArray()); // see previous state
$article->tags()->sync([...]);
$article->load('tags');
dump($article->tags->pluck('id')->toArray()); // see state after syncing
```
**BUT** in this case not:
```
$article = Article::with('tags')->find(5); // + with!!!
dump($article->tags->pluck('id')->toArray()); // see previous state
$article->tags()->sync([...]);
$article->load('tags');
dump($article->tags->pluck('id')->toArray()); // see previous state, no db query for fetching new values was detected
```

I tried the same example in Laravel 6 and Laravel 5.5.* and second case works as expected (returns new state after re-loading relation) in both of them. So something went wrong in OctoberCMS.

**Comment by LukeTowers** [comment]
@Rike-cz you should be able to call `$article->reloadRelations('tags');`, and if that doesn't work `$article->reload()`

**Comment by Rike-cz** [comment]
@LukeTowers `$article->reloadRelations('tags')` really works! But why is wide known `load()` behavior different for Laravel 5.5 and OctoberCMS? When I googled "refresh polymorphic many-to-many relation", I found only `load()` solution as the right one. This behavioral difference made me crazy :-)

**Comment by LukeTowers** [comment]
@Rike-cz fair enough, we could easily have it trigger on the load method too by overriding https://github.com/laravel/framework/blob/5.5/src/Illuminate/Database/Eloquent/Model.php#L383 and calling the flushDuplicateCache method in our overridden one. My only concern with that is knowing exactly when else load is called because if it's called lots of times then that effectively makes the cache useless. 

Alternatively we could add some more information on this cache to the docs, do you have any recommendations for where that could go?

**Comment by Rike-cz** [comment]
Any information about cache would go [there](https://octobercms.com/docs/database/model), because it's the place where common informations about Models are expected. Different between `load `and `reloadRelations` will be helpfull [here](https://octobercms.com/docs/database/relations#eager-loading).

**Comment by LukeTowers** [comment]
@Rike-cz could you start a PR to the docs to add these notes? I can add more details to them later.
