### ISSUE TITLE
RelationController don't work with 'hasManyThrough' relations

### ISSUE THREAD

**Issue by alter72** [octobercms/october#4724]

**Comment by bennothommo** [comment]
The amount of time spent asking for help is directly related to the amount of time spent putting in effort to answer it. If you want help and / or guidance, then invest as much time as possible in providing us with enough information in order for us to assist you. Otherwise, nobody is going to invest their time helping with a question that wasn't even worth the askers time to ask correctly.

**Comment by bennothommo** [comment]
Duplicate of #2508
