### ISSUE TITLE
Remove Attachments on Plugin Refresh

### ISSUE THREAD

**Issue by DanHarrin** [octobercms/october#4779]
### Description:
Plugins' attachments aren't removed with `plugin:refresh`.

### Steps To Reproduce:
1. Attach file to record 1 within Table X.
2. Refresh Plugin X with `php artisan plugin:refresh DanHarrin.X`.
3. Recreate record 1 with no attachments.
4. Record 1 is still related to its old attachment.

I am happy to PR this feature in once someone's confirmed it as not intentional.

**Comment by DanHarrin** [comment]
An alternative approach would be a parameter for the `plugin:refresh` command to enable this behaviour.

**Comment by LukeTowers** [comment]
@DanHarrin it's not really intentional, but it's not really a bug either. If we were to implement a cleanup of the system files table on plugin refresh it would probably need to be behind a flag like `--remove-attachments` or something and I'd need to see how it was implemented before I could approve it.
