### ISSUE TITLE
Search in tree list

### ISSUE THREAD

**Issue by pavelmgn** [octobercms/october#4938]
0/ 
I have a problem with the search. After entering a search query, the tree list breaks. After clearing the search query, it is not restored.
![gif](https://user-images.githubusercontent.com/8817759/74335570-52699e80-4dbe-11ea-9f45-7267cf5bbeb1.gif)
If I hide some entries in the tree for some users. The tree works, but the search breaks it and does not show children.
I hide the lines this way:
```
public function listExtendRecords($records)
	{
		$user = BackendAuth::getUser();
		
		if ( $user->is_superuser ) {
			return $records;
		}
		
		$allowIds = PermissionHelper::getAllowMaterials(false);
		
		return Material::whereIn('id', $allowIds)->get()->toNested(false);
	}
```
![gif2](https://user-images.githubusercontent.com/8817759/74335841-e0458980-4dbe-11ea-9d1d-dfa25104f3b5.gif)

Please tell me how to solve the problem? Maybe I'm going the wrong way. Thanks.

**Comment by mjauvin** [comment]
Please, use support channels (discord/forums) for questions and problems.

Git hub issues is to report bugs only.

**Comment by LukeTowers** [comment]
This is a complex case. 

In order to aid in our understanding of the problem, please submit [a Pull Request to the test plugin](https://github.com/octoberrain/oc-test-plugin) for investigation that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it _using the test plugin_.

**Comment by chrisvidal** [comment]
I am facing the same issue.

**Comment by chrisvidal** [comment]
@pavelmgn you need to setup `searchable: true` in your model `columns.yaml` to enable the search in the wanted fields

**Comment by pavelmgn** [comment]
> @pavelmgn you need to setup `searchable: true` in your model `columns.yaml` to enable the search in the wanted fields

I know how to make the field searchable. My tree breaks during the search, and is not restored. And if I filter the strings, the search does not work at all.

**Comment by chrisvidal** [comment]
I see what you mean. I can confirm the same issue.

**Comment by LukeTowers** [comment]
Again: 

This is a complex case. 

In order to aid in our understanding / replication of the problem, please submit [a Pull Request to the test plugin](https://github.com/octoberrain/oc-test-plugin) for investigation that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it _using the test plugin_.

**Comment by pavelmgn** [comment]
> Again:
> 
> This is a complex case.
> 
> In order to aid in our understanding / replication of the problem, please submit [a Pull Request to the test plugin](https://github.com/octoberrain/oc-test-plugin) for investigation that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it _using the test plugin_.

hi, i will do this week

**Comment by pavelmgn** [comment]
[Commit](https://github.com/octoberrain/test-plugin/pull/85/commits/97e76c3297b93a1ff462a51a7df66b960a6bea7a)
[PR](https://github.com/octoberrain/test-plugin/pull/85#issue-394737462)

**Comment by daftspunk** [comment]
Fixed in next release. Thanks for the report

**Comment by iboved** [comment]
@daftspunk how did you fix this? Can you send a link to the commit?
