### ISSUE TITLE
Document data attribute API Usage

### ISSUE THREAD

**Issue by srsgores** [octobercms/october#4993]
The [current documentation for the data attributes API](https://octobercms.com/docs/ajax/attributes-api) currently lacks any description of the expected back-end API for submitting forms.

Currently, AJAX submission is achieved via jQuery, leaving theme vendors who choose not to include the library out of many plugins and back-end components.  The `request` implementation [heavily depends on jQuery](https://github.com/octobercms/october/blob/develop/modules/system/assets/js/framework.js#L79).

I propose an implementation that removes the need for jQuery.  I believe [the current implementation](https://github.com/octobercms/october/blob/develop/modules/system/assets/js/framework.js#L79) can be shortened while still maintaining browser support:

```javascript
/* Adapted from https://github.com/octobercms/october/blob/develop/modules/system/assets/js/framework.js */
window.onload = function(document) {
	const ajaxFormNodes = document.querySelectorAll("form[data-request]");
	if (ajaxFormNodes.length > 0) {
		ajaxFormNodes.addEventListener("submit", function(event) {
			event.preventDefault();
			const data = new FormData(this);
			const request = new XMLHttpRequest();
			return new Promise(function(resolve, reject) {
				const requestHeaders = {
					"X-OCTOBER-REQUEST-HANDLER": this.getAttribute("data-request"),
					"X-OCTOBER-REQUEST-PARTIALS": extractPartials(options.update)
				};
				request.onreadystatechange = function() {
					if (request.readyState !== 4) {
						return;
					}
					if (request.status >= 200 && request.status < 300) {
						resolve(request);
					}
					else {
						reject({
							status: request.status,
							statusText: request.statusText
						});
					}
				}
				request.send(data);
			}).then(function() {return false;});
		});
	}
}
```

(The above is not tested, and only serves to show a simple approach for theme vendors who do not include jQuery in their theme.)

Alternatively, and probably best, I would suggest **not** relying on AJAX to submit forms.

In either case, the documentation lacks here, as I still remain uncertain to the API endpoints and what format controllers expect by default in the JSON payload.

**Comment by LukeTowers** [comment]
@srsgores while it's unlikely that we'll move away from jQuery, that is just one implementation of the AJAX framework. I've heard from a few different people that don't like jQuery for one reason or another that they'd like to know how to use the AJAX framework without it. Right now I'd say that the easiest way of achieving that would be to read framework.js and the code in Backend\Classes\Controller.php and Cms\Classes\Controller that process the AJAX requests in order to replicate the request processing in the frontend using your library of choice. 

We could eventually add some documentation as to what exactly is expected in terms of raw data transferred and functionality that should be supported, but I personally don't have time to do that right now. @bennothommo any thoughts on this?

**Comment by srsgores** [comment]
@LukeTowers, even after reading the file, the endpoints are unclear.  If you could, at the very least, comment on the following:

1. Endpoint URL format for a plugin (for example, the corresponding endpoint for a controller with an `onSubmit` function)
2. Minimum expected data to send data via `POST` and the format expected

Finally, is there a reason why the current implementation isn't backwards-compatible with browsers not supporting js via `method` and `action` attributes in HTML?  It seems odd to me that this wouldn't just work out of the box without any JavaScript whatsoever.

**Comment by LukeTowers** [comment]
@srsgores The AJAX handling code is active on any URL handled by the Cms\Classes\Controller or Backend\Classes\Controller classes, so pretty much any normal route within October. All the serverside code expects at the most basic is an `X-OCTOBER-REQUEST-HANDLER` header with the name of the handler being called, and any data to be submitted in the request body. There are a few other headers that you can send for optional features, but that's the most basic. See https://github.com/octobercms/october/blob/develop/modules/system/assets/js/framework.js#L62-L74

**Comment by srsgores** [comment]
Just so others don't have to load up a separate instance, let's go through an example:

If I have a plugin in the directory `plugins\vimirlab\newsletter` and a controller in the path `plugins\vimirlab\newsletter\controllers\Subscribers.php` that has a `public` function, what would the URL look like?

I had tried `backend/plugins/vimirlab/newsletter/controllers/Subscribers` to no avail.

**Comment by LukeTowers** [comment]
@srsgores ah, you're asking about backend routing. The answer is in our documentation: https://octobercms.com/docs/backend/controllers-ajax#actions-views-routing.

> URL of this page is made up of the author name, plugin name, controller name and action name.
`backend/[author name]/[plugin name]/[controller name]/[action name]`

So given your example the route would be `backend/vimirlab/newsletter/subscribers/nameofpublicmethod`

**Comment by bennothommo** [comment]
@LukeTowers I've only just seen your mention to me - apologies.

I'm in two minds about jQuery in relation to our framework - on the one hand, we've historically always used jQuery, and the effort involved to change that will be great. On the other hand, we've always advertised that October will always support your framework of choice for the public side, at least. 

Our framework however creates a hard dependency for jQuery, yet we only use probably 1/50th of its functionality. We also can't use the slim version as we rely on jQuery's implementation of AJAX.

I've had in the back of my mind to investigate a more open way of using our framework, but I've probably got enough on my plate for now so it's been on hold.

**Comment by LukeTowers** [comment]
@bennothommo we wouldn't ever officially support custom framework.js implementations in the backend (if they do that then they have to re-implement every single backend JS plugin), but it would be doable to document the spec of the API so that anyone could implement it however they want. But yeah, I don't have time to take care of this myself either right now.

If anyone wants to sponsor this then I'd be willing to document the AJAX framework spec for $150 USD, otherwise read the framework.js & Backend\Classes\Controller & Cms\Classes\Controller files to figure it out for yourself if you'd like to not use jQuery for the AJAX framework at all. I will say that it's relatively straight forward, we're not exactly doing anything mind blowingly complex and there's nothing magical about jQuery that would prevent any other JS from interacting with the AJAX framework.
