### ISSUE TITLE
The Algolia powered search is inactive in certain conditions

### ISSUE THREAD

**Issue by florianstancioiu** [octobercms/october#5009]
# What happens:

The Algolia powered search is inactive in certain conditions.
There is no response from the search at all, no results are being shown in the custom search dropdown. 

# When it happens: 

This happens when I have multiple documentation tabs open at the same time, I switch to a different website for a while and I spend some time there (5+ minutes but not tested) and when I come back, the search feature no longer works. I think it's also related to how much time I stay away from the documentation tabs, on page load, the search works in every page, the problem shows only after I leave the docs and come back to them later.

# My own analysis and conclusion

I checked to see if there were any errors in the console and there was none, however, I did look in the networks tab and there seems to be no ajax request being triggered when the problem occurs.
This indicates that the problem is rooted in the frontend, in the JS files.

# My specs
Firefox Browser: `74.0 (64-bit)`

Operating System: `Ubuntu 18.04 - Linux 5.0.0-37-generic octobercms/docs#40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 GNU/Linux`

Firefox plugins installed: Adblocker

**Comment by bennothommo** [comment]
This may be worked around in the near future by a search functionality being added to the RainLab.Docs plugins (https://github.com/rainlab/docs-plugin/issues/5)

**Comment by daftspunk** [comment]
@florianstancioiu This has been an issue for some time and relates to how quickly the Algolia library can load asynchronously to the page; the client and hence this logic is something out of our control. It has 250ms to get ready and sometimes the browser cannot execute the code in time. I've since upped this to 1s and it should make it probabilistically less likely to occur in future

Thanks for the report!
