### ISSUE TITLE
Add support for Html::purify($html, $options)

### ISSUE THREAD

**Issue by LukeTowers** [octobercms/october#5118]
Refs discussion in https://github.com/rainlab/blog-plugin/commit/6ae19a6e16ef3ba730692bc899851342c858bb94.

October already has `Html::clean()` which is lightweight method for protecting against XSS attacks by sanitizing provided HTML to remove potential XSS attempts. This is mostly used for situations where the providers of the content are already in a privileged / somewhat trusted role (i.e. authenticated backend users in various contexts). However, the desire exists for a more strict / robust solution built into the core that would take advantage of the popular HTMLPurifier library (note that https://octobercms.com/plugin/vdlp-htmlpurifier already exists).

Given that the HTMLPurifier library is a heavy beast and somewhat unwieldy to use at times, we would like to add a new method to the HtmlBuilder helper: `Html::purify($html, $options);`. At this time we aren't considering adding the `| purify` Twig filter, as we feel that would encourage poor practices for performance (you should sanitize / purify on input and escape on output, not purify multiple content pieces on every page load). However, we are open to thoughts and feedback on this feature.

Right now this is low priority, but the issue is being opened to keep track of the progress and encourage discussion.

**Comment by msimkunas** [comment]
Although I do agree that adding a `purify` filter has the potential to encourage poor practices performance-wise, it would still be useful in cases where the author of the plugin did not perform proper sanitization on input and it is now left up to the end user of the plugin to purify that data on output. Obviously, this is not a long term solution and the issue should eventually be fixed in the corresponding plugin but it might be useful in certain edge cases where the original plugin can not or will not be updated.

**Comment by LukeTowers** [comment]
@msimkunas even in that case you can easily work around it:
```php
ExternalModel::extend(function($model) {
    $model->bindEvent('model.beforeSave', function () use ($model) {
        $model->dirty_attribute = Html::purify($model->dirty_attribute);
    });
});
```
