### ISSUE TITLE
Add support for tab deep linking to CMS & RainLab.Pages tabs

### ISSUE THREAD

**Issue by seanthepottingshed** [octobercms/october#5135]
- OctoberCMS Build: `466` 
- PHP Version: `7.2`
- Database Engine: `mySQL`
- Plugins Installed: `RainLab.Pages` -> `1.3.3`

### Description:
Tab linking doesn't work for pages, the same applies for CMS pages

### Steps To Reproduce:

* https://example.com/admin/rainlab/pages#primarytab-thepottingshedcontentblockslangcontent-blockstabscontent-blocks <-- Doesn't reference selected page

<img width="1664" alt="Screenshot 2020-06-23 at 11 46 09" src="https://user-images.githubusercontent.com/12046965/85394862-24a01d80-b547-11ea-94ee-b9e2595c4701.png">

**Comment by LukeTowers** [comment]
This is a pretty complicated use case that would need custom handling in the JS for both the CMS controller & RainLab.Pages. You would need to include the template file type and filename in the tab URL in order to load the main tab that houses those nested tabs before selecting the nested tab.

**Comment by seanthepottingshed** [comment]
This would still be super lovely jubbly to keep functionality consistent throughout CMS

**Comment by daftspunk** [comment]
Thanks @seanthepottingshed. I've made a note to address this in a later release, in addition to the pagers using #hashbangs instead of the session store

Overall this feature would cause some interesting looking URLs, but it would also make state persistence function a whole lot better across the app. Cheers 🍻
