### ISSUE TITLE
Crash when importing assets using CombineAssets via plugin

### ISSUE THREAD

**Issue by SaifurRahmanMohsin** [octobercms/october#5143]
- OctoberCMS Build: ### 465
- PHP Version: 7.4.7
- Database Engine: 10.4.13-MariaDB
- Plugins Installed: Mohsin.Acme

### Description:
When I use CombineAssets::combine to import some assets into the OctoberCMS combiner, it crashes at [CombineAssets#L492](/octobercms/october/blob/develop/modules/system/classes/CombineAssets.php#L492)

### Steps To Reproduce:
1. Scaffold a fresh plugin with a component.
2. Add this code to the Component.php file:
```
use System\Classes\CombineAssets;

public function onRun()
{
    $css  = ['acme.sass'];
    $this -> addCss(CombineAssets::combine($css, plugins_path() . '/mohsin/acme/assets/sass'));
}
```
3. Add the component to a page and visit that page. The error pops up:
**Invalid argument supplied for foreach()**

**Comment by SaifurRahmanMohsin** [comment]
Ooh, casting to array fixes this:
```
foreach ((array)$filters as $filter) {
```
Not sure if it's a hack or the right fix thou'.

**Comment by bennothommo** [comment]
@SaifurRahmanMohsin hmmm, you should be able to just add an array to `addCss()` directly - it'll use the combiner automatically if it is given an array of CSS files.

**Comment by LukeTowers** [comment]
@bennothommo I believe he's doing it his way to get around the AssetMaker trait using the local assetPath property to resolve the asset's location since it's in a separate folder. He could try using the plugin path helper symbol (`$`, so `$this->addCss(['$/mohsin/acme/assets/sass/acme.sass']);`) or another approach I sometimes do is to set the assetPath property right before calling addCss() to the relevant file and then changing it back after the call is completed. @SaifurRahmanMohsin could you try those approaches?

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
