### ISSUE TITLE
Validation Error in Theme File PHP Code Section Parser

### ISSUE THREAD

**Issue by mahony0** [octobercms/october#5205]
- OctoberCMS Build: 465
- PHP Version: 7.4

![err](https://user-images.githubusercontent.com/2674488/87009399-ca9d8a00-c1cd-11ea-8330-a7759d6aeb0c.jpg)

As it is shown in the screenshot, **use Cache** directive is in the method definition and commented.
Line 10 is causing this issue because if I remove the line, everything is fine.

**Comment by bennothommo** [comment]
@mahony0 As far as I'm aware, you cannot use `use` statements in the PHP code for templates, as that code is wrapped in a class before being run. If you want to use classes from external libraries, you have to use their fully-namespaced class names.

**Comment by mahony0** [comment]
My intent is not using **use Cache;** in the method definition space, but surprised while it's commented but parsed as well.
I thought this is a bug, but it seems it's not so we can close this issue as well.

**Comment by LukeTowers** [comment]
@bennothommo you can actually use `use` statements, they just can't be the root namespace since the parsed class is already in the root namespace since it doesn't have one itself. @mahony0 you are correct that it is a bug that it's picking up that use statement even though it's commented, however I'm going to submit a PR that just fixes the issue of "non-compound names" being used because trying to regex parse PHP comment states would be a nightmare.

**Comment by mahony0** [comment]
@LukeTowers is [this regex](https://regex101.com/r/UDBRPz/1) suits for it? Need be carefully tested though

**Comment by LukeTowers** [comment]
@mahony0 meh, https://github.com/octobercms/october/pull/5206 fixes it and is less risky. The commented out sections aren't getting evaluated, it's literally just looking for use statements to pull into the top of the file, so the worst that would happen is that a useless class gets imported, which doesn't do anything AFAIK. 

#5206 fixes the annoying issue that even trips me up sometimes by just preventing that error message from ever being thrown in the first place.
