### ISSUE TITLE
Improve poor performance of the adding an image to a model in the add() method

### ISSUE THREAD

**Issue by lautsevich** [octobercms/october#5208]
The query for the deleting legacy data from the `system_files` table is calling while adding an image to a model `attachOne` in the `add()` method:

PHP code example:

```PHP
$obPreviewImage = new File();
$obPreviewImage->fromFile($this->sPreviewImage);
$this->obModel->preview_image()->add($obPreviewImage);
```

SQL query:

```SQL
delete from `system_files` where `system_files`.`attachment_type` = 'Lovata\BaseCode\Models\OfferLink' and `system_files`.`attachment_id` = '266810' and `field` = 'preview_image' and `system_files`.`attachment_id` is not null order by `sort_order` asc
```

A single query execution performance:

up to 1k records | 100k+ records
--------------------- | -------------------
~560μs              | ~405ms

**Comment by bennothommo** [comment]
@lautsevich This looks to be normal to me. The `delete` query occurs in order to fire off callbacks on any previously-attached records, and I believe part of those callbacks for files is to delete the file off disk. 405ms for 100k records looks to be a good result to me for that sort of functionality.

Is there a particular optimisation that you can suggest in that whole process?
