### ISSUE TITLE
Error when using a webp file as a backend avatar image

### ISSUE THREAD

**Issue by NewEditOfficial** [octobercms/october#5279]
_I wake up and i cant access the Dashboard (backend)._

[System Log](https://github.com/octobercms/october/files/5246694/system.log)

Error:
![error](https://user-images.githubusercontent.com/19749031/93620150-d9789800-f9d9-11ea-8d57-9961ba13d031.PNG)

Thanks in advance for help!

**Comment by LukeTowers** [comment]
@NewEditOfficial looks like an issue with your hosting provider, it can't find the imagecreatefromwebp() function which usually means that the GD extension isn't properly setup. It's also triggered because someone is using a webp file as a backend user avatar, so if you get rid of that file it should start working again. Check your system_files table for files attached to Backend User models with a webp extension and delete them. Once you've done that you should be able to login and update your system.

**Comment by NewEditOfficial** [comment]
@LukeTowers 
I was thinking of it could be the avatar, but wasn't sure, I'm going to try it. 
Thank you

**Comment by NewEditOfficial** [comment]
@LukeTowers Yea, i removed the avatar - it's working ty.
