### ISSUE TITLE
Make uploading screenshots a `required` feature for all plugins to the marketplace

### ISSUE THREAD

**Issue by summercms** [octobercms/october#5308]
The biggest problem I have with the plugin marketplace is trying to second guess what half the plugins do?

Most of the time I don't download the plugins because there is a meaningless short description and if the author spent a few minutes uploading a screenshot of what their plugin actually does? Then I might download it and give it a try.

Please all authors I'm not a mind reader!

Therefore, I request the admins to make screenshots a `required` feature when submitting a plugin to the marketplace!

Then I can fully understand what your plugin does and then can decide to download and install it or not?

### Two points

1. Poor conversion rates

> Common sense, if you want to increase your conversion rates - then add a screenshot!

2. Poor user experience

> Why should I waste 30 minutes of my life downloading and installing your plugin to find out what it's about - when a screenshot could of saved me 29 minutes, trying to work out what your plugin does?

Plugin authors need to think about their users!

**Comment by SebastiaanKloos** [comment]
There are a lot of toolbox / no controller type plugins. So there may be some plugins which can't be screenshotted

**Comment by ayumi-cloud** [comment]
> There are a lot of toolbox / no controller type plugins. So there may be some plugins which can't be screenshotted

Some of those plugins, could take a screenshot of a `code example`, to let users better understand their plugin!

There are very few plugins which maybe don't need a screenshot, like this one: https://octobercms.com/plugin/vojtasvoboda-twigextensions

They have the correct amount of documentation!

~BUT most `toolbox / no controller type plugins` really don't have enough info in their documentation for a new user to understand.

**Comment by ayumi-cloud** [comment]
> There are a lot of toolbox / no controller type plugins. So there may be some plugins which can't be screenshotted

Some of those plugins, could take a screenshot of a `code example`, to let users better understand their plugin!

Do you have a specific plugin example to look at?

I really believe 99.99% of all plugins can do a screenshot in one way or another.

**Comment by summercms** [comment]
> There are a lot of toolbox / no controller type plugins. So there may be some plugins which can't be screenshotted

Some of those plugins, could take a screenshot of a `code example`, to let users better understand their plugin!

Do you have a specific plugin example to look at?

I really believe 99.99% of all plugins can do a screenshot in one way or another.

All plugins either `add`, `upgrade` or `change` a `feature` of some kind. A screenshot can demo that feature.

**Comment by summercms** [comment]
Going to add another comment as I feel strongly on this topic!

I give an example:

There are many plugins in the marketplace that have 1-50 installs, containing a poor description and no screenshots! Clearly those few installs are by the plugin's author and have been installed on the plugin author's websites! Many non plugin author users look at that plugin and can't fully understand what it does and don't choose to install that plugin because of the lack of info the plugin author has done! This makes the plugin marketplace end up with a ton of low quality plugins and also hurts the good plugins - by making it harder to find them as a user now needs to scroll through more (low quality) plugins in the marketplace as time goes on.

My other concern is that there should not be a **one rule for one plugin and another rule for another plugin!** Let's say a plugin has a lot of good information in their description and a screenshot would offer a very tiny enhancement for users to better understand their plugin. They still should add a screenshot. So that we can force all plugins to be a certain `standard level` of quality! Thus improving the plugin marketplace and helping us fully understand `what the plugin is aiming to achieve` and `is it worth installing or not?`

**Comment by bennothommo** [comment]
@ayumi-cloud I agree with your points, however, at the end of the day - the maintainer team (@LukeTowers, @mjauvin and myself) don't have access to the marketplace so we can't realistically make any changes to this process ourselves.

As I've said on Slack though, we have to maintain a careful balance between ensuring quality on the marketplace but also keeping the barrier of entry low. I constantly have debates with people about October vs WordPress, and the one argument I can never win on is the number of plugins available. Even if a lot of WP plugins are hot garbage, most clients (and even some developers) simply don't care - if it works, it works. So it's in our best interest to continue to increase the number of plugins available.

**Comment by summercms** [comment]
@bennothommo Though I strongly disagree with your comment, I don't want to start an argument, plus I don't want to take up too much of your time!

I just list some things I think when reading your comment - you can treat them with a pinch of salt. It's going to be disappointing my side as I know this issue is going to get closed down and nothing happens in the end.

1. You say admins don't have access to the marketplace or the submission process? This is kind of shocking to me and raising red flags! I would like to know more about how the marketplace runs behind the scenes - but I don't want to take up too much of your time and I don't think writing publicly is the answer either.

> Even if a lot of WP plugins are hot garbage, most clients (and even some developers) simply don't care - if it works, it works. So it's in our best interest to continue to increase the number of plugins available.

2. Quality is out of the window and quantity is the goal with the October marketplace then! Opens the flood gates for hackers to create fake plugins and websites to install plugins with security issues. Any hacker reading this you can start running an automatic bot and scrap the vulnerable websites now!

3. If a developer can code a complex sequence - surely they have enough brain power to upload a screenshot? :laughing:

![image](https://user-images.githubusercontent.com/57409060/101916033-4e650380-3bbe-11eb-8d47-0aac14665904.png)

Jokes aside - you've totally put me off using the plugins from the marketplace now.

**Comment by LukeTowers** [comment]
> Do you have a specific plugin example to look at?

https://octobercms.com/plugin/luketowers-twigpcre, https://octobercms.com/plugin/luketowers-tinypng, https://octobercms.com/plugin/luketowers-pwnedpasswords, https://octobercms.com/plugin/luketowers-sentry, https://octobercms.com/plugin/luketowers-gnuterrypratchett. All of those plugins don't need screenshots and there's not much to be gained from requiring them to have screenshots.

I'm going to close this issue for now since there are higher priority issues for us to track that would improve the marketplace in a more measurable way than this, and I personally don't think making screenshots required is the best thing to do at this point in time. Feel free to send an email with your marketplace comments to hello@octobercms.com though.

**Comment by RomainMazB** [comment]
Really interesting subject here! I want to share my thoughts on this one.

I'm on the half way between bennothommo and ayumi-cloud :
• I agree bennothommo: October needs more plugins and themes. Beside others CMS, October is definitely in need of that.
• I agree ayumi-cloud: we should encourage (didn't want to use the term "force") developers to share only high quality plugin.

Long speak (short version at the end) : I speak of OctoberCMS almost every day to all the developers I know and recently I convinced one of my workmate to try it on a personal project, he definitely loved it like I assume all of us did.

I'm talking about that because he made me realize an annoying thing about the plugins discovering and the main process to install them using the backend interface which I think is related to this discussion.

I faced this annoying feeling when I started to intensely use October, the most annoying thing I guess is not the fact that many plugins doesn't provide a screenshot, I prefer a good Readme.md teaching me what the plugin does instead of a screenshot displaying an interface with forms and list we all already know. The most important barrier when I'm searching for a plugin is the fact that when I'm using the backend (which is the fastest and most used way to do in other CMS), I can't see any preview of the plugin itself, when you click on it, it just install the plugin, we can't even see an eventual readme or documentation, you can see it only when it's installed.
This is - for me - the most annoying part when I'm searching a plugin to install to my website.

Short speak: yes, we should encourage the developers to create high quality plugins, and yes the barrier should stay low, but I don't feel like forcing the developer to upload a dummy screenshot is the most important thing to do for the ones who's searching a plugin.

**Comment by mjauvin** [comment]
It's true you cannot see the plugin details from the backend, this is better done from the marketplace.

**Comment by RomainMazB** [comment]
Yep, this is what most of us finally do.

But the ones who came from another CMS feel like frustrating to go outside of the backend to search for a plugin, and then copy/paste the plugin name into it.

A feature to display the readme/documentation directly from backend would be awesome.

I'm putting it on my "no due date PR to make", but since I need to hit the marketplace API which doesn't provide any public documentation AFAIK, it won't be easy for me.

**Comment by summercms** [comment]
@RomainMazB Interesting read of your comment - I opened up a different issue a while back with regards to that as well. The conclusion was allowing plugins to be previewed in a sandbox environment using Docker. 

@LukeTowers 

> Feel free to send an email with your marketplace comments to hello@octobercms.com though.

I feel this conversation in this issue would be great for a `Github Discussions` thread instead. Advantages of that would be allowing other October users to join into the discussion and the topic to be filed in a nice place where other users could view the topic at a later date (In Slack for example the issue gets lost as you need to pay to see old issues) and in (Email other people can't join in the conversation and add their input).

Anyway, I'm suggesting instead of filling up the `Github Issues` with `Marketplace Feedback` it gets moved into `Github Discussions` instead - totally up to you! Just though I'd share my thoughts.

**Comment by LukeTowers** [comment]
> I feel this conversation in this issue would be great for a Github Discussions thread instead. Advantages of that would be allowing other October users to join into the discussion and the topic to be filed in a nice place where other users could view the topic at a later date (In Slack for example the issue gets lost as you need to pay to see old issues) and in (Email other people can't join in the conversation and add their input).

@ayumi-cloud ultimately it doesn't matter what the community says in public discussions or where those comments are made when it comes to the marketplace. @alekseybobkov is who maintains the marketplace, and he does his own research. He monitors hello@octobercms.com though, which is why I recommended that you send an email there.

**Comment by summercms** [comment]
Ok understood, thanks for clarifying!
