### ISSUE TITLE
Upgrade from 1.0 to 1.1 from the backend system

### ISSUE THREAD

**Issue by zimudec** [octobercms/october#5314]
Is it possible to upgrade from the backend system to version 1.1? either with or without composer?

If not, I think that it would be a necessary functionality to avoid resorting to a developer and for an easier and faster upgrade, taking into account that laravel 5.5 is no longer in maintenance since September 2020.

**Comment by LukeTowers** [comment]
The marketplace update for 1.1 is being worked on right now, but in the meantime the answer to all your questions is to use Composer.

**Comment by massimomegistus** [comment]
Hi guys,
do you suggest to upgrade production sites using composer? Is the 1.1.4 release ready and stable for production?
I'm not sure about that because the branch has the "test: failing" badge
https://github.com/octobercms/october/tree/1.1
I know that you are working on the marketplace update for 1.1, may be reasonable to wait for that?
Thank you!

**Comment by daftspunk** [comment]
Hi @massimomegistus, 1.1.4 is tested and can be used for production, in addition, any reported bugs will be addressed promptly. You are welcome to install this version via composer. However, if you have time to wait, we have another release coming soon (1.2) and to save the need to upgrade twice, it would be better to wait for this version to launch

**Comment by massimomegistus** [comment]
Thank you @daftspunk
I'll definitely wait for 1.2 for production upgrade.
In the meantime, I am trying to upgrade an existing 1.0.471 october Application, following these steps
1 Fresh October installation
**composer create-project october/october --prefer-dist --no-dev project_name**
2 disableCoreUpdates setting activation, in config/cms.php
3 php artisan october:env
4 Set mysql connection to the existing 1.0.471 database
5 storage, plugins and themes folders copied to the new app directory
5 php artisan october:up
(only one migration performed)
Migrated:  2021_10_01_000025_Db_Add_Pivot_Data_To_Deferred_Bindings (0.05 seconds)

Everything seems to work well, but the backend dashboard
<img width="960" alt="Schermata 2021-04-01 alle 17 11 55" src="https://user-images.githubusercontent.com/39944924/113316583-cb072380-930e-11eb-9fb6-3e347bfb7d3f.png">
and the System Updates 
<img width="705" alt="Schermata 2021-04-01 alle 17 12 15" src="https://user-images.githubusercontent.com/39944924/113316667-e5d99800-930e-11eb-8919-ac8b555cd826.png">
both display the 471 build number, which is absent in a fresh October installation
<img width="692" alt="Schermata 2021-04-01 alle 17 12 44" src="https://user-images.githubusercontent.com/39944924/113317128-58e30e80-930f-11eb-9f06-b7d98cd7782f.png">

Is there a way to fix this?

Update:
I've just noticed that the build number is saved in the system_parameters table
<img width="478" alt="Schermata 2021-04-01 alle 18 15 58" src="https://user-images.githubusercontent.com/39944924/113323713-926b4800-9316-11eb-8cc4-91e9fe27c7f2.png">
but I don't know if I should worry about that...

Thanks once more for the support!

**Comment by daftspunk** [comment]
@massimomegistus This looks great, a perfect upgrade process. Since v1.1 has not been officially released via the marketplace, it does not display the version in the backend yet. You can inspect the version of october by running the `composer show october/system` command:

```
λ composer show october/system
name     : october/system
descrip. : System module for October CMS
keywords : october, october cms, system
versions : * v1.1.4
```

The upcoming version of October will use this information to display it in the backend. We hope to have this available soon
