### ISSUE TITLE
Duplicated ajax request with group filter 

### ISSUE THREAD

**Issue by danielbidala** [octobercms/october#5365]
If I'm using group filter type in list, the request is sent twice.

### Steps To Reproduce:
The same behavior can be seen when you filter Rainlab Blog's posts with category filter.

October CMS v469

**Comment by LukeTowers** [comment]
This is a complex case. 

In order to aid in our understanding of the problem, please submit [a Pull Request to the test plugin](https://github.com/octoberrain/oc-test-plugin) for investigation that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it _using the test plugin_.

**Comment by LukeTowers** [comment]
Also, please try updating to v1.1 through composer first.

**Comment by bennothommo** [comment]
I can confirm this in the Blog plugin as @danielbidala described, as well as in the Test plugin with the Role filter in the Users page.
