### ISSUE TITLE
SelectConcatenations trait throws Undefined property Builder::$concats

### ISSUE THREAD

**Issue by paishin** [octobercms/october#5372]
After updating OctoberCMS to version 469 my models starting giving me an error about
`Undefined property: Grimzy\LaravelMysqlSpatial\Eloquent\BaseBuilder::$concats`
whenever I try to query a model that uses the SpatialTrait.

Drilling deeper into the error I can see that the problem starts at October\Rain\Database\Query\Grammars\Concerns\SelectConcatenations.php at line 22 where it tries to count $query->concats but \Illuminate\Database\Query\Builder does not have such a property.

I suspect I may need a different version of Laravel but I can't find any version that has that property.

Here is my composer.json :
[composer.txt](https://github.com/octobercms/october/files/5618695/composer.txt)

**Comment by LukeTowers** [comment]
That's because the package that you're using is replacing the QueryBuilder used by the model with it's own that is based on the base Laravel one, while $concats is an October-specific enhancement to the QueryBuilder. You would have to get that package to base it's query building class on October's (which are in turn built on Laravel's) in order for it to work.
