### ISSUE TITLE
Applying italics through the WYSIWYG editor doesn't work for multiple paragraphs

### ISSUE THREAD

**Issue by RyanSimon** [octobercms/october#5380]
- OctoberCMS Build: 1.1.1
- PHP Version: 7.2
- Database Engine: MySQL
- Plugins Installed: RainLab.Blog-v1.4.3

### Description:
Hitting the `I` button in the WYSIWYG editor after highlighting multiple paragraphs correctly applies the `*` at the beginning and end of the highlighted content, but does not apply italics correctly.

As a user I would expect this to work correctly by italicizing all highlighted content. If I replace the `*`'s with `<em>` tags it works just fine.

### Steps To Reproduce:
A quick sample to reproduce this can be as simple as inputting this into the editor
```
*Hello I am paragraph number one.

And I am number two.*
```

You'll see that the preview of the text does not properly italicize and the published content does not receive italics in the web page render either.

**Comment by bennothommo** [comment]
@RyanSimon `<em>` tags are an inline tag that is not supposed to be used across blocks. Given that paragraphs are broken up with paragraph tags, it would not be semantic HTML to surround them with `<em></em>`, which is why you cannot use `*` across paragraphs either.

You'll need to instead wrap each paragraph with `* ... *` to italicise multiple paragraphs.
