### ISSUE TITLE
Repeater with groups - Record finder not bound to controller

### ISSUE THREAD

**Issue by Rike-cz** [octobercms/october#5447]
- OctoberCMS Build: 1.1.1
- PHP Version: 7.4

### Description:
When using repeater **with groups** and new repeater item with Record finder is added, Record finder's search and lists widgets are not bound to controller (cannot search or paginate when selecting record in popup list). Without groups and when updating existing repeater item it works as expected.

**Comment by bennothommo** [comment]
I've been able to confirm this bug, but it will be incredibly difficult to fix.

When trying to bind widgets within repeater items, we use the POST data to determine what repeater items are visible all the way up the hierarchy - mainly using the alias of the widget. In the instance of repeater groups, we have to also rely on a special `_group` variable which determines the group type picked.

However, the pagination and search query box in the List widget within a Record Finder does not POST any information other than what's needed for the query, basically either the page picked, or the search query entered, and the alias of the Record Finder widget. While it would be able to work out the hierarchy for normal repeaters through the alias, it won't work for grouped repeaters because of the lack of `_group` variable, so it doesn't know which widgets to load and bind.

**Comment by LukeTowers** [comment]
@bennothommo would this be fixed by the eventual completion of my requestParent work? https://github.com/octobercms/october/pull/5136

**Comment by daftspunk** [comment]
Hey @Rike-cz. This is a complex case. Please submit a Pull Request to the [test plugin for investigation](https://github.com/octoberrain/oc-test-plugin) that demonstrates the issue. Don't forget to include step by step instructions on how to replicate it *using the test plugin*. Once done, ping me and we can reopen this issue

As an alternative to using a repeater, it might be worthwhile looking at using a traditional relationship or a custom implementation as I've [covered in this screencast](https://octobercms.com/support/article/ob-21). It is always going to be a challenge to make the OEM tools work for every situation, and sometimes a custom solution is just the easiest way to do it
