### ISSUE TITLE
List filters adds no items after 500 records 

### ISSUE THREAD

**Issue by remko-key** [octobercms/october#5459]
- OctoberCMS Build: 1.1 ### 0634060195cac6c558d46b1d3d906d77e24afd00
- PHP Version: 7.3 / 7.4
- Database Engine: MySQL
- Plugins Installed: Translate/Builder/Pages

### Description:

In the list filters items after 500 are not added. When you search for records and try to add an item after 500 the Apply and Clear button don't show up. A trick with adding one from the first 500 that shows these buttons and adding one after the 500's item only adds the one in the first 500. 

### Steps To Reproduce:
See screenshot. Create a filter with more then 500 records, search for record > 500 and click on + sign. No Apply and Clear button appear. 
![2021-01-14_10-37-56](https://user-images.githubusercontent.com/273132/104708663-47ca2e80-571e-11eb-8435-5d6e27acafcb.png)

**Comment by LukeTowers** [comment]
Are there any errors in your developer console?

**Comment by remko-key** [comment]
@LukeTowers There are no errors in the developer console. I also tested it in multiple browsers with the same results.

**Comment by danielbidala** [comment]
I can confirm this bug with build 1.1 and build 0.469. There is not js error in console.

**Comment by danielbidala** [comment]
Related pull request from the past which seems has not solved the problem: #5141 
@bennothommo I recompiled js with `php artisan october:util compile js` Is it working for someone at all?

**Comment by remko-key** [comment]
@danielbidala Did the same here but `php artisan october:util compile js` didn't help

**Comment by danielbidala** [comment]
@meinmotion I investigated a bit and #5141 from @Klaasie solves the problem if you define an `options` method for the scope where you return all of your related model.

In `config_filter.yaml`:
```
scopes:
    customer:
        label: Customer
        type: group
        modelClass: Brightstaff\Brightcrm\Models\Client
        conditions: customer_id in (:filtered)
        options: clientsForFilter
```

In `Client.php` model class:
```
public function clientsForFilter()
{
	return self::query()->pluck('name', 'id')->toArray();
}
```
Anyway I don't think that's a good solution especially if you have tens of thousands of related records.

Another issue with filter widget is that, group filter's query (which receives the select options) runs when the page loads and runs again via ajax request when you open the filter widget's dropdown. This makes no sense. After all of that if you start type in widget's search input, another ajax request runs to search select options array server side. (This could be done on client side since the whole select options array was received before).

**Comment by bennothommo** [comment]
@danielbidala It's pretty clear the filter was never designed for that amount of items, and given it seems that you are using the *search* input of the filter, why not just cut out the middle-man and extend the query of the list itself via the `backend.list.extendQuery` event and use the main search input?

**Comment by danielbidala** [comment]
@bennothommo Thanks for the suggestion, we use list's main search input with custom scope, so we can search related model this way but sometimes we need complex filtering for the list.

> It's pretty clear the filter was never designed for that amount of items

I do not agree with that. I think the filter widget is sophisticated, well structured enough to handle this in some way. I will submit a PR to fix this.

**Comment by danielbidala** [comment]
@meinmotion I've submitted a PR #5470 to fix this.

**Comment by remko-key** [comment]
@danielbidala great thanks for your effort...

**Comment by daftspunk** [comment]
Moved to #5470
