### ISSUE TITLE
Tooltip in first column doesn't work

### ISSUE THREAD

**Issue by rubenvanerk** [octobercms/october#5515]
- OctoberCMS Build: v1.1.1
- PHP Version: 7.4.15
- Database Engine: MySQL
- Plugins Installed: October.Demo, October.Test

### Description:
A tooltip in the first column of a list doesn't work. 
Code responsible: https://github.com/octobercms/october/blob/develop/modules/system/assets/ui/js/list.rowlink.js#L81
I think the content of the first column is hidden _after_ the tooltip is initiated.

### Steps To Reproduce:
1. Create a list with 2 columns with type partial, use a tooltip in the partial for both columns.
2. Hover over both columns.

See PR in test plugin: https://github.com/octoberrain/test-plugin/pull/92

**Comment by daftspunk** [comment]
This a perfect example of a good Pull Request. You're right, this is a race condition where the HTML is duplicated instead of leveraging the existing node element. Changing to `link.after(link.children()).hide();` seems to behave well enough

This change will be available in the next upcoming release. Thanks 🙏
