### ISSUE TITLE
Repeater maxItems bug

### ISSUE THREAD

**Issue by GinoPane** [octobercms/october#5533]
- OctoberCMS Build: 471
- PHP Version: 7.2.4

### Description:
When using repeater with maxItems=1, repeater does not work correctly. It adds one record and still shows the button to add one more. When you remove all records and start adding them again, the repeater works as expected.

### Steps To Reproduce:

![october](https://user-images.githubusercontent.com/3897579/111197337-6b4f0f80-85cf-11eb-931b-1f0f5c09262e.gif)

**Comment by daftspunk** [comment]
Hi @GinoPane, I have tested this and confirm it will be fixed in the upcoming release (available soon). Thanks for the report and for using October CMS! :pray: 

If you find it still occurs after updating, just ping me and we can reopen this issue. My testing was with the [Test Plugin](https://github.com/octoberrain/test-plugin) using the **Countries > Related repeater** and setting `maxItems: 1`

- plugins\october\test\models\country\fields.yaml

It would be worthwhile testing this yourself to ensure we are using the same test conditions.
