### ISSUE TITLE
Validation issue with multiple booleans in required_if

### ISSUE THREAD

**Issue by erwanregnier** [octobercms/october#5535]
- OctoberCMS Build: 471
- PHP Version: 7.3

### Description:
When using multiple boolean tests in a Validator with required_if, the field is always validated even if it shouldn't
The issue is with both test values: true,false or 1,0

### Steps To Reproduce:
**This works:**
```
'has_bill' => ['boolean'],
'billing_type' => ['required_if:has_bill,1', 'boolean'],
'billing_first_name' => ['required_if:billing_type,0'],
```
**This doesn't work**

```
'has_bill' => ['boolean'],
'billing_type' => ['required_if:has_bill,1', 'boolean'],
'billing_first_name' => ['required_if:has_bill,1,billing_type,0'],
```

In the second case, if billing_first_name is empty, the test passed as well without returning an error. As mentioned previously, it doesn't work as well using "true/false" instead of 1/0

**Comment by daftspunk** [comment]
I'm not sure this syntax is valid `'required_if:has_bill,1,billing_type,0'`...

You may need to try:

```
'billing_first_name' => ['required_if:has_bill,1', 'required_if:billing_type,0'],
```

If that fails you can implement custom validation logic in your model like this. It is preferred when dealing with complex validation rules, since the logic is more flexible

    public function beforeValidate()
    {
        if ($this->has_bill && !$this->billing_type && !$this->billing_first_name) {
            throw new \ValidationException(['billing_first_name' => 'First name is required']);
        }
    }

Hope this helps! Thanks for using October CMS 👍
