### ISSUE TITLE
No default language selected for new users

### ISSUE THREAD

**Issue by boyardnicolas** [octobercms/october#5576]
When you create a new user, there are no language selected by default:
1 - on the user settings page, Bahasa Indonesia language is shown, but probably because nothing is selected and Bahasa is the first option of the select list.
2 - the interface is in English even if the browser/system language is not, so I guess it's because the CMS default language is English
3 - when pikaday is trying to display the calendar, it relies on user's picked language, which is undefined, causing the bug:

`Uncaught TypeError: Cannot read property '0' of undefined`

![image](https://user-images.githubusercontent.com/20859005/115648751-96f4b080-a358-11eb-8d7d-aa79b58c859f.png)

Would be nice to automatically set the language to browser's language upon login if no language has been enforced in user settings, or force new users to pick a language as soon as they login, or just set English by default.

**Comment by daftspunk** [comment]
Hi @boyardnicolas ! 

I have tested by doing the following:

1. Login to backend
2. Navigate to Backend Preferences
3. Change language to Bahasa Indonesia
4. The language is now changed
5. Navigate to a page with a `datepicker` used

No error is displayed like in the screenshot.

However, the datepicker is indeed still in English, perhaps because it has not been translated. Notice that the `client.php` file is missing from here:

https://github.com/octobercms/october/tree/develop/modules/system/lang/id

The source for this file can be found here:

https://github.com/octobercms/october/blob/develop/modules/system/lang/en/client.php

May I also ask what version of October CMS you are running? This was tested with v2.0.9 which contains many bug fixes

Thanks!

**Comment by boyardnicolas** [comment]
Hi @daftspunk 
Sorry, didn't think about providing steps to reproduce, I didn't mean that there's a bug with Bahasa Indonesia language.

Steps:
1. Create a new user account
2. Login with that user
3. That user have no language selected in his preferences yet, so the language select field is misleading since it shows Bahasa Indonesia (the first option of the select field)
4. Try to use a form with a date picker, bug happens in my case
5. Pick a language (I only tried English)
6. Check the form again, it should be fine

Currently the system is running with the build 471, so not even v2, just realized I have some serious catching up to do here, maybe that bug is not even happening on v2 (or that issue relevant for that matter).

Let me know if you have possibility to check, if not I'll try to upgrade ASAP and see if still happens.

Thank you.

**Comment by daftspunk** [comment]
We've looked in to this, the default locale for new backend users should be coming from the **config/app.php** file.

```
    /*
    |--------------------------------------------------------------------------
    | Application Locale Configuration
    |--------------------------------------------------------------------------
    |
    | The application locale determines the default locale that will be used
    | by the translation service provider. You are free to set this value
    | to any of the locales which will be supported by the application.
    |
    */

    'locale' => env('APP_LOCALE', 'en'),
```

The above will be observed if the above is set to something that does not appear in the dropdown list.

As a result, I was unable to replicate this. Could you check what value you have set here?
