### ISSUE TITLE
Bad protocol version. Please update to a newer version of October CMS (Build >472 or >v1.1.5) and try again. 

### ISSUE THREAD

**Issue by gladder** [octobercms/october#5586]
It seems like newest version of october has some issues with installing plugins from web. Using Backend and Console also will give

**Bad protocol version. Please update to a newer version of October CMS (Build >472 or >v1.1.5) and try again.**

for installing any Plugin. Since this is reproducable on Docker Images and PROD Instances also this may be an issue inside Octiber itself (?) Fun fact: there is no October CMS Version > 472 or >v1.1.5 ;-)

Workaround is to just git clone the Plugin directly into plugins folder and do a php artisan plugin:refresh Plugin.Name

Any help appreciated - BR, Gladder

**Comment by daftspunk** [comment]
Hi @gladder 

Oh yes, I see, minor typo in that message. >= 472, >= 1.1.5

The gateway has changed its package format and a protocol update is needed to continue working with it. Build 472 and 1.1.5 are tagged and released

- https://github.com/octobercms/october/releases/tag/v1.1.5
- https://github.com/octobercms/october/releases/tag/v1.0.472

The gateway also delivers Build 472 for the web installer and will be delivered via the standard update process

Your workaround is good too, or using composer can work quite well also

**Comment by gladder** [comment]
Hi @daftspunk 

thanks for your response - any idea on how to solve that? I did a forced update by using Backend and Console with no success. I also made a composer update for all libs. Installed version is indeed 472 but still i get that error message when installing plugins using Backend.

Any help very appreciated ;)

BR,
Gladder

**Comment by daftspunk** [comment]
The error should only present itself when you use an old protocol version v1.1. It expects protocol v1.2 to know the new package locations.

The version is contained in this file, at this line: https://github.com/octobercms/october/blob/1.0/modules/system/classes/UpdateManager.php#L966

Please inspect your codebase to ensure it says 1.2, otherwise, I suspect that the file may be stale. It is safe to replace the entire contents with the contents of above in an attempt to fix it -- all the necessary logic is contained within this one file

Best of luck
