### ISSUE TITLE
Undefined index: REMOTE_ADDR  after install

### ISSUE THREAD

**Issue by HomaEEE** [octobercms/october#5597]
Hello, after migrate from old site have some errors:

```
System\Console\ComposerScript::postUpdateCmd
In routes.php line 29:
Undefined index: REMOTE_ADDR  
```

**Comment by daftspunk** [comment]
Hi @HomaEEE 

This looks like it might be caused by a plugin, you'd need to find out where the `routes.php` file is. Or try searching the code base for `REMOTE_ADDR`. It would appear that this plugin does not support execution handling from the command line

If you need further assistance, please send an email to hello@octobercms.com

Thanks
