### ISSUE TITLE
Wrong URL / Missing Port in storage/app URL

### ISSUE THREAD

**Issue by marcoboehrs** [octobercms/october#5609]
OC runs on Port 80 behind a reverse proxy with ssl termination which runs on port 8443. 
I can get all content with https://<ip>:8443 but not the images stored in /var/www/html/storage/app/...

In all URLs, except for the storage urls, the port 8443 is present. See attached screenshot from the chrome web developer tools showing the urls.

![2021-07-13 14_29_20-OC_missing_ports](https://user-images.githubusercontent.com/3685445/125451981-4b8dacc8-524b-40ca-859e-5d3c64898d64.png)

**Comment by daftspunk** [comment]
Hi @marcoboehrs 

This is most likely caused by the `Url::asset()` (broken) directive, which differs from `Url::to()` (working). You may need to define and include the port for the asset URL (`asset_url`) found in the Laravel config file (app.php). See below:

```
    /*
    |--------------------------------------------------------------------------
    | Application URL
    |--------------------------------------------------------------------------
    |
    | This URL is used by the console to properly generate URLs when using
    | the Artisan command line tool. You should set this to the root of
    | your application so that it is used when running Artisan tasks.
    |
    */

    'url' => env('APP_URL', 'http://localhost'),

    'asset_url' => env('ASSET_URL', null),
```

If you require further assistance with this issue and for a faster response time, please email hello@octobercms.com

Thanks!
