### ISSUE TITLE
Tailor Image columns not finding image

### ISSUE THREAD

**Issue by fgschafer** [octobercms/october#5688]
Tailor image columns (at least via fileupload content field) do not find the image path.  If you enter the record, you DO see the image preview, but not in the list.  
I have tested with the link policy set to force and still not showing.  Please see attached image for the path it's trying to reach, its incomplete.  OC is installed in a subfolder (/public_html/subfoldername).
OC v3.2.1
![error](https://user-images.githubusercontent.com/5186031/212168910-e097cf0b-26ec-4567-86f7-1c8b771543ee.png)

**Comment by daftspunk** [comment]
Hi @fgschafer 

Right click on the link and open in a new tab, it should display the error.

**Comment by fgschafer** [comment]
Hi @daftspunk, here it is:
<img width="973" alt="Screen Shot 2023-01-16 at 10 58 14" src="https://user-images.githubusercontent.com/5186031/212695599-a5e07f87-6e94-4de0-b8c9-11c22e5cb584.png">

**Comment by daftspunk** [comment]
Hi @fgschafer 

This looks like it could be unrelated to October CMS since it is showing a vanilla 404 error. Check your web server configuration to find out why the `/resize` route is returning 404. Including access to the [`storage/app/resources` directory](https://github.com/octobercms/october/blob/3.x/.htaccess#L40).
