### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by webfalter** [octobercms/october#5695]
OctoberCMS 3.2 Build  3.2.7

blueprints/blog/ -- Not the separate blog plugin

With the "Planned" option to publish, the post is already displayed in the front end of the page.

![Bildschirmfoto 2023-01-22 um 14 52 42](https://user-images.githubusercontent.com/481551/213920188-7f7eee30-2383-4ded-b4b9-db61cc673613.png)

**Comment by rubenvanerk** [comment]
If I recall correctly, you can always see unpublished blog posts when you're logged in in the backend. Please check again in an incognito window.

**Comment by webfalter** [comment]
I see the post even if I'm not logged into the backend, cookies and session are deleted

**Comment by daftspunk** [comment]
Hi @webfalter 

The visibility issue has been fixed in v3.2.8 (released today). Expired and scheduled entries (posts) are no longer visible when using tailor components.

Regarding the visibility of hidden posts, clicking the Preview button will issue a preview token in the URL to make it visible, allowing the link to be shared to other non-admins.

Please update to v3.2.8 and try again. Thanks!
