### ISSUE TITLE
Safari Login Problem

### ISSUE THREAD

**Issue by guilhermejbranco** [octobercms/october#5700]
Hello,

I'm struggling to login in OctoberCMS v2 using Safari 16.3.

My OctoberCMS instance is running on a docker container, and I can access everything fine in Chrome. Although, when I try to access in Safari, I cannot move past Login.

<img width="1449" alt="Screenshot 2023-02-16 at 18 02 42" src="https://user-images.githubusercontent.com/11890261/219449844-d495eaf8-c060-4464-9628-e6977e1a5a03.png">

When I click login, the browser simply refreshes the page. I could see that no cookie is setted and I don't think that's the expected behaviour. Tried several things without success. My privacy settings for Safari are as follow.
 
<img width="872" alt="Screenshot 2023-02-16 at 18 03 39" src="https://user-images.githubusercontent.com/11890261/219450031-e727860e-6221-4f21-a817-3980a63ffe3f.png">

Can anyone help me?

Thank you in advance.

**Comment by daftspunk** [comment]
Hello @guilhermejbranco 

Sorry to hear about this issue.

We are able log in using Safari without issues. It could be something with your browser or hosting environment, otherwise we would hear from other users. Possible causes:

- **Browser issue**: We recommend checking Safari console for errors. We do not observe any errors in our console. Check that JavaScript is enabled. Check if there are any Cookies or Sessions stored in the Application tab of developer tools.

- **Server issue**: We recommend requesting a demo at https://octobercms.com/ and check to see if you are able to log in here. If you can, it suggests an issue with your hosting provider not allowing cookies/sessions. Strict policies, for example Apache's ModSec, can block the appropriate cookies. Or it can be a configuration issue that Safari is not accepting.

For more help, feel free to visit our online community at: https://talk.octobercms.com

I hope this helps.
