### ISSUE TITLE
Drivers Plugin - S3 force TLS 1.2

### ISSUE THREAD

**Issue by TheFetchZen** [octobercms/october#5715]
Hi,

I got an email from AWS stating that we need to update our TLS connections to 1.2.
We are currently on the v2 of october.

The message:

> "We are reaching out because there are TLS 1.0 or TLS 1.1 connections to Amazon Simple Storage Service (Amazon S3) objects hosted in your account. As AWS is updating the TLS configuration for all AWS API endpoints to a minimum of version TLS 1.2 [1], you must take action as soon as possible for these connections to maintain their access to your S3 objects.
> 
> What actions can I take to maintain access?
> To avoid potential interruption, you must update all client software accessing your Amazon S3 objects using TLS 1.0 or 1.1, to use TLS 1.2 or higher. If you are unable or would prefer to not update all impacted clients, we recommend replacing direct client access to the S3 objects with use of a proxy, such as an Amazon CloudFront distribution. This will allow clients to access your S3 objects via Amazon CloudFront using any TLS version you choose to allow. Amazon CloudFront will forward the calls to your S3 objects using TLS 1.2 or higher. For more guidance for how to setup your CloudFront distribution to front your S3 object access, please review this Knowledge Center article [2].
> 
> ...
> 
> How can I enforce connections to my bucket(s) be over TLSv1.2 and above?
> As a best practice, and to prepare for our enforcement of TLS 1.2 or higher, we recommend you proactively enforce a minimum of TLS 1.2 directly on all of your shared S3 bucket(s). You may do this by applying a bucket policy with the s3:TlsVersion condition key as per the documented this Knowledge Center article [6]
> "

Since the plugin wasn't updated since 2020, I was wondering if this is supported and how to enforce it.
If not, is there a plan to update the plugin?

**Comment by daftspunk** [comment]
Hey @TheFetchZen 

Here is a related link: https://octobercms.com/support/article/rn-32#drivers-plugin

We retired the plugin in v3.0 since drivers can be installed individually using composer. However, we have since improved the platform to support one-click updates and version protection (so v1 sites are safe); and may bring the plugin back out of retirement soon, for sake of convenience.

Regarding the solution to this, try removing the drivers plugin and installing the latest driver in its place. I think the correct driver for OCv2 (Laravel 6) is this one...

```
composer require league/flysystem-aws-s3-v3 "^1.0"
```

...however, this is the same version the drivers plugin uses.

I imagine this would be a common problem for many people using legacy code bases, so it might be worth [checking with the vendor](https://github.com/thephpleague/flysystem-aws-s3-v3/issues).

If this does not resolve the issue, then upgrading to OCv3 may be the next path since Laravel 6 is no longer maintained, and by extension this version of the flysystem driver goes with it.
