### ISSUE TITLE
Image dimensions validation

### ISSUE THREAD

**Issue by molcsan** [octobercms/october#5749]
I'm trying to validate form field with 
```yaml
type: fileupload 
mode: image
```
Using this rules in model it always says image is not valid size.
```php
public $rules = [
    'image_fullscreen' => 'required|image|dimensions:height=600,width=1160'
];
```
I tried to put validate rules to $rules in beforeValidate with Rule class but same thing happened. 

Thank you for any help. 🙏

**Comment by daftspunk** [comment]
Hello @molcsan 

This should be fixed in https://github.com/octobercms/library/commit/f49276d21064946428183c45722412c3c426aad1 and included in the next patch (v3.4.16). There were some unpredictable results especially when uploading and clearing the file multiple times.

For posterity, to confirm this is working, install the Test plugin: https://github.com/octobercms/test-plugin

1. Open file **plugins/october/test/models/User.php**
2. Update the rules object for the `photo` attribute
```php
public $rules = [
    // ...
    'photo' => 'required|image|dimensions:width=430,height=520',
    // ...
];
```
3. Save the form with an image of these dimensions
4. Form saves successfully

Hopefully it works on your side, if not, please `@` my username and we can take another look. Thanks!
