### ISSUE TITLE
CombineAssets combine not working if there are several kubernetes pod

### ISSUE THREAD

**Issue by aifst** [octobercms/october#5750]
version: **v1.1.12**
class: **System\Classes\CombineAssets**
method: **prepareCombiner**

is it possible to adapt part of the logic of the prepareCombiner method to use a different type of cache storage, better with the ability to specify type?

```php
$cache = new FilesystemCache($this->storagePath);
```

instead something like

```php
$cache = Cache::storage();
```

or

```php
if (!$cache = Event::fire('cms.combiner.cachePrepare', [$this], true)) {
  $cache = new FilesystemCache($this->storagePath);
}
```

**Comment by daftspunk** [comment]
Hi @aifst 

[We can add the event here](https://github.com/octobercms/library/blob/3.x/src/Assetic/Combiner.php#L87), although development is now on v3.4, so for you the more significant issue may be upgrading to the latest version and working through the Laravel changes. In the October CMS space, there are minimal breaking changes from v1 to v3.

Closing since we are no longer adding features to v1, however, you may continue to reply here.

**Comment by aifst** [comment]
yes, we are planning a transition to 3.*, it would not be bad to add such an option there

Thank you very much for the prompt reply.
