### ISSUE TITLE
Data error in a field of the nested form type when creating a model.

### ISSUE THREAD

**Issue by Dok2314** [octobercms/october#5759]
Example of my form.yaml:

fields:
    primary:
        label: Primary
        span: auto
        default: 0
        type: switch
    section:
        label: Section
        nameFrom: name
        descriptionFrom: slug
        list: $/authorname/pluginname/models/modelname/recordfinder_columns_for_model.yaml
        span: full
        type: recordfinder
    custom_fields:
        type: nestedform
        showPanel: false
        dependsOn: section
        trigger:
            action: hide
            field: section
            condition: value
        form:
            fields:

<img width="796" alt="Снимок экрана 2023-10-13 в 19 57 34" src="https://github.com/octobercms/october/assets/77670782/490c1b62-6d04-4a82-b2f4-6427ff2ab0ff">

**OctoberCMS 3.3.20:**
I get next data:
``
[
  string primary => 1,
  string section => 2,
  array 'custom_fields' => []
]
``

**OctoberCMS 3.5:**
I get an unpacked array of custom_fields;
``
[]
``

**Comment by Dok2314** [comment]
Any news?!

**Comment by daftspunk** [comment]
Hi @Dok2314 

Sometimes, unconventional code works because of a quirk in the design; when the quirk (bug) is fixed, the code breaks and forces you to write it according to the conventional design pattern.

In this case, your issue is probably because of the following change:

![image](https://github.com/octobercms/october/assets/1392869/c23b9eac-67c7-4a3a-be9f-fcbb89a29f0c)

Here is the reason for the change:

> When NestedForm is not in a relation mode, it currently doesn't process form widgets correctly and it just returns raw post data.
> 
> This causes wrong values to be stored in a database when using more complex form widgets. This PR ensures that data is correctly processed before it is returned from the getSaveValue method.

I'm not 100% sure if this is the problem with your code, but hopefully, it offers some insight into a recent change to `NestedForm`. If you think you've found a bug in the October CMS platform, please [get in touch with the helpdesk](https://octobercms.com/contact).

**Comment by Dok2314** [comment]
My model uses filterFields method, and in OctoberCMS 3.5, I fall into the method when i press "create", and due to changes in the getSaveValue method, I do not receive all the necessary data and get into the method, as a result I hide my own fields, before this did not happen, because all the necessary data came in. Use filterFields - it's not a unconventional code.

**Comment by daftspunk** [comment]
You should be able to access via `post()` in filterFields, hopefully it helps as a workaround.
