### ISSUE TITLE
Non American English Does Not Read en.json Language Files

### ISSUE THREAD

**Issue by sqwk** [octobercms/october#5760]
When creating a `en.json` language file, October correctly parses it only when the site language (Backend Preferences > Region > Locale) is set to `English (United States)`. When selecting any other English like `English (United Kingdom)` language strings to not get displayed.

Tested using the `customMessages.buttonCreate` for a tailor model.

**Comment by daftspunk** [comment]
Thanks @sqwk 

This is an intentional design decision coming from Laravel, and they don't appear to have any intention of addressing it:

> https://github.com/laravel/framework/issues/41565
> The current code works as intended. With JSON translations, there is no usage of a fallback language. The key is the translation.

We can include a fix for this in the next patch since it is a common source of confusion for developers outside the US.

Fixed in https://github.com/octobercms/library/commit/a67c128e873ce689e29781eccd60e1a215385a2f
