### ISSUE TITLE
Saving a CMS Page for a Multisite Overrides Another Site

### ISSUE THREAD

**Issue by sqwk** [octobercms/october#5762]
Saving a CMS page `/` for a multi site (using its own theme) overrides another site's page (using another theme) for the same url. This only happens when the page/theme to edit has been selected using the dot menu > Edit Theme button in the CMS tab. Selecting the site/theme to edit via the menu next to user menu top right of screen works fine.

Saving the falsely overridden CMS page again fixes the routing.

**Comment by daftspunk** [comment]
To clarify:

You have Site A and Site B defined using Theme A and Theme B, respectively. You have Site A selected, then choose Theme B from the Editor menu (not the site picker) and it overrides Theme A's theme?

Is this correct?

**Comment by sqwk** [comment]
> To clarify:
> 
> You have Site A and Site B defined using Theme A and Theme B, respectively. You have Site A selected, then choose Theme B from the Editor menu (not the site picker) and it overrides Theme A's theme?
> 
> Is this correct?

Yes. Correct.

**Comment by daftspunk** [comment]
Hi @sqwk 

Unfortunately, after two separate attempts, we could not reproduce this issue. If you don't mind, could you provide step-by-step instructions from a clean install that demonstrates the issue using the latest version? Then we can take another look.

Thank you

**Comment by sqwk** [comment]
1.  `mkdir octobertest`
1.  `cd octobertest`
1.  `bash -c "$(curl https://octobercms.com/api/dockerdevinstaller)"`
1.  Log into the backend and create a theme blank `themeA` and a blank `themeB`
1.  Activate `themeA`
1.  Create a secondary site `Secondary Site` and use `themeB`
1.  Edit the themes to contain a page with the text "Theme A" or "Theme B" respectively (Both for the url `/`)
1.  Visit `http://localhost:8080/`- The page should say "Theme A"
1.  Go to the Editor, switch sites to the secondary site via the top right dropdown and edit and save  themeB`. Visit `http://localhost:8080/`- The page should still say "Theme A"
1.  Switch sites to the primary site via the top right dropdown, then switch to Theme B via the CMS dropdown and edit and save `themeB`. Visit `http://localhost:8080/`- The page should now say "Theme B"
1.  Refresh the backend CMS editor and open the page in `themeA`, which should still say "Theme A". Refreshing the front end page after having opened the backend page fixes the front-end mismatch.

**Comment by daftspunk** [comment]
Hi @sqwk 

Thanks for the instructions; everything functions here as normal. With these instructions in mind, what is the expected behavior and what is the actual behavior?

Some things of note

- Switching the theme via the CMS menu sets the "Edit theme" for the current user session. This edit session overrides the site definition theme used by the front end. It allows you to preview a different theme for the selected site configuration.

- Switching the theme via the Site menu resets the "Edit theme" to null and will use the site definition rules to determine the displayed frontend theme. This resets the editor to a natural state and displays the front end based on the expected site rules.

#### In step 9

- Theme A is shown since this theme belongs to the primary Site Definition. 

- The Second Site Definition is blocked here since there are no rules (CMS prefix, hostname, app URL, etc.) to determine how to activate it. 

- The editor also cannot produce a valid preview URL for the secondary site since it is not distinct from the primary site.

#### In step 10

- Theme B is shown since the Theme has been changed via the editor menu

- Clicking preview will override any site definition with the "Edit theme" found in the administrator's session.

---

I hope this helps.

**Comment by sqwk** [comment]
So selecting a theme via the editor menu, changes the "Edit theme" for the current user session for that site? That definitely was not expected — there's no clear UI hints that the editor menu should behave any differently than the site selection menu, although there's a small HUD that the "Edit theme has changed". (Note that I did not click "Preview" in step 10.) However, I guess this can remain closed as works as expected nevertheless.

**Comment by daftspunk** [comment]
Yes, this is a point of confusion for expectations, since they both function differently. However, using one menu exclusively tends to avoid it. We've got an issue for this internally to add a global indicator when the "Edit Theme" is active in the session, that will hopefully clear up any confusion when both are used.

Thanks for reporting back!
