### ISSUE TITLE
Are UI components still valid in OctoberCMS 3?

### ISSUE THREAD

**Issue by harmenjanssen** [octobercms/october#5765]
Hi,
I'm upgrading from OctoberCMS 2 to 3, but I'm noticing some missing styles and in some cases get some Javascript errors when working with UI components. 

For instance, when working with a modal dialog (https://octobercms.com/docs/ui/popup), I'm getting an error `Uncaught TypeError: Cannot read properties of undefined (reading 'backdrop')`. 

Also, the styling utilities (https://octobercms.com/docs/ui/utilities) for adding margin and such seem to have disappeared.

Is the [documentation for UI components](https://octobercms.com/docs/ui) still valid, or should I look elsewhere?

**Comment by daftspunk** [comment]
Hi @harmenjanssen 

Short answer: Partially valid, for now. Use [Bootstrap 5 docs](https://getbootstrap.com/docs/5.3/).

Long answer:

October v1 + v2 both used a modified version of Bootstrap 3 called "Storm UI".

In October v3, Storm was replaced by a direct implementation of Bootstrap 5. This was a big job, but it was achieved with minimal disruption, thanks to the maturity of Bootstrap--staying true to its design patterns.

Some unavoidable code changes are required in upgrading, outlined here:
https://octobercms.com/support/article/rn-31

Since the internals are different, some properties will be different between Bootstrap v3 and v5.

WRT to the documentation, Bootstrap 5 is miles ahead now, and that includes more utilities, found here: https://getbootstrap.com/docs/5.3/layout/utilities/

All the BS5 docs are available in the backend panel now. They are the replacement for the October UI component docs, except for the icon documentation which will be replaced with a dedicated documentation page soon.

I hope this helps.

**Comment by harmenjanssen** [comment]
Thanks for your quick answer, I will chase the docs!
