### ISSUE TITLE
October 3.6 - Update error

### ISSUE THREAD

**Issue by Dahfrenk** [octobercms/october#5781]
When attempting to upgrade to October 3.6 using php artisan october:update the following error occurs;

`In Container.php line 891:
Target class [system.cacher] does not exist.`

`In Container.php line 889:
Class "system.cacher" does not exist`

The update is aborted and I have to run the command again for the database migration to be done and the update to be successfully completed. I believe I came from v3.5.14 and I am running on PHP 8.3.

**Comment by daftspunk** [comment]
Hey @Dahfrenk 

The `system.cacher` class is a new addition to 3.6 since most singletons live in the container now.

Assuming this is updating via the admin panel, I updated from 3.5.3 to 3.6.0 just now and didn't get this error, although I had debug mode enabled. With debug mode disabled, it's possible this could have been caused by a cached container mapping that resets when it encounters an error.

We'll keep this open for a few in case anyone else bumps into this issue.

**Comment by Dahfrenk** [comment]
Thank you for your quick reply, I was updating with the `php artisan october:update` command through the terminal. And my debug mode is indeed disabled.

**Comment by Samuell1** [comment]
Not sure why but we have same issue but for ocms v3.5 version when we want to run seeder with plugin:seed , maybe its related to caching somehow. Because we run this seed command on production enviroment.

![image](https://github.com/octobercms/october/assets/3110002/93d9fdd1-de3e-449c-9b0b-6de81e11704e)

**Comment by daftspunk** [comment]
Another customer has reported this today, so it is now a confirmed >2 issue.

Added advice to the release note: https://octobercms.com/support/article/rn-37#upgrade-instructions
