### ISSUE TITLE
The system.manage_logs role for "Log Settings" is not enabled

### ISSUE THREAD

**Issue by aifst** [octobercms/october#5800]
In the settings, section "Logs" there is a setting for "Access Log", but now it is only available for the super admin, it is not available for other users. Apparently because "system.manage_logs" is not described anywhere

System\ServiceProvider::registerSettings()

**Comment by daftspunk** [comment]
I have reviewed it, and I think it was left like this since, optimally, it should have its own permission. However, this is too granular for such a simple page. We can reuse the "utilities.logs" permission for this, even though it goes outside of the "View Logs" descriptor.

It will be set like this in v3.7.3

Thanks!
