### ISSUE TITLE
Could not translate relation type 'morphMany' to a valid field type

### ISSUE THREAD

**Issue by mabehiry** [octobercms/october#5820]
My model has the following morph relationship:

```php
public $morphMany = [
    'recordings' => ['sunsoft\courses\models\Meetingrecording', 'name' => 'recordable']
];
```

it works fine when I add or get it, but when I try to display it in the backend form like this:

```yaml
recordings:
        type: relation
```

I get the following error:
Could not translate relation type 'morphMany' to a valid field type
~/modules/backend/formwidgets/Relation.php line 162

**Comment by daftspunk** [comment]
Hi @mabehiry 

The relation `morphToMany` and `morphedByMany` is supported here. We will need to investigate further why the `morphMany` relation isn't included in the list.

**Comment by daftspunk** [comment]
Hi @mabehiry 

The error appears because a checkbox list cannot display available records since they "belong to" the parent record, so it only makes sense in the context of creating records (see below).

This works if you use the controller definition in the field: https://docs.octobercms.com/3.x/element/form/widget-relation.html#relation-controller-integration

Best regards
