### ISSUE TITLE
[Bug] Relations and sorting in controllers forms

### ISSUE THREAD

**Issue by tiipiik** [octobercms/october#596]
Hi,

Finally I've find the problem I was having with my plugin. I have two fields which are relations. All is fine until I click on sorting on one of this relations. I have been able to reproduce that in the Blog plugin, which has the same relation type.
In the Rainlab.Blog, create a category, create a post, then click on sort by categories. You hould have a js alert that indicates "Unknown column @name...". Click ok, then reload the page, you should have an exception with the same error message.
It seems that the resquest is stored in the session file, that's why on reload the error is stiil here. Delete the session file, reload and all is fine.
Don't known exaclty where the problem is, but if I can help...

Argh, this is not in the controller form but in the controller list.

**Comment by tschallacka** [comment]
@daftspunk is it possible to make default sortable: false if it's a relation? Would help a lot in making list views with as first column a relationship with columns that are only relationships.
Otherwise I keep getting exceptions that it tries to sort on non existing columnnames(the relation field names)
