### ISSUE TITLE
Ace editor customization (font size/color scheme)

### ISSUE THREAD

**Issue by anfrantic** [octobercms/october#63]
Ace editor default font size is uncomfortable size, would be great to have an option to set the desired fontsize somewhere in the panel

**Comment by avlight** [comment]
Hello guys! I have a question related to image size and customization into the blog post.
For example, I have that code for image integration:
![9_main.jpg](http://hql-blog.loc/storage/app/uploads/public/5a9/a2b/0db/5a9a2b0db7aec777751196.jpg)

How can I change its width or height, maybe border and etc.
Where can I find some format documentation for this?

**Comment by LukeTowers** [comment]
@avlight please don't highjack unrelated issues for your questions; there are lots of other avenues for asking questions in the community.

@avlight Github issues really isn't the place for questions like this. Please use one of the many other avenues available instead of highjacking unrelated issues for your questions.

Forum: http://octobercms.com/forum
StackOverflow: http://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or http://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/

**Comment by avlight** [comment]
@LukeTowers thank you for answer.
And it is not only a question ;)
