### ISSUE TITLE
Disabled plugins don't update correctly

### ISSUE THREAD

**Issue by Flynsarmy** [octobercms/october#778]
### Bug summary
When a plugin is disabled, updates appear and download/install for that plugin, but it does not get updated and they will show again next update check

### Request location
Backend > Settings > Updates

### Reproduce steps
* In updates area of admin click 'Manage Plugins'
* Disable one or more plugins (preferrably one that has an update available for the purpose of this demo)
* Go back for updates and check for updates - you'll see your disabled plugin in the updates list
* Try to update - it will appear as if it worked
* Check for updates again - the plugin will be back in the updates list again
I am not using a project.

### Expected result:
The plugin should update itself

### Actual result
The plugin does not update.

**Comment by daftspunk** [comment]
Disabling a plugin only prevents it from booting, the classes and its presence in the file system cannot be disabled. If the plugin does not report itself to the update server then it may try to download again, causing potentially destructive changes.

Simply remove the plugin instead of disabling it. You can now also remove plugins from projects.
