### ISSUE TITLE
Using Twig markup inside widgets partials

### ISSUE THREAD

**Issue by Whyounes** [octobercms/october#809]
Is there a way to use Twig inside my widgets partials? if no, i thinks it should be added!!

Also, i think that grouping widgets inside a specific folder is much better than being on the plugin root directory, any thoughts on that?

**Comment by daftspunk** [comment]
```

public function makeTwigPartial($name)
{
    $twig = App::make('twig.string');
    $contents = call_user_func_array([$this, makePartial], func_get_args());
    return $twig->render($contents);
}
```

**Comment by alexeydemin** [comment]
For those who were misled by documentation, expecting to find full-fledged partials on the backend this might help:
```
public function makePartial($partial, $params = [], $throwException = true)
{
    return Twig::parse(parent::makePartial($partial), $params);
}
```
Unfortunately, partial section splitting won't work anyway.

**Comment by LukeTowers** [comment]
@alexeydemin what do you mean by misled? Do you have any specific suggestions for improving the documentation?

**Comment by alexeydemin** [comment]
Sorry @LukeTowers the straightforward phrasing, but I'd rather remove 2 bottom code blocks from this section 
https://octobercms.com/docs/backend/widgets#generic-widgets since it's impossible to pass any variable to the widget partial.
Also, I'd remove "equivalent" word because basically what the widget partial can do is rendering of a simple html.

**Comment by LukeTowers** [comment]
Make a PR to the docs repository with your suggested changes @alexeydemin

**Comment by munxar** [comment]
> section
https://octobercms.com/docs/backend/widgets#generic-widgets since it's impossible to pass any variable to the widget partial.

Imho this two blocks are correct. I use widget partials all the time and I *can* pass data to them.
Do you have any specific example what doesn't work, when passing data to partials?

**Comment by lieszkol** [comment]
I agree with @alexeydemin - the OctoberCMS documentation is very vague when it comes to how partials are rendered inside backend plugin settings pages.

For example, it was not at all obvious to me that twig tags are not processed here. 

Something simple like including an image that I uploaded into my /plugins/author/plugin/assets/ directory without hard-coding the path in the partial took way too long to figure out.

**Comment by w20k** [comment]
@lieszkol if you have a minute and a will to provide an update to the docs, it's highly appreciated (or tips&tricks to octobertricks.com) :)
