### ISSUE TITLE
Access denied for user with permission

### ISSUE THREAD

**Issue by luciano-jr** [octobercms/october#831]
When set permission for user of just "Manage mail templates" in settings section "System" on manager users group: 
![edit group october cms](https://cloud.githubusercontent.com/assets/3333167/5426127/4a40cbd4-8325-11e4-802b-2de1e6f42b0e.png)
and set permission on "Cms":
![edit group october cms 1](https://cloud.githubusercontent.com/assets/3333167/5426133/8bdf971e-8325-11e4-8a56-6d015a1961c5.png)

and after create a user in this group with follows configs (all inherit):
![edit administrator october cms](https://cloud.githubusercontent.com/assets/3333167/5426135/a7712bc8-8325-11e4-8d45-f5db3b7e7b05.png)

When I try sing in with this user: 
![access denied](https://cloud.githubusercontent.com/assets/3333167/5426139/000535c2-8326-11e4-8414-87a1b93ff6db.png)

**Comment by daftspunk** [comment]
This will be fixed in next build

**Comment by alvaro-canepa** [comment]
This problem is not solved. I'm using the build 293 and when click `Save and Close` on user profile (without dashboard permission) give the `Access Denied` page.

The controller in `/backend/backend/users` must redirect like the main dashboard do. Or, more simple, remove the `Save and Close` button.

Thanks and sorry my English.

**Comment by daftspunk** [comment]
@alvaro-canepa This is a separate issue, fixed in Build 294+

**Comment by alvaro-canepa** [comment]
Thanks ;)
