### ISSUE TITLE
Ugly urls when linking assets.

### ISSUE THREAD

**Issue by serialscoper101** [octobercms/october#853]
I have a problem when I try linking documents with the twig filters in the docs.  For example, notice how in this url - ```http://www.mhscompsci.com/themes/october-theme/assets/courses/compsci2/Lecture%20DocumentsII/Intro%20to%20OO%20Dev%20&%20Terms.doc - ``` there is /themes/october-theme/theme/assets/*.

This linking format is very ugly and I was wondering where in the repo I could find the code section that routes the twig filters.  Then I could setup a rule in .htacces to rewrite the new requests to the old ugly url.  Something like this-
```RewriteRule (.+) /themes/october-theme/assets/$1```.
You can test it out [on this site](http://htaccess.madewithlove.be/) with this url ```http://www.mhscompsci.com/courses/compsci2/Lecture%20DocumentsII/Intro%20to%20OO%20Dev%20&%20Terms.doc``` and the mentioned .htaccess code.
If I am confusing you, feel free to ask.

**Comment by daftspunk** [comment]
I would suggest using a routes.php file either in the **app/** or in your own plugin, then have the route redirect to the longer [uglier] link.

Otherwise your suggestion using .htaccess is good too, you will need to make your own twig filter for creating these links though, you can find this [in the documentation](https://octobercms.com/docs/plugin/registration#extending-twig).
