### ISSUE TITLE
Backend users page throws exception

### ISSUE THREAD

**Issue by mosid** [octobercms/october#883]
When navigating to backend/users i get the following exception
![screenshot from 2015-01-11 12 44 23](https://cloud.githubusercontent.com/assets/5040354/5694882/46df877e-9990-11e4-85f2-959d4b9b598f.png).
octobercms build 174 on ubuntu 14.04 php5 apache postgresql
plugins installed : Translate - Blog - users

**Comment by dtaub** [comment]
I'm getting this as well. It looks like the issue is in October\Rain\Database\Dongle::parseConcat(). It's trying to parse a string with nested parentheses (because of the cast), and the regex can't handle that. PHP does support recursive regexes which may solve it, but I'm not too familiar with recursive regexes.

**Comment by mosid** [comment]
You where truly right @dtaub .
I  added the `(?R)` flag to `October\Rain\Database\Dongle::parseConcat()` in line 107 like this:
`'/(?:group_)?concat\(([^)]+)\)(?R)/i'` and it worked like a charm.
well spotted.

**Comment by daftspunk** [comment]
Looks good, submit as a pull request to the library@develop branch.
