### ISSUE TITLE
Drag and drop reordering of lists [$25]

### ISSUE THREAD

**Issue by chrisnharvey** [octobercms/october#943]
It would be great if it was possible to enable the ability to reorder lists in the backend using drag and drop.

It would also be great if this worked within relation lists too.

Is this a planned feature? If not, is this something you'd be happy me adding via a PR?

**Comment by chrisnharvey** [comment]
I'm about to start work on this. I'll keep this thread updated.

If anyone has any suggestions on how this should work then please let me know.

**Comment by daftspunk** [comment]
Please hold off on this, it is a planned feature.

**Comment by chrisnharvey** [comment]
Nice one, I'll leave it to you guys then.

**Comment by 7talents** [comment]
Is this coming soon? I would have to write my own otherwise anyway, because there is a time issue on my side of things...

**Comment by MatissJanis** [comment]
It would be amazing to have this one implemented. Currently I've seen some plugins using their own versions of drag&drop sorting.

**Comment by CptMeatball** [comment]
Is there any update on this? Would be an awesome feature!

**Comment by pvullioud** [comment]
Yes, this could be very usefull to standardise the way to manage order with drag&drop

**Comment by NemoD503** [comment]
+1 for this feature

**Comment by sajjad-ser** [comment]
+1

**Comment by that0n3guy** [comment]
Whats the $10 bounty thing?  My company will pay that right now.

**Comment by daftspunk** [comment]
It means someone has put up $10 to see this happen

**Comment by tsioukas** [comment]
Also it would be good to be compatible with showTree option of lists. Sometimes it's good to have grouped rows.

This project provides a good example of drag/drop lists/tables. Also it have a powerful API to control almost everything. http://johnny.github.io/jquery-sortable

**Comment by jonpxpx** [comment]
@daftspunk let me know where I need to paypal, this USD or AUD?

**Comment by jonpxpx** [comment]
And ignore me, turns out I didnt see the link before posting... :+1:

**Comment by 7talents** [comment]
I think this needs explaining - at least to me it did ;-)
The bounty means that (at this point) two people have agreed to pay money if someone solves this.
It does not mean that you pay (at this point) $ 25 and @daftspunk or someone else solves this right away...

**Comment by jBOKA** [comment]
+1
I am willing to look into this, but I'm not sure where to start. The feature might somehow be integrated into the list behaviour I guess.

How would you guys imagine this reordering thing to work? The Sortable trait from the core defines the logic for saving a sort_oder (or any other column name) of type integer to the database. One would just have to setup the model and database accordingly. But I'm not sure if this helps, since the usual configuration stuff regarding list behaviour is managed via the models yaml files or the controller yaml configs. But the trait cannot be added on runtime, so this has to be implemented differently I guess.

Anyway, two quenstions I've run into:

In case of a list of all model items, this is pretty straight forward, i.e. we could rearrange the list via drag&drop and save all items' sort_order to the database, giving each item a unique integer.
But if we want it to work in different contexts like a relation list (where not all items [e.g. only related] are listed), would we just set new order numbers for the current set of items?

And also how should this work in regard to the sortable functions from the columns.yaml of the model that defines how the list widget handles sorting. Would it make sense to either make automatic sorting possible, as it's defined right now or to restrict everything to manual sorting?

Any ideas?

**Comment by clone45** [comment]
+1

**Comment by tsioukas** [comment]
Is there any documentation for this new feature, or if not do you have it in your todo list?

**Comment by hybridvision** [comment]
@tsioukas - https://octobercms.com/docs/backend/reorder :)

**Comment by tsioukas** [comment]
Thanks, I was looking on Lists, I thought that Sorting Records was from older release :). Maybe a different title will be better.

**Comment by hybridvision** [comment]
Maybe it could be called "reordering" instead of "sorting" but in the case of documentation for new features, a good place to check is the documentation repository: https://github.com/octobercms/docs/commits/master

**Comment by tdolph** [comment]
How can i user reorder functionality with relaton manager?

**Comment by CptMeatball** [comment]
Haven't tried any of these, but maybe look at one of these:

https://github.com/scottbedard/draganddrop
http://octobercms.com/forum/post/reordering-items-in-a-relation#post-13983

You can also perform a `queryFilter` on the reorder view. For this you need to add the id for the relation to the reorder controllerview. 

So your URL would besomething like: `/acme/relationcontroller/reorder/{id}`. 
And in your controller you would add a filter on the reorder view to only load the relationship models.
