### ISSUE TITLE
TrustedProxies

### ISSUE THREAD

**Issue by drtzack** [octobercms/october#955]
Some servers make proxy-pass nginx to apache. So we cannot get client IP.

To solve this we should add:
Request::setTrustedProxies(array('server-ip')); 

It could be nice if you add this to october.

**Comment by daftspunk** [comment]
This looks like it should be addressed at the framework level, Laravel might already have a solution. Otherwise this issue does not completely describe the problem and propose any type of workable solution moving forward.

**Comment by DeeJaVu** [comment]
do something about it fucking morons

**Comment by daftspunk** [comment]
I don't really have a deep understanding of this problem. For someone who
does, if this can be fixed gracefully within the platform, feel free to
submit a PR.

Otherwise perhaps this should be a plugin, that implements this composer
package (https://github.com/fideloper/TrustedProxy) or somthing like it.
Then register the middleware as part of the service provider (
http://octobercms.com/docs/plugin/registration#registering-middleware).

Beyond someone educating me further or offering a tangible solution, I
can't be much more help than that, sorry.

**Comment by seanthepottingshed** [comment]
@DeeJaVu Someone needs to resolve their anger issues ;)
